// src/svelte-frontend/src/routes/pension/savings/[id]/edit/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { m } from '$lib/paraglide/messages.js';
	import { pensionApi } from '$lib/api/pension';
	import { pensionStore } from '$lib/stores/pension.svelte';
	import { toastStore } from '$lib/stores/toast.svelte';
	import { PensionType, CompoundingFrequency } from '$lib/types/pension';
	import type { SavingsPension, ContributionStep } from '$lib/types/pension';
	import PageHeader from '$lib/components/ui/PageHeader.svelte';
	import Card from '$lib/components/ui/Card.svelte';
	import ContentSection from '$lib/components/ui/ContentSection.svelte';
	import Explanation from '$lib/components/ui/Explanation.svelte';
	import ExplanationAlert from '$lib/components/ui/ExplanationAlert.svelte';
	import ExplanationList from '$lib/components/ui/ExplanationList.svelte';
	import ExplanationListItem from '$lib/components/ui/ExplanationListItem.svelte';
	import BasicInformationCard from '$lib/components/pension/savings/BasicInformationCard.svelte';
	import InterestRatesCard from '$lib/components/pension/savings/InterestRatesCard.svelte';
	import StatementsCard from '$lib/components/pension/savings/StatementsCard.svelte';
	import ContributionPlanCard from '$lib/components/pension/ContributionPlanCard.svelte';
	import PensionStatusActions from '$lib/components/pension/PensionStatusActions.svelte';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	let pensionId = $derived(data.pensionId);

	// Loading/error state
	let loadError = $state('');
	let submitting = $state(false);

	// Pension data
	let pension = $state<SavingsPension | null>(null);

	// Form state
	let name = $state('');
	let startDate = $state('');
	let notes = $state('');
	let compoundingFrequency = $state<CompoundingFrequency>(CompoundingFrequency.ANNUALLY);
	// Rates stored as decimals (0.02 = 2%)
	let pessimisticRate = $state(0.01);
	let realisticRate = $state(0.02);
	let optimisticRate = $state(0.03);

	interface StatementFormData {
		id: number;
		pension_id: number;
		statement_date: string;
		balance: number;
		note?: string;
	}
	let statements = $state<StatementFormData[]>([]);
	let contributionPlanSteps = $state<ContributionStep[]>([]);
	let errors = $state<Record<string, string>>({});

	function hydrateForm(currentPension: SavingsPension) {
		name = currentPension.name;
		startDate = currentPension.start_date;
		notes = currentPension.notes ?? '';
		compoundingFrequency = currentPension.compounding_frequency;
		// API rates are percentages (2.0 = 2%), convert to decimals for form
		pessimisticRate = currentPension.pessimistic_rate / 100;
		realisticRate = currentPension.realistic_rate / 100;
		optimisticRate = currentPension.optimistic_rate / 100;
		statements = (currentPension.statements ?? []).map((statement) => ({
			...statement,
			balance: statement.balance ?? 0
		}));
		contributionPlanSteps = (currentPension.contribution_plan_steps ?? []).map((step) => ({
			...step
		}));
	}

	$effect(() => {
		loadError = data.initialError;
		pension = data.initialPension;
		if (data.initialPension) {
			hydrateForm(data.initialPension);
		}
	});

	function validate(): boolean {
		const newErrors: Record<string, string> = {};
		if (!name.trim()) newErrors.name = m.savings_pension_name_required();
		if (!startDate) newErrors.start_date = m.savings_pension_start_date_required();
		errors = newErrors;
		return Object.keys(newErrors).length === 0;
	}

	async function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		if (!validate() || !pension) return;

		submitting = true;
		try {
			// Savings pension does NOT accept statements in the update body —
			// update pension first, then manage statements via their own endpoints.
			const pensionData = {
				name: name.trim(),
				start_date: startDate,
				notes: notes.trim() || '',
				// Convert decimals back to percentages for API
				pessimistic_rate: pessimisticRate * 100,
				realistic_rate: realisticRate * 100,
				optimistic_rate: optimisticRate * 100,
				compounding_frequency: compoundingFrequency,
				contribution_plan_steps: contributionPlanSteps.map(step => ({
					id: step.id,
					amount: step.amount,
					frequency: step.frequency,
					start_date: step.start_date,
					end_date: step.end_date || undefined,
					note: step.note || ''
				}))
			};

			await pensionApi.update(PensionType.SAVINGS, pensionId, pensionData);

			// Manage statements separately:
			// - id === 0 → new statement, POST
			// - id > 0 → existing statement, PUT to update
			await Promise.all(
				statements
					.filter(s => s.statement_date)
					.map(s => {
						const payload = {
							statement_date: s.statement_date,
							balance: s.balance || 0,
							note: s.note || ''
						};
						return s.id
							? pensionApi.updateSavingsPensionStatement(pensionId, s.id, payload)
							: pensionApi.addSavingsPensionStatement(pensionId, payload);
					})
			);

			toastStore.success(m.savings_pension_updated());
			goto('/pension');
		} catch (error) {
			console.error('Error updating savings pension:', error);
			toastStore.error(error instanceof Error ? error.message : m.savings_pension_update_failed());
		} finally {
			submitting = false;
		}
	}

	async function handlePause(pauseDate: string) {
		try {
			await pensionStore.updateStatus(PensionType.SAVINGS, pensionId, {
				status: 'PAUSED',
				paused_at: pauseDate
			});
			pension = await pensionApi.get<SavingsPension>(PensionType.SAVINGS, pensionId);
		} catch (error) {
			console.error('Error pausing pension:', error);
			toastStore.error(error instanceof Error ? error.message : m.savings_pension_update_failed());
		}
	}

	async function handleResume(resumeDate: string) {
		try {
			await pensionStore.updateStatus(PensionType.SAVINGS, pensionId, {
				status: 'ACTIVE',
				resume_at: resumeDate
			});
			pension = await pensionApi.get<SavingsPension>(PensionType.SAVINGS, pensionId);
		} catch (error) {
			console.error('Error resuming pension:', error);
			toastStore.error(error instanceof Error ? error.message : m.savings_pension_update_failed());
		}
	}
</script>

<div class="space-y-6">
	<!-- Header -->
	<div class="flex flex-col space-y-4 sm:flex-row sm:justify-between sm:space-y-0 sm:items-center">
		<PageHeader
			title={m.savings_pension_edit_title()}
			description={m.savings_pension_edit_description()}
		/>
		<div class="flex space-x-4 shrink-0">
			<button
				type="button"
				onclick={() => history.back()}
				class="px-4 py-2 bg-secondary hover:bg-secondary/80 text-secondary-foreground rounded-lg text-sm font-medium transition-colors"
			>
				{m.cancel()}
			</button>
			<button
				type="submit"
				form="savings-pension-form"
				disabled={submitting}
				class="px-4 py-2 bg-primary hover:bg-primary/90 text-primary-foreground rounded-lg text-sm font-medium transition-colors disabled:opacity-50"
			>
				{m.savings_pension_save()}
			</button>
		</div>
	</div>

	{#if loadError}
		<div class="bg-destructive/10 border border-destructive/30 rounded-xl p-4 text-destructive">
			<p>{loadError}</p>
		</div>
	{:else if !pension}
		<div class="bg-destructive/10 border border-destructive/30 rounded-xl p-4 text-destructive">
			<p>{m.savings_pension_not_found()}</p>
		</div>
	{:else}
		<form id="savings-pension-form" onsubmit={handleSubmit} class="space-y-8">
			<!-- Basic Information Section -->
			<ContentSection>
				{#snippet aside()}
					<Explanation>
						<p>{m.savings_pension_explanation_intro()}</p>
						<ExplanationList>
							<ExplanationListItem><strong>{m.savings_pension_name()}:</strong> {m.savings_pension_explanation_name()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.savings_pension_start_date()}:</strong> {m.savings_pension_explanation_start_date()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.savings_pension_compounding_frequency()}:</strong> {m.savings_pension_explanation_compounding()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.savings_pension_notes()}:</strong> {m.savings_pension_explanation_notes()}</ExplanationListItem>
						</ExplanationList>
						<ExplanationAlert>
							{m.savings_pension_explanation_alert()}
						</ExplanationAlert>
					</Explanation>
				{/snippet}
				<Card title={m.savings_pension_basic_info()} description={m.savings_pension_basic_info_edit_description()}>
					{#snippet headerActions()}
						<PensionStatusActions
							status={pension!.status}
							onPause={handlePause}
							onResume={handleResume}
						/>
					{/snippet}
					<BasicInformationCard bind:name bind:startDate bind:compoundingFrequency bind:notes {errors} />
				</Card>
			</ContentSection>

			<!-- Interest Rates Section -->
			<ContentSection>
				{#snippet aside()}
					<Explanation>
						<p>{m.savings_pension_interest_rates_explanation_intro()}</p>
						<ExplanationList>
							<ExplanationListItem><strong>{m.savings_pension_pessimistic_rate()}:</strong> {m.savings_pension_interest_rates_explanation_pessimistic()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.savings_pension_realistic_rate()}:</strong> {m.savings_pension_interest_rates_explanation_realistic()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.savings_pension_optimistic_rate()}:</strong> {m.savings_pension_interest_rates_explanation_optimistic()}</ExplanationListItem>
						</ExplanationList>
						<ExplanationAlert>
							{m.savings_pension_interest_rates_explanation_alert()}
						</ExplanationAlert>
					</Explanation>
				{/snippet}
				<Card title={m.savings_pension_interest_rates()} description={m.savings_pension_interest_rates_description()}>
					<InterestRatesCard bind:pessimisticRate bind:realisticRate bind:optimisticRate />
				</Card>
			</ContentSection>

			<!-- Statements Section -->
			<ContentSection>
				{#snippet aside()}
					<Explanation>
						<p>{m.savings_pension_statements_explanation_intro()}</p>
						<ExplanationList>
							<ExplanationListItem><strong>{m.savings_pension_statement_date()}:</strong> {m.savings_pension_statements_explanation_date()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.savings_pension_balance()}:</strong> {m.savings_pension_statements_explanation_balance()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.savings_pension_statement_note()}:</strong> {m.savings_pension_statements_explanation_note()}</ExplanationListItem>
						</ExplanationList>
						<ExplanationAlert>
							{m.savings_pension_statements_explanation_alert()}
						</ExplanationAlert>
					</Explanation>
				{/snippet}
				<Card title={m.savings_pension_statements()} description={m.savings_pension_statements_description()}>
					<StatementsCard bind:statements {pensionId} />
				</Card>
			</ContentSection>

			<!-- Contribution Plan Section -->
			<ContentSection>
				{#snippet aside()}
					<Explanation>
						<p>{m.savings_pension_contribution_plan_explanation_intro()}</p>
						<ExplanationList>
							<ExplanationListItem><strong>{m.contribution_amount()}:</strong> {m.savings_pension_contribution_plan_explanation_amount()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.contribution_frequency()}:</strong> {m.savings_pension_contribution_plan_explanation_frequency()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.contribution_start_date()} / {m.contribution_end_date()}:</strong> {m.savings_pension_contribution_plan_explanation_dates()}</ExplanationListItem>
						</ExplanationList>
						<ExplanationAlert>
							{m.savings_pension_contribution_plan_explanation_alert()}
						</ExplanationAlert>
					</Explanation>
				{/snippet}
				<ContributionPlanCard bind:steps={contributionPlanSteps} />
			</ContentSection>
		</form>
	{/if}
</div>

// app/pension/savings/[id]/edit/page.tsx
"use client"

import { useForm } from "react-hook-form"
import { useRouter } from "next/navigation"
import { Form } from "@/frontend/components/ui/form"
import { Button } from "@/frontend/components/ui/button"
import { SavingsPensionFormData } from "@/frontend/types/pension-form"
import { PensionType, SavingsPension, SavingsPensionStatement } from "@/frontend/types/pension"
import { toast } from "sonner"
import { zodResolver } from "@hookform/resolvers/zod"
import { savingsPensionSchema } from "@/frontend/lib/validations/pension"
import { ErrorBoundary } from "@/frontend/components/shared/ErrorBoundary"
import { BasicInformationCard } from "@/frontend/components/pension/savings/BasicInformationCard"
import { InterestRatesCard } from "@/frontend/components/pension/savings/InterestRatesCard"
import { StatementsCard } from "@/frontend/components/pension/savings/StatementsCard"
import { ContributionPlanCard } from "@/frontend/components/pension/savings/ContributionPlanCard"
import { FormLayout, FormSection } from "@/frontend/components/shared"
import { BasicInformationExplanation } from "@/frontend/components/pension/savings/explanations/BasicInformationExplanation"
import { InterestRatesExplanation } from "@/frontend/components/pension/savings/explanations/InterestRatesExplanation"
import { StatementsExplanation } from "@/frontend/components/pension/savings/explanations/StatementsExplanation"
import { ContributionPlanExplanation } from "@/frontend/components/pension/savings/explanations/ContributionPlanExplanation"
import { getPensionListRoute } from "@/frontend/lib/routes"
import { toISODateString } from "@/frontend/lib/dateUtils"
import React, { useState, useEffect, useMemo } from "react"
import { useSavingsPension, useUpdateSavingsPension, useUpdateSavingsPensionStatus } from "@/frontend/hooks/useSavingsPensions"
import { Alert, AlertDescription, AlertTitle } from "@/frontend/components/ui/alert"
import { LoadingState } from "@/frontend/components/shared/LoadingState"
import { savingsPensionToForm } from "@/frontend/lib/transformers/savingsPensionTransformers"
import { PensionStatusActions } from "@/frontend/components/pension/shared/PensionStatusActions"
import { PauseConfirmationDialog } from "@/frontend/components/pension/shared/dialogs/PauseConfirmationDialog"
import { ResumeDateDialog } from "@/frontend/components/pension/shared/dialogs/ResumeDateDialog"

interface EditSavingsPensionPageProps {
  params: Promise<{
    id: string
  }>
}

export default function EditSavingsPensionPage({ params }: EditSavingsPensionPageProps) {
  const router = useRouter()
  const resolvedParams = React.use(params)
  const pensionId = parseInt(resolvedParams.id)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [showPauseDialog, setShowPauseDialog] = useState(false)
  const [showResumeDialog, setShowResumeDialog] = useState(false)
  
  // Use React Query hook to fetch pension data
  const { 
    data: pension,
    isLoading,
    error
  } = useSavingsPension(pensionId)
  
  const { mutateAsync: updatePension } = useUpdateSavingsPension(pensionId)
  const { mutateAsync: updateStatus } = useUpdateSavingsPensionStatus()

  // Unified loading state for consistency
  const loadingState = useMemo(() => ({
    isPageLoading: isLoading,
    isSubmitting,
    isAnyLoading: isLoading || isSubmitting
  }), [isLoading, isSubmitting]);

  // Helper function to check if pension is of SAVINGS type
  const isPensionTypeValid = useMemo(() => {
    // Always show loading state if we're still loading pension data
    if (loadingState.isPageLoading) return true;
    
    // If pension data is loaded but null, there's a real issue
    if (!pension) return false;
    
    // Special case: If type is an empty string on page refresh, treat it as valid
    if (!pension.type || String(pension.type).trim() === "") return true;
    
    // Normal case: Compare the types
    return String(pension.type) === String(PensionType.SAVINGS);
  }, [pension, loadingState.isPageLoading]);

  // Initialize form with the pension data once it's loaded
  const form = useForm<SavingsPensionFormData>({
    resolver: zodResolver(savingsPensionSchema),
    // We'll set default values when the pension data loads
    defaultValues: pension ? savingsPensionToForm(pension) : undefined
  })

  // Update form data when pension data loads
  useEffect(() => {
    if (pension) {
      const formData = savingsPensionToForm(pension)
      form.reset(formData) // This reinitializes the form with the data
    }
  }, [pension, form])

  // Handle form submission
  const handleSubmit = async (data: SavingsPensionFormData) => {
    try {
      setIsSubmitting(true)
      const memberId = parseInt(data.member_id)
      if (isNaN(memberId)) {
        toast.error("Error", { description: "Invalid member ID" })
        return
      }

      // Process statements to match SavingsPensionStatement[]
      const statements: SavingsPensionStatement[] = data.statements
        .filter(statement => statement.statement_date) // Only include statements with dates
        .map(statement => {
          // Create a valid statement object
          const processedStatement: SavingsPensionStatement = {
            pension_id: pensionId,
            statement_date: toISODateString(statement.statement_date),
            balance: statement.balance,
            note: statement.note || "",
            // Only include id if it exists and is a number
            id: statement.id || 0
          }
          return processedStatement
        })

      // Create a pension data object that matches what the API expects
      const pensionData = {
        type: PensionType.SAVINGS as const,
        name: data.name,
        member_id: memberId,
        start_date: toISODateString(data.start_date),
        notes: data.notes || "",
        
        // Interest rates
        pessimistic_rate: data.pessimistic_rate,
        realistic_rate: data.realistic_rate,
        optimistic_rate: data.optimistic_rate,
        
        // Compounding frequency
        compounding_frequency: data.compounding_frequency,
        
        // Status
        status: data.status,
        
        // Statements (already processed above)
        statements: statements,
        
        // Contribution plan steps (convert dates to ISO strings)
        contribution_plan_steps: data.contribution_plan_steps.map(step => ({
          amount: step.amount,
          frequency: step.frequency,
          start_date: toISODateString(step.start_date),
          end_date: step.end_date ? toISODateString(step.end_date) : undefined,
          note: step.note || ""
        }))
      }
      
      // Update the pension using React Query mutation
      await updatePension(pensionData as unknown as Partial<SavingsPension>)
      
      toast.success("Success", { description: "Savings pension updated" })
      router.push(getPensionListRoute())
    } catch (error) {
      console.error("Error updating savings pension:", error)
      toast.error("Error", { 
        description: error instanceof Error 
          ? error.message 
          : "Failed to update savings pension" 
      })
    } finally {
      setIsSubmitting(false)
    }
  }

  // Handle status changes
  const handlePauseConfirm = async (pauseDate: Date) => {
    try {
      await updateStatus({
        pensionId,
        statusData: {
          status: 'PAUSED',
          paused_at: toISODateString(pauseDate)
        }
      })
      toast.success("Success", { description: "Savings pension paused successfully" })
      setShowPauseDialog(false)
    } catch (error) {
      console.error("Error pausing savings pension:", error)
      toast.error("Error", { 
        description: error instanceof Error 
          ? error.message 
          : "Failed to pause savings pension" 
      })
    }
  }

  const handleResumeConfirm = async (resumeDate: Date) => {
    try {
      await updateStatus({
        pensionId,
        statusData: {
          status: 'ACTIVE',
          resume_at: toISODateString(resumeDate)
        }
      })
      toast.success("Success", { description: "Savings pension resumed successfully" })
      setShowResumeDialog(false)
    } catch (error) {
      console.error("Error resuming savings pension:", error)
      toast.error("Error", { 
        description: error instanceof Error 
          ? error.message 
          : "Failed to resume savings pension" 
      })
    }
  }

  return (
    <ErrorBoundary>
      <div className="container">
        {/* Page header with title and buttons */}
        <div className="flex flex-col space-y-4 sm:flex-row sm:justify-between sm:space-y-0 sm:items-center mb-6">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Edit Savings Pension</h1>
            <p className="text-muted-foreground mt-2">
              Update your savings account details and track your retirement savings over time.
            </p>
          </div>
          
          <div className="flex space-x-4">
            <Button
              type="button"
              variant="outline"
              onClick={() => router.back()}
            >
              Cancel
            </Button>
            <Button 
              type="submit"
              form="savings-pension-form"
              disabled={loadingState.isAnyLoading}
            >
              Save Changes
            </Button>
          </div>
        </div>

        {loadingState.isPageLoading ? (
          <LoadingState message="Loading pension details..." />
        ) : error ? (
          <Alert variant="destructive">
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>{(error as Error).message}</AlertDescription>
          </Alert>
        ) : !pension ? (
          <Alert variant="destructive">
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>Pension not found</AlertDescription>
          </Alert>
        ) : !isPensionTypeValid ? (
          <Alert variant="destructive">
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>
              Invalid pension type: &ldquo;{pension.type}&rdquo; (expected: &ldquo;{PensionType.SAVINGS}&rdquo;)
            </AlertDescription>
          </Alert>
        ) :
          <Form {...form}>
            <form 
              id="savings-pension-form"
              onSubmit={form.handleSubmit(handleSubmit)} 
            >
              <FormLayout>
                {/* Basic Information Section */}
                <FormSection
                  title="Basic Information"
                  description="Enter the basic details of your savings account"
                  explanation={<BasicInformationExplanation />}
                  headerActions={
                    <PensionStatusActions
                      status={pension.status}
                      onPause={() => setShowPauseDialog(true)}
                      onResume={() => setShowResumeDialog(true)}
                    />
                  }
                >
                  <BasicInformationCard form={form} />
                </FormSection>
                
                {/* Interest Rates Section */}
                <FormSection
                  title="Interest Rates"
                  description="Configure interest rates for different scenarios"
                  explanation={<InterestRatesExplanation />}
                >
                  <InterestRatesCard form={form} />
                </FormSection>
                
                {/* Statements Section */}
                <FormSection
                  title="Account Statements"
                  description="Record your savings account balance over time"
                  explanation={<StatementsExplanation />}
                >
                  <StatementsCard form={form} pensionId={pensionId} />
                </FormSection>
                
                {/* Contribution Plan Section */}
                <FormSection
                  title="Contribution Plan"
                  description="Set up your regular deposits to this savings account"
                  explanation={<ContributionPlanExplanation />}
                >
                  <ContributionPlanCard form={form} />
                </FormSection>
              </FormLayout>
            </form>
          </Form>
        }
      </div>

      {/* Dialog components */}
      <PauseConfirmationDialog
        open={showPauseDialog}
        onOpenChange={setShowPauseDialog}
        onConfirm={handlePauseConfirm}
      />
      
      <ResumeDateDialog
        open={showResumeDialog}
        onOpenChange={setShowResumeDialog}
        onConfirm={handleResumeConfirm}
      />
    </ErrorBoundary>
  )
}
