// src/frontend/components/shared/inputs/CurrencyInput.tsx
"use client"

import { useSettings } from '@/frontend/context/SettingsContext'
import { NumberInput } from './NumberInput'
import { getCurrencySymbol, getDefaultCurrencyPosition } from '@/frontend/lib/transforms'

interface CurrencyInputProps extends Omit<React.ComponentProps<typeof NumberInput>, 'prefix' | 'suffix'> {
  showSymbol?: boolean
}

/**
 * CurrencyInput component for handling currency input.
 * Extends NumberInput component with currency symbol display.
 * 
 * @component
 * @example
 * // Basic usage
 * <CurrencyInput 
 *   value={1234.56} 
 *   onChange={setValue} 
 * />
 */
export function CurrencyInput({ 
  showSymbol = true,
  decimals = 2,
  className = '',
  ...props
}: CurrencyInputProps) {
  const { settings } = useSettings()
  const currencySymbol = getCurrencySymbol(settings.number_locale, settings.currency)
  const currencyPosition = getDefaultCurrencyPosition(settings.number_locale)
  
  const symbolClassName = showSymbol 
    ? currencyPosition === 'prefix' 
      ? 'pl-7' 
      : 'pr-7'
    : ''
  
  return (
    <div className="relative">
      {showSymbol && currencyPosition === 'prefix' && (
        <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">
          {currencySymbol}
        </span>
      )}
      
      <NumberInput
        {...props}
        decimals={decimals}
        className={`${className} ${symbolClassName}`}
      />
      
      {showSymbol && currencyPosition === 'suffix' && (
        <span className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground">
          {currencySymbol}
        </span>
      )}
    </div>
  )
}

// src/svelte-frontend/src/lib/components/ui/CurrencyInput.svelte
<script lang="ts">
	import { settingsStore } from '$lib/stores/settings.svelte';
	import { getCurrencySymbol, getCurrencyPosition } from '$lib/utils/format';
	import NumberInput from './NumberInput.svelte';

	let {
		value = $bindable(0),
		decimals = 2,
		min,
		max,
		showSymbol = true,
		disabled = false,
		class: className = ''
	}: {
		value: number;
		decimals?: number;
		min?: number;
		max?: number;
		showSymbol?: boolean;
		disabled?: boolean;
		class?: string;
	} = $props();

	let symbol = $derived(getCurrencySymbol(settingsStore.current.number_locale, settingsStore.current.currency));
	let position = $derived(getCurrencyPosition(settingsStore.current.number_locale));
</script>

{#if showSymbol}
	<div class="relative {className}">
		{#if position === 'prefix'}
			<span class="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">{symbol}</span>
		{/if}
		<NumberInput
			bind:value
			{decimals}
			{min}
			{max}
			{disabled}
			class={position === 'prefix' ? 'pl-7' : 'pr-7'}
		/>
		{#if position === 'suffix'}
			<span class="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">{symbol}</span>
		{/if}
	</div>
{:else}
	<NumberInput bind:value {decimals} {min} {max} {disabled} class={className} />
{/if}
