// src/frontend/components/shared/inputs/PercentInput.tsx
"use client"

import { NumberInput } from './NumberInput'

interface PercentInputProps extends Omit<React.ComponentProps<typeof NumberInput>, 'prefix' | 'suffix'> {
  showSymbol?: boolean
}

/**
 * PercentInput component for handling percentage input.
 * Extends NumberInput component with percentage-specific features.
 * Values are stored as decimals (0.05 for 5%) but displayed as percentages (5%).
 * 
 * @component
 * @example
 * // Basic usage (displays 5% for value 0.05)
 * <PercentInput 
 *   value={0.05} 
 *   onChange={setValue} 
 * />
 */
export function PercentInput({ 
  value, 
  onChange,
  showSymbol = true,
  decimals = 1,
  min,
  max,
  className = '',
  ...props
}: PercentInputProps) {
  return (
    <div className="relative">
      <NumberInput
        {...props}
        // Display value as percentage
        value={value !== null && value !== undefined ? value * 100 : null}
        // Store value as decimal
        onChange={newValue => onChange(newValue !== null ? newValue / 100 : null)}
        decimals={decimals}
        // Convert min/max to percentage for display
        min={min !== undefined ? min * 100 : undefined}
        max={max !== undefined ? max * 100 : undefined}
        className={`${className} ${showSymbol ? 'pr-7' : ''}`}
      />
      
      {showSymbol && (
        <span className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground">
          %
        </span>
      )}
    </div>
  )
}

// src/svelte-frontend/src/lib/components/ui/PercentInput.svelte
<script lang="ts">
	import NumberInput from './NumberInput.svelte';

	let {
		value = $bindable(0),
		decimals = 1,
		min,
		max,
		showSymbol = true,
		disabled = false,
		class: className = ''
	}: {
		value: number;
		decimals?: number;
		min?: number;
		max?: number;
		showSymbol?: boolean;
		disabled?: boolean;
		class?: string;
	} = $props();

	// Display as percentage (5) but store as decimal (0.05)
	let displayValue = $state(value * 100);

	// Sync inward: external value → display
	$effect(() => {
		const rounded = Math.round(value * 100 * 10 ** decimals) / 10 ** decimals;
		if (Math.abs(rounded - displayValue) > 0.0001) {
			displayValue = rounded;
		}
	});

	// Sync outward: display → external value
	$effect(() => {
		const newValue = displayValue / 100;
		if (Math.abs(newValue - value) > 0.000001) {
			value = newValue;
		}
	});
</script>

{#if showSymbol}
	<div class="relative {className}">
		<NumberInput
			bind:value={displayValue}
			{decimals}
			min={min !== undefined ? min * 100 : undefined}
			max={max !== undefined ? max * 100 : undefined}
			{disabled}
			class="pr-7"
		/>
		<span class="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">%</span>
	</div>
{:else}
	<NumberInput
		bind:value={displayValue}
		{decimals}
		min={min !== undefined ? min * 100 : undefined}
		max={max !== undefined ? max * 100 : undefined}
		{disabled}
		class={className}
	/>
{/if}
