// app/pension/state/[id]/edit/page.tsx
"use client"

import { useForm } from "react-hook-form"
import { useRouter } from "next/navigation"
import { Form } from "@/frontend/components/ui/form"
import { Button } from "@/frontend/components/ui/button"
import { StatePensionFormData } from "@/frontend/types/pension-form"
import { PensionType, StatePensionStatement } from "@/frontend/types/pension"
import { toast } from "sonner"
import { zodResolver } from "@hookform/resolvers/zod"
import { statePensionSchema } from "@/frontend/lib/validations/pension"
import { ErrorBoundary } from "@/frontend/components/shared/ErrorBoundary"
import { BasicInformationCard } from "@/frontend/components/pension/state/BasicInformationCard"
import { StatementsCard } from "@/frontend/components/pension/state/StatementsCard"
import { ScenarioViewer } from "@/frontend/components/pension/state/ScenarioViewer"
import { FormLayout, FormSection } from "@/frontend/components/shared"
import { BasicInformationExplanation } from "@/frontend/components/pension/state/explanations/BasicInformationExplanation"
import { StatementsExplanation } from "@/frontend/components/pension/state/explanations/StatementsExplanation"
import { ScenariosExplanation } from "@/frontend/components/pension/state/explanations/ScenariosExplanation"
import { getPensionListRoute } from "@/frontend/lib/routes"
import { toISODateString } from "@/frontend/lib/dateUtils"
import React, { useState } from "react"
import { useStatePension, useUpdateStatePension, useUpdateStatePensionStatus } from "@/frontend/hooks/pension/useStatePensions"
import { Alert, AlertDescription, AlertTitle } from "@/frontend/components/ui/alert"
import { LoadingState } from "@/frontend/components/shared/LoadingState"
import { statePensionToForm } from "@/frontend/lib/transformers/statePensionTransformers"
import { PensionStatusActions } from "@/frontend/components/pension/shared/PensionStatusActions"
import { PauseConfirmationDialog } from "@/frontend/components/pension/shared/dialogs/PauseConfirmationDialog"
import { ResumeDateDialog } from "@/frontend/components/pension/shared/dialogs/ResumeDateDialog"

interface EditStatePensionPageProps {
  params: Promise<{
    id: string
  }>
}

export default function EditStatePensionPage({ params }: EditStatePensionPageProps) {
  const router = useRouter()
  const resolvedParams = React.use(params)
  const pensionId = parseInt(resolvedParams.id)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [showPauseDialog, setShowPauseDialog] = useState(false)
  const [showResumeDialog, setShowResumeDialog] = useState(false)
  
  // Use React Query hook to fetch pension data
  const { 
    data: pension,
    isLoading,
    error
  } = useStatePension(pensionId)
  
  const { mutateAsync: updatePension } = useUpdateStatePension()
  const { mutateAsync: updateStatus } = useUpdateStatePensionStatus()

  // Initialize form with the pension data once it's loaded
  const form = useForm<StatePensionFormData>({
    resolver: zodResolver(statePensionSchema),
    // We'll set default values when the pension data loads
    defaultValues: pension ? statePensionToForm(pension) : undefined
  })

  // Handle form submission
  const handleSubmit = async (data: StatePensionFormData) => {
    try {
      setIsSubmitting(true)
      const memberId = parseInt(data.member_id)
      if (isNaN(memberId)) {
        toast.error("Error", { description: "Invalid member ID" })
        return
      }

      // Process statements to match StatePensionStatement[]
      const statements: StatePensionStatement[] = data.statements
        .filter(statement => statement.statement_date) // Only include statements with dates
        .map(statement => {
          // Create a valid statement object
          const processedStatement: StatePensionStatement = {
            pension_id: pensionId,
            statement_date: toISODateString(statement.statement_date),
            current_monthly_amount: statement.current_monthly_amount || undefined,
            projected_monthly_amount: statement.projected_monthly_amount || undefined,
            current_value: statement.current_value || undefined,
            note: statement.note || "",
            // Only include id if it exists and is a number
            id: statement.id || 0 // Must have an id as per StatePensionStatement
          }
          return processedStatement
        })

      // Create a pension data object that matches what the API expects
      const pensionData = {
        type: PensionType.STATE as const,
        name: data.name,
        member_id: memberId,
        start_date: toISODateString(data.start_date),
        notes: data.notes || "",
        status: data.status,
        statements
      }
      
      // Update the pension using React Query mutation
      await updatePension({ 
        id: pensionId, 
        data: pensionData 
      })
      
      toast.success("Success", { description: "State pension updated" })
      router.push(getPensionListRoute())
    } catch (error) {
      console.error("Error updating state pension:", error)
      toast.error("Error", { 
        description: error instanceof Error 
          ? error.message 
          : "Failed to update state pension" 
      })
    } finally {
      setIsSubmitting(false)
    }
  }

  // Handle status changes
  const handlePauseConfirm = async (pauseDate: Date) => {
    try {
      await updateStatus({
        pensionId,
        statusData: {
          status: 'PAUSED',
          paused_at: toISODateString(pauseDate)
        }
      })
      toast.success("Success", { description: "State pension paused successfully" })
      setShowPauseDialog(false)
    } catch (error) {
      console.error("Error pausing state pension:", error)
      toast.error("Error", { 
        description: error instanceof Error 
          ? error.message 
          : "Failed to pause state pension" 
      })
    }
  }

  const handleResumeConfirm = async (resumeDate: Date) => {
    try {
      await updateStatus({
        pensionId,
        statusData: {
          status: 'ACTIVE',
          resume_at: toISODateString(resumeDate)
        }
      })
      toast.success("Success", { description: "State pension resumed successfully" })
      setShowResumeDialog(false)
    } catch (error) {
      console.error("Error resuming state pension:", error)
      toast.error("Error", { 
        description: error instanceof Error 
          ? error.message 
          : "Failed to resume state pension" 
      })
    }
  }

  return (
    <ErrorBoundary>
      <div className="container mx-auto py-10">
        {/* Page header with title and buttons */}
        <div className="flex flex-col space-y-4 sm:flex-row sm:justify-between sm:space-y-0 sm:items-center mb-6">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Edit State Pension</h1>
            <p className="text-muted-foreground mt-2">
              Update your state pension details and track your benefits over time.
            </p>
          </div>
          
          <div className="flex space-x-4">
            <Button
              type="button"
              variant="outline"
              onClick={() => router.back()}
            >
              Cancel
            </Button>
            <Button 
              type="submit"
              form="state-pension-form"
              disabled={isLoading || isSubmitting}
            >
              Save Changes
            </Button>
          </div>
        </div>

        {isLoading ? (
          <LoadingState message="Loading pension details..." />
        ) : error ? (
          <Alert variant="destructive">
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>{(error as Error).message}</AlertDescription>
          </Alert>
        ) : !pension ? (
          <Alert variant="destructive">
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>Pension not found</AlertDescription>
          </Alert>
        ) : pension.type !== undefined && pension.type !== PensionType.STATE ? (
          <Alert variant="destructive">
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>Invalid pension type</AlertDescription>
          </Alert>
        ) : (
          <Form {...form}>
            <form 
              id="state-pension-form"
              onSubmit={form.handleSubmit(handleSubmit)} 
            >
              <FormLayout>
                {/* Basic Information Section */}
                <FormSection
                  title="Basic Information"
                  description="Keep your state pension details up to date"
                  explanation={<BasicInformationExplanation />}
                  headerActions={
                    <PensionStatusActions
                      status={pension.status}
                      onPause={() => setShowPauseDialog(true)}
                      onResume={() => setShowResumeDialog(true)}
                    />
                  }
                >
                  <BasicInformationCard form={form} />
                </FormSection>
                
                {/* Statements Section */}
                <FormSection
                  title="Pension Statements"
                  description="Record information from your state pension statements"
                  explanation={<StatementsExplanation />}
                >
                  <StatementsCard form={form} pensionId={pensionId} />
                </FormSection>

                {/* Scenarios Section */}
                <FormSection
                  title="Pension Scenarios"
                  description="View projections of future benefits based on retirement age and growth rates"
                  explanation={<ScenariosExplanation />}
                >
                  <ScenarioViewer pensionId={pensionId} />
                </FormSection>
              </FormLayout>
            </form>
          </Form>
        )}
      </div>

      {/* Replace the AlertDialogs with custom dialog components */}
      <PauseConfirmationDialog
        open={showPauseDialog}
        onOpenChange={setShowPauseDialog}
        onConfirm={handlePauseConfirm}
      />
      
      <ResumeDateDialog
        open={showResumeDialog}
        onOpenChange={setShowResumeDialog}
        onConfirm={handleResumeConfirm}
      />
    </ErrorBoundary>
  )
}

// src/svelte-frontend/src/routes/pension/state/[id]/edit/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import { m } from '$lib/paraglide/messages.js';
	import { pensionApi } from '$lib/api/pension';
	import { pensionStore } from '$lib/stores/pension.svelte';
	import { PensionType } from '$lib/types/pension';
	import type { StatePension } from '$lib/types/pension';
	import PageHeader from '$lib/components/ui/PageHeader.svelte';
	import Card from '$lib/components/ui/Card.svelte';
	import ContentSection from '$lib/components/ui/ContentSection.svelte';
	import Explanation from '$lib/components/ui/Explanation.svelte';
	import ExplanationAlert from '$lib/components/ui/ExplanationAlert.svelte';
	import ExplanationList from '$lib/components/ui/ExplanationList.svelte';
	import ExplanationListItem from '$lib/components/ui/ExplanationListItem.svelte';
	import BasicInformationCard from '$lib/components/pension/state/BasicInformationCard.svelte';
	import StatementsCard from '$lib/components/pension/state/StatementsCard.svelte';
	import ScenarioViewer from '$lib/components/pension/state/ScenarioViewer.svelte';
	import PensionStatusActions from '$lib/components/pension/PensionStatusActions.svelte';

	// Get pension ID from route params
	let pensionId = $derived(Number($page.params.id));

	// Loading/error state
	let loading = $state(true);
	let loadError = $state('');
	let submitting = $state(false);

	// Pension data
	let pension = $state<StatePension | null>(null);

	// Form state
	let name = $state('');
	let startDate = $state('');
	let notes = $state('');
	interface StatementFormData {
		id: number;
		pension_id: number;
		statement_date: string;
		current_monthly_amount: number;
		projected_monthly_amount: number;
		current_value: number;
		note?: string;
	}
	let statements = $state<StatementFormData[]>([]);
	let errors = $state<Record<string, string>>({});

	// Toast
	let toast = $state<{ message: string; type: 'success' | 'error' } | null>(null);
	function showToast(message: string, type: 'success' | 'error') {
		toast = { message, type };
		setTimeout(() => { toast = null; }, 3000);
	}

	onMount(async () => {
		try {
			pension = await pensionApi.get<StatePension>(PensionType.STATE, pensionId);
			// Populate form
			name = pension.name;
			startDate = pension.start_date;
			notes = pension.notes ?? '';
			statements = (pension.statements ?? []).map(s => ({
				...s,
				current_monthly_amount: s.current_monthly_amount ?? 0,
				projected_monthly_amount: s.projected_monthly_amount ?? 0,
				current_value: s.current_value ?? 0
			}));
		} catch (e) {
			loadError = e instanceof Error ? e.message : m.state_pension_not_found();
		} finally {
			loading = false;
		}
	});

	function validate(): boolean {
		const newErrors: Record<string, string> = {};
		if (!name.trim()) newErrors.name = m.state_pension_name_required();
		if (!startDate) newErrors.start_date = m.state_pension_start_date_required();
		errors = newErrors;
		return Object.keys(newErrors).length === 0;
	}

	async function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		if (!validate() || !pension) return;

		submitting = true;
		try {
			const pensionData = {
				type: PensionType.STATE,
				name: name.trim(),
				member_id: pension.member_id,
				start_date: startDate,
				notes: notes.trim() || '',
				status: pension.status,
				statements: statements
					.filter(s => s.statement_date)
					.map(s => ({
						id: s.id || 0,
						pension_id: pensionId,
						statement_date: s.statement_date,
						current_monthly_amount: s.current_monthly_amount || undefined,
						projected_monthly_amount: s.projected_monthly_amount || undefined,
						current_value: s.current_value || undefined,
						note: s.note || ''
					}))
			};

			await pensionApi.update(PensionType.STATE, pensionId, pensionData);
			showToast(m.state_pension_updated(), 'success');
			goto('/pension');
		} catch (error) {
			console.error('Error updating state pension:', error);
			showToast(
				error instanceof Error ? error.message : m.state_pension_update_failed(),
				'error'
			);
		} finally {
			submitting = false;
		}
	}

	async function handlePause(pauseDate: string) {
		try {
			await pensionStore.updateStatus(PensionType.STATE, pensionId, {
				status: 'PAUSED',
				paused_at: pauseDate
			});
			pension = await pensionApi.get<StatePension>(PensionType.STATE, pensionId);
		} catch (error) {
			console.error('Error pausing pension:', error);
			showToast(error instanceof Error ? error.message : 'Failed to pause pension', 'error');
		}
	}

	async function handleResume(resumeDate: string) {
		try {
			await pensionStore.updateStatus(PensionType.STATE, pensionId, {
				status: 'ACTIVE',
				resume_at: resumeDate
			});
			pension = await pensionApi.get<StatePension>(PensionType.STATE, pensionId);
		} catch (error) {
			console.error('Error resuming pension:', error);
			showToast(error instanceof Error ? error.message : 'Failed to resume pension', 'error');
		}
	}
</script>

<!-- Toast -->
{#if toast}
	<div
		class="fixed top-4 right-4 z-50 px-4 py-3 rounded-xl shadow-lg text-sm font-medium border {toast.type === 'success'
			? 'bg-card text-foreground border-primary/30'
			: 'bg-card text-destructive border-destructive/30'}"
	>
		{toast.message}
	</div>
{/if}

<div class="space-y-6">
	<!-- Header -->
	<div class="flex flex-col space-y-4 sm:flex-row sm:justify-between sm:space-y-0 sm:items-center">
		<PageHeader
			title={m.state_pension_edit_title()}
			description={m.state_pension_edit_description()}
		/>
		<div class="flex space-x-4 shrink-0">
			<button
				type="button"
				onclick={() => history.back()}
				class="px-4 py-2 bg-secondary hover:bg-secondary/80 text-secondary-foreground rounded-lg text-sm font-medium transition-colors"
			>
				{m.cancel()}
			</button>
			<button
				type="submit"
				form="state-pension-form"
				disabled={loading || submitting}
				class="px-4 py-2 bg-primary hover:bg-primary/90 text-primary-foreground rounded-lg text-sm font-medium transition-colors disabled:opacity-50"
			>
				{m.state_pension_save()}
			</button>
		</div>
	</div>

	{#if loading}
		<p class="text-center text-muted-foreground py-8">{m.state_pension_loading()}</p>
	{:else if loadError}
		<div class="bg-destructive/10 border border-destructive/30 rounded-xl p-4 text-destructive">
			<p>{loadError}</p>
		</div>
	{:else if !pension}
		<div class="bg-destructive/10 border border-destructive/30 rounded-xl p-4 text-destructive">
			<p>{m.state_pension_not_found()}</p>
		</div>
	{:else}
		<form id="state-pension-form" onsubmit={handleSubmit} class="space-y-8">
			<!-- Basic Information Section -->
			<ContentSection>
				{#snippet aside()}
					<Explanation>
						<p>{m.state_pension_explanation_intro()}</p>
						<ExplanationList>
							<ExplanationListItem><strong>{m.state_pension_name()}:</strong> {m.state_pension_explanation_name()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.state_pension_start_date()}:</strong> {m.state_pension_explanation_start_date()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.state_pension_notes()}:</strong> {m.state_pension_explanation_notes()}</ExplanationListItem>
						</ExplanationList>
						<ExplanationAlert>
							{m.state_pension_explanation_alert()}
						</ExplanationAlert>
					</Explanation>
				{/snippet}
				<Card title={m.state_pension_basic_info()} description={m.state_pension_basic_info_edit_description()}>
					{#snippet headerActions()}
						<PensionStatusActions
							status={pension!.status}
							onPause={handlePause}
							onResume={handleResume}
						/>
					{/snippet}
					<BasicInformationCard bind:name bind:startDate bind:notes {errors} />
				</Card>
			</ContentSection>

			<!-- Statements Section -->
			<ContentSection>
				{#snippet aside()}
					<Explanation>
						<p>{m.state_pension_statements_explanation_intro()}</p>
						<ExplanationList>
							<ExplanationListItem><strong>{m.state_pension_statement_date()}:</strong> {m.state_pension_statements_explanation_date()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.state_pension_current_monthly()}:</strong> {m.state_pension_statements_explanation_current()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.state_pension_projected_monthly()}:</strong> {m.state_pension_statements_explanation_projected()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.state_pension_current_value()}:</strong> {m.state_pension_statements_explanation_value()}</ExplanationListItem>
						</ExplanationList>
						<ExplanationAlert>
							{m.state_pension_statements_explanation_alert()}
						</ExplanationAlert>
					</Explanation>
				{/snippet}
				<Card title={m.state_pension_statements()} description={m.state_pension_statements_description()}>
					<StatementsCard bind:statements {pensionId} />
				</Card>
			</ContentSection>

			<!-- Scenarios Section -->
			<ContentSection>
				{#snippet aside()}
					<Explanation>
						<p>{m.state_pension_scenarios_explanation_intro()}</p>
						<p>{m.state_pension_scenarios_explanation_text()}</p>
						<ExplanationList>
							<ExplanationListItem><strong>{m.state_pension_planned_retirement({ age: '' })}:</strong> {m.state_pension_scenarios_explanation_planned()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.state_pension_alternative_retirement({ age: '' })}:</strong> {m.state_pension_scenarios_explanation_alternative()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.state_pension_pessimistic()}:</strong> {m.state_pension_scenarios_explanation_pessimistic()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.state_pension_realistic()}:</strong> {m.state_pension_scenarios_explanation_realistic()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.state_pension_optimistic()}:</strong> {m.state_pension_scenarios_explanation_optimistic()}</ExplanationListItem>
						</ExplanationList>
						<ExplanationAlert>
							{m.state_pension_scenarios_explanation_alert()}
						</ExplanationAlert>
					</Explanation>
				{/snippet}
				<Card title={m.state_pension_scenarios()} description={m.state_pension_scenarios_description()}>
					<ScenarioViewer {pensionId} />
				</Card>
			</ContentSection>
		</form>
	{/if}
</div>
