// app/pension/savings/new/page.tsx
"use client"

import { useForm } from "react-hook-form"
import { useRouter, useSearchParams } from "next/navigation"
import { Form } from "@/frontend/components/ui/form"
import { Button } from "@/frontend/components/ui/button"
import { SavingsPensionFormData } from "@/frontend/types/pension-form"
import { PensionType, SavingsPension, CompoundingFrequency } from "@/frontend/types/pension"
import { toast } from "sonner"
import { zodResolver } from "@hookform/resolvers/zod"
import { savingsPensionSchema } from "@/frontend/lib/validations/pension"
import { ErrorBoundary } from "@/frontend/components/shared/ErrorBoundary"
import { BasicInformationCard } from "@/frontend/components/pension/savings/BasicInformationCard"
import { InterestRatesCard } from "@/frontend/components/pension/savings/InterestRatesCard"
import { StatementsCard } from "@/frontend/components/pension/savings/StatementsCard"
import { ContributionPlanCard } from "@/frontend/components/pension/savings/ContributionPlanCard"
import { FormLayout, FormSection } from "@/frontend/components/shared"
import { BasicInformationExplanation } from "@/frontend/components/pension/savings/explanations/BasicInformationExplanation"
import { InterestRatesExplanation } from "@/frontend/components/pension/savings/explanations/InterestRatesExplanation"
import { StatementsExplanation } from "@/frontend/components/pension/savings/explanations/StatementsExplanation"
import { ContributionPlanExplanation } from "@/frontend/components/pension/savings/explanations/ContributionPlanExplanation"
import { getPensionListRoute } from "@/frontend/lib/routes"
import { toISODateString } from "@/frontend/lib/dateUtils"
import { useState, useMemo } from "react"
import { useCreateSavingsPension } from "@/frontend/hooks/useSavingsPensions"

export default function NewSavingsPensionPage() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const [isSubmitting, setIsSubmitting] = useState(false)
  const { mutateAsync: createPension } = useCreateSavingsPension()

  // Initialize form with default values
  const defaultValues = useMemo<SavingsPensionFormData>(() => ({
    type: PensionType.SAVINGS,
    name: "",
    member_id: searchParams.get('member_id') || "",
    start_date: new Date(),
    notes: "",

    // Default interest rates (stored as decimals: 0.01 = 1%)
    pessimistic_rate: 0.01,
    realistic_rate: 0.02,
    optimistic_rate: 0.03,

    // Default compounding frequency
    compounding_frequency: CompoundingFrequency.ANNUALLY,

    // Status and related data
    status: "ACTIVE",
    statements: [],
    contribution_plan_steps: []
  }), [searchParams]);

  const form = useForm<SavingsPensionFormData>({
    resolver: zodResolver(savingsPensionSchema),
    defaultValues
  })

  const handleSubmit = async (data: SavingsPensionFormData) => {
    try {
      setIsSubmitting(true)
      const memberId = parseInt(data.member_id)
      if (isNaN(memberId)) {
        toast.error("Error", { description: "Invalid member ID" })
        return
      }

      // Create a pension data object that matches what the API expects
      const pensionData = {
        type: PensionType.SAVINGS as const,
        name: data.name,
        member_id: memberId,
        start_date: toISODateString(data.start_date),
        notes: data.notes || "",
        
        // Interest rates
        pessimistic_rate: data.pessimistic_rate,
        realistic_rate: data.realistic_rate,
        optimistic_rate: data.optimistic_rate,
        
        // Compounding frequency
        compounding_frequency: data.compounding_frequency,
        
        // Status
        status: data.status,
        
        // Statements (convert dates to ISO strings)
        statements: data.statements.length > 0 
          ? data.statements.map(statement => ({
              statement_date: toISODateString(statement.statement_date),
              balance: statement.balance,
              note: statement.note || ""
            })) 
          : undefined,
        
        // Contribution plan steps (convert dates to ISO strings)
        contribution_plan_steps: data.contribution_plan_steps.length > 0
          ? data.contribution_plan_steps.map(step => ({
              amount: step.amount,
              frequency: step.frequency,
              start_date: toISODateString(step.start_date),
              end_date: step.end_date ? toISODateString(step.end_date) : undefined,
              note: step.note || ""
            }))
          : []
      }

      // Create the pension using React Query mutation
      await createPension(pensionData as unknown as Omit<SavingsPension, 'id'>)
      
      toast.success("Success", { description: "Savings pension created" })
      router.push(getPensionListRoute())
    } catch (error) {
      console.error("Error creating savings pension:", error)
      toast.error("Error", { 
        description: error instanceof Error 
          ? error.message 
          : "Failed to create savings pension" 
      })
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <ErrorBoundary>
      <div className="container mx-auto py-10">
        {/* Page header with title and buttons */}
        <div className="flex flex-col space-y-4 sm:flex-row sm:justify-between sm:space-y-0 sm:items-center mb-6">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">New Savings Pension</h1>
            <p className="text-muted-foreground mt-2">
              Create a savings-based pension plan to track your retirement savings account.
            </p>
          </div>
          
          <div className="flex space-x-4">
            <Button
              type="button"
              variant="outline"
              onClick={() => router.back()}
            >
              Cancel
            </Button>
            <Button 
              type="submit"
              form="savings-pension-form"
              disabled={isSubmitting}
            >
              Create Pension
            </Button>
          </div>
        </div>

        <Form {...form}>
          <form 
            id="savings-pension-form"
            onSubmit={form.handleSubmit(handleSubmit)} 
          >
            <FormLayout>
              {/* Basic Information Section */}
              <FormSection
                title="Basic Information"
                description="Enter the basic details of your savings account"
                explanation={<BasicInformationExplanation />}
              >
                <BasicInformationCard form={form} />
              </FormSection>
              
              {/* Interest Rates Section */}
              <FormSection
                title="Interest Rates"
                description="Configure interest rates for different scenarios"
                explanation={<InterestRatesExplanation />}
              >
                <InterestRatesCard form={form} />
              </FormSection>
              
              {/* Statements Section */}
              <FormSection
                title="Account Statements"
                description="Record your savings account balance over time"
                explanation={<StatementsExplanation />}
              >
                <StatementsCard form={form} />
              </FormSection>
              
              {/* Contribution Plan Section */}
              <FormSection
                title="Contribution Plan"
                description="Set up your regular deposits to this savings account"
                explanation={<ContributionPlanExplanation />}
              >
                <ContributionPlanCard form={form} />
              </FormSection>
            </FormLayout>
          </form>
        </Form>
      </div>
    </ErrorBoundary>
  )
}

// src/frontend/src/routes/pension/savings/new/+page.svelte
<!--
@file src/routes/pension/savings/new/+page.svelte
@kind route
@purpose Rendert die Route 'pension/savings/new' und verbindet Seitenzustand, Nutzeraktionen und Unterkomponenten.
@contains Reaktiver Seitenzustand wird ueber `\$state`, `\$derived` und `\$effect` organisiert.
@contains Kernfunktionen `validate()`, `handleSubmit()` steuern Laden, Aktionen und Fehlerpfade.
@contains Das Markup verdrahtet Sektionen, Dialoge und Aktionen fuer den Route-Workflow.
-->

<script lang="ts">
	import { goto } from '$app/navigation';
	import { m } from '$lib/paraglide/messages.js';
	import { pensionApi } from '$lib/api/pension';
	import { toastStore } from '$lib/stores/toast.svelte';
	import { PensionType, CompoundingFrequency } from '$lib/types/pension';
	import type { ContributionStep } from '$lib/types/pension';
	import { todayIsoDate } from '$lib/utils/date-only';
	import Button from '$lib/components/ui/Button.svelte';
	import PageHeader from '$lib/components/ui/PageHeader.svelte';
	import Card from '$lib/components/ui/Card.svelte';
	import ContentSection from '$lib/components/ui/ContentSection.svelte';
	import Explanation from '$lib/components/ui/Explanation.svelte';
	import ExplanationAlert from '$lib/components/ui/ExplanationAlert.svelte';
	import ExplanationList from '$lib/components/ui/ExplanationList.svelte';
	import ExplanationListItem from '$lib/components/ui/ExplanationListItem.svelte';
	import BasicInformationCard from '$lib/components/pension/savings/BasicInformationCard.svelte';
	import ScenarioRatesCard from '$lib/components/pension/ScenarioRatesCard.svelte';
	import StatementsCard from '$lib/components/pension/savings/StatementsCard.svelte';
	import ContributionPlanCard from '$lib/components/pension/ContributionPlanCard.svelte';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	interface StatementFormData {
		id: number;
		pension_id: number;
		statement_date: string;
		balance: number;
		note?: string;
	}

	// Form state
	let name = $state('');
	let startDate = $state(todayIsoDate());
	let notes = $state('');
	let compoundingFrequency = $state(CompoundingFrequency.ANNUALLY);
	// Rates stored as decimals (0.01 = 1%), PercentInput handles display
	let pessimisticRate = $state(0.01);
	let realisticRate = $state(0.02);
	let optimisticRate = $state(0.03);
	let statements = $state<StatementFormData[]>([]);
	let contributionPlanSteps = $state<ContributionStep[]>([]);
	let errors = $state<Record<string, string>>({});
	let submitting = $state(false);

	let memberId = $derived(data.memberId);

	function validate(): boolean {
		const newErrors: Record<string, string> = {};
		if (!name.trim()) newErrors.name = m.savings_pension_name_required();
		if (!startDate) newErrors.start_date = m.savings_pension_start_date_required();
		errors = newErrors;
		return Object.keys(newErrors).length === 0;
	}

	async function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		if (!validate()) return;

		submitting = true;
		try {
			// Savings pension does NOT accept statements in the create body —
			// create the pension first, then POST each statement individually.
			const pensionData = {
				type: PensionType.SAVINGS,
				name: name.trim(),
				member_id: memberId,
				start_date: startDate,
				notes: notes.trim() || '',
				status: 'ACTIVE' as const,
				// Convert decimals to percentages for API
				pessimistic_rate: pessimisticRate * 100,
				realistic_rate: realisticRate * 100,
				optimistic_rate: optimisticRate * 100,
				compounding_frequency: compoundingFrequency,
				contribution_plan_steps: contributionPlanSteps.map(step => ({
					amount: step.amount,
					frequency: step.frequency,
					start_date: step.start_date,
					end_date: step.end_date || undefined,
					note: step.note || ''
				}))
			};

			const created = await pensionApi.create<{ id: number }>(PensionType.SAVINGS, pensionData);

			// Now POST each statement separately
			await Promise.all(
				statements
					.filter(s => s.statement_date)
					.map(s => pensionApi.addSavingsPensionStatement(created.id, {
						statement_date: s.statement_date,
						balance: s.balance || 0,
						note: s.note || ''
					}))
			);

			toastStore.success(m.savings_pension_created());
			goto('/pension');
		} catch (error) {
			console.error('Error creating savings pension:', error);
			toastStore.error(error instanceof Error ? error.message : m.savings_pension_create_failed());
		} finally {
			submitting = false;
		}
	}
</script>

<div class="space-y-6">
	<!-- Header -->
	<div class="flex flex-col space-y-4 sm:flex-row sm:justify-between sm:space-y-0 sm:items-center">
		<PageHeader
			title={m.savings_pension_new_title()}
			description={m.savings_pension_new_description()}
		/>
		<div class="flex space-x-4 shrink-0">
			<Button variant="secondary" onclick={() => history.back()}>
				{m.cancel()}
			</Button>
			<Button type="submit" form="savings-pension-form" disabled={submitting}>
				{m.savings_pension_create()}
			</Button>
		</div>
	</div>

	<form id="savings-pension-form" onsubmit={handleSubmit} class="space-y-8">
		<!-- Basic Information Section -->
		<ContentSection>
			{#snippet aside()}
				<Explanation>
					<p>{m.savings_pension_explanation_intro()}</p>
					<ExplanationList>
						<ExplanationListItem><strong>{m.savings_pension_start_date()}:</strong> {m.savings_pension_explanation_start_date()}</ExplanationListItem>
						<ExplanationListItem><strong>{m.savings_pension_compounding_frequency()}:</strong> {m.savings_pension_explanation_compounding()}</ExplanationListItem>
					</ExplanationList>
					<ExplanationAlert>
						{m.savings_pension_explanation_alert()}
					</ExplanationAlert>
				</Explanation>
			{/snippet}
			<Card title={m.savings_pension_basic_info()} description={m.savings_pension_basic_info_description()}>
				<BasicInformationCard bind:name bind:startDate bind:compoundingFrequency bind:notes {errors} />
			</Card>
		</ContentSection>

		<!-- Interest Rates Section -->
		<ContentSection>
			{#snippet aside()}
				<Explanation>
					<p>{m.savings_pension_interest_rates_explanation_intro()}</p>
					<ExplanationList>
						<ExplanationListItem><strong>{m.pension_scenario_pessimistic_rate()}:</strong> {m.savings_pension_interest_rates_explanation_pessimistic()}</ExplanationListItem>
						<ExplanationListItem><strong>{m.pension_scenario_realistic_rate()}:</strong> {m.savings_pension_interest_rates_explanation_realistic()}</ExplanationListItem>
						<ExplanationListItem><strong>{m.pension_scenario_optimistic_rate()}:</strong> {m.savings_pension_interest_rates_explanation_optimistic()}</ExplanationListItem>
					</ExplanationList>
					<ExplanationAlert>
						{m.savings_pension_interest_rates_explanation_alert()}
					</ExplanationAlert>
				</Explanation>
			{/snippet}
			<Card title={m.savings_pension_interest_rates()} description={m.savings_pension_interest_rates_description()}>
				<ScenarioRatesCard bind:pessimisticRate bind:realisticRate bind:optimisticRate />
			</Card>
		</ContentSection>

		<!-- Statements Section -->
		<ContentSection>
			{#snippet aside()}
				<Explanation>
					<p>{m.savings_pension_statements_explanation_intro()}</p>
					<ExplanationList>
						<ExplanationListItem><strong>{m.savings_pension_statement_date()}:</strong> {m.savings_pension_statements_explanation_date()}</ExplanationListItem>
						<ExplanationListItem><strong>{m.savings_pension_balance()}:</strong> {m.savings_pension_statements_explanation_balance()}</ExplanationListItem>
						<ExplanationListItem><strong>{m.savings_pension_statement_note()}:</strong> {m.savings_pension_statements_explanation_note()}</ExplanationListItem>
					</ExplanationList>
					<ExplanationAlert>
						{m.savings_pension_statements_explanation_alert()}
					</ExplanationAlert>
				</Explanation>
			{/snippet}
			<Card title={m.savings_pension_statements()} description={m.savings_pension_statements_description()}>
				<StatementsCard bind:statements />
			</Card>
		</ContentSection>

		<!-- Contribution Plan Section -->
		<ContentSection>
			{#snippet aside()}
				<Explanation>
					<p>{m.savings_pension_contribution_plan_explanation_intro()}</p>
					<ExplanationList>
						<ExplanationListItem><strong>{m.contribution_amount()}:</strong> {m.savings_pension_contribution_plan_explanation_amount()}</ExplanationListItem>
						<ExplanationListItem><strong>{m.contribution_frequency()}:</strong> {m.savings_pension_contribution_plan_explanation_frequency()}</ExplanationListItem>
						<ExplanationListItem><strong>{m.contribution_start_date()} / {m.contribution_end_date()}:</strong> {m.savings_pension_contribution_plan_explanation_dates()}</ExplanationListItem>
					</ExplanationList>
					<ExplanationAlert>
						{m.savings_pension_contribution_plan_explanation_alert()}
					</ExplanationAlert>
				</Explanation>
			{/snippet}
			<ContributionPlanCard bind:steps={contributionPlanSteps} />
		</ContentSection>
	</form>
</div>
