// src/svelte-frontend/src/routes/pension/etf/[id]/edit/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { m } from '$lib/paraglide/messages.js';
	import { pensionApi } from '$lib/api/pension';
	import { pensionStore } from '$lib/stores/pension.svelte';
	import { toastStore } from '$lib/stores/toast.svelte';
	import { settingsStore } from '$lib/stores/settings.svelte';
	import { PensionType } from '$lib/types/pension';
	import type { ETFPension, ContributionStep, ETFPensionStatistics } from '$lib/types/pension';
	import { calculateCombinedScenarios } from '$lib/utils/projection';
	import { formatCurrency, formatPercent, formatDate } from '$lib/utils/format';
	import PageHeader from '$lib/components/ui/PageHeader.svelte';
	import Card from '$lib/components/ui/Card.svelte';
	import ContentSection from '$lib/components/ui/ContentSection.svelte';
	import Explanation from '$lib/components/ui/Explanation.svelte';
	import ExplanationList from '$lib/components/ui/ExplanationList.svelte';
	import ExplanationListItem from '$lib/components/ui/ExplanationListItem.svelte';
	import ExplanationStats from '$lib/components/ui/ExplanationStats.svelte';
	import ExplanationStat from '$lib/components/ui/ExplanationStat.svelte';
	import BasicInformationCard from '$lib/components/pension/etf/BasicInformationCard.svelte';
	import HistoricalPerformanceChart from '$lib/components/pension/etf/HistoricalPerformanceChart.svelte';
	import ProjectionChart from '$lib/components/pension/etf/ProjectionChart.svelte';
	import ContributionPlanCard from '$lib/components/pension/ContributionPlanCard.svelte';
	import PensionStatusActions from '$lib/components/pension/PensionStatusActions.svelte';
	import OneTimeInvestmentModal from '$lib/components/pension/etf/OneTimeInvestmentModal.svelte';
	import type { PageData } from './$types';
	import {
		Wallet,
		TrendingUp,
		TrendingDown,
		ArrowRight,
		Calendar,
		CircleDot,
		CalendarClock
	} from '@lucide/svelte';

	let { data }: { data: PageData } = $props();

	let pensionId = $derived(data.pensionId);

	// Loading/error state
	let loadError = $state('');
	let submitting = $state(false);

	// Pension data
	let pension = $state<ETFPension | null>(null);

	// Form state
	let name = $state('');
	let etfId = $state('');
	let etfDisplayName = $state('');
	let existingUnits = $state(0);
	let referenceDate = $state('');
	let notes = $state('');
	let contributionPlanSteps = $state<ContributionStep[]>([]);
	let errors = $state<Record<string, string>>({});

	// Statistics (loaded non-blocking after page load)
	let statistics = $state<ETFPensionStatistics | null>(null);
	let statisticsLoading = $state(false);

	// One-time investment modal
	let showOneTimeModal = $state(false);

	// Retirement date from loaded member
	const retirementDateStr = $derived(data.member?.retirement_date_planned ?? null);

	// Settings for formatting
	const locale = $derived(settingsStore.current.number_locale);
	const currency = $derived(settingsStore.current.currency);

	function hydrateForm(p: ETFPension) {
		name = p.name;
		etfId = p.etf_id;
		etfDisplayName = p.etf ? `${p.etf.symbol} - ${p.etf.name}` : p.etf_id;
		existingUnits = p.existing_units ?? 0;
		referenceDate = p.reference_date ?? '';
		notes = p.notes ?? '';
		contributionPlanSteps = (p.contribution_plan_steps ?? []).map((step) => ({ ...step }));
	}

	$effect(() => {
		loadError = data.initialError;
		pension = data.initialPension;
		if (data.initialPension) {
			hydrateForm(data.initialPension);
		}
	});

	// Load statistics non-blocking
	$effect(() => {
		if (pensionId) {
			statisticsLoading = true;
			pensionApi
				.getETFPensionStatistics(pensionId)
				.then((s) => {
					statistics = s;
				})
				.catch((err) => {
					console.error('Failed to load ETF statistics:', err);
				})
				.finally(() => {
					statisticsLoading = false;
				});
		}
	});

	// Projection calculation for sidebar stats
	const projectionData = $derived.by(() => {
		if (!statistics || !retirementDateStr || contributionPlanSteps.length === 0) return null;

		const { value_history, contribution_history } = statistics;
		if (!value_history || value_history.length === 0) return null;

		const sortedHistory = [...value_history].sort(
			(a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
		);
		const lastPoint = sortedHistory[sortedHistory.length - 1];
		const initialValue = Number(lastPoint.value);

		const projectionStart = new Date(lastPoint.date);
		projectionStart.setMonth(projectionStart.getMonth() + 1);

		const retirementDate = new Date(retirementDateStr);
		if (retirementDate <= new Date()) return null;

		try {
			return calculateCombinedScenarios({
				initialValue,
				contributionSteps: contributionPlanSteps,
				rates: {
					pessimistic: settingsStore.current.projection_pessimistic_rate,
					realistic: settingsStore.current.projection_realistic_rate,
					optimistic: settingsStore.current.projection_optimistic_rate
				},
				startDate: projectionStart,
				endDate: retirementDate,
				historicalContributions: contribution_history
			});
		} catch {
			return null;
		}
	});

	function validate(): boolean {
		const newErrors: Record<string, string> = {};
		if (!name.trim()) newErrors.name = 'Name is required';
		errors = newErrors;
		return Object.keys(newErrors).length === 0;
	}

	async function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		if (!validate() || !pension) return;

		submitting = true;
		try {
			const pensionData = {
				name: name.trim(),
				etf_id: etfId,
				is_existing_investment: pension.is_existing_investment,
				existing_units: existingUnits,
				reference_date: referenceDate || undefined,
				notes: notes.trim() || '',
				contribution_plan_steps: contributionPlanSteps.map((step) => ({
					id: step.id,
					amount: step.amount,
					frequency: step.frequency,
					start_date: step.start_date,
					end_date: step.end_date || undefined,
					note: step.note || ''
				}))
			};

			await pensionApi.update(PensionType.ETF_PLAN, pensionId, pensionData);
			toastStore.success(m.etf_pension_updated());
			goto('/pension');
		} catch (error) {
			console.error('Error updating ETF pension:', error);
			toastStore.error(error instanceof Error ? error.message : m.etf_pension_update_failed());
		} finally {
			submitting = false;
		}
	}

	async function handlePause(pauseDate: string) {
		try {
			await pensionStore.updateStatus(PensionType.ETF_PLAN, pensionId, {
				status: 'PAUSED',
				paused_at: pauseDate
			});
			pension = await pensionApi.get<ETFPension>(PensionType.ETF_PLAN, pensionId);
		} catch (error) {
			console.error('Error pausing pension:', error);
			toastStore.error(error instanceof Error ? error.message : m.etf_pension_update_failed());
		}
	}

	async function handleResume(resumeDate: string) {
		try {
			await pensionStore.updateStatus(PensionType.ETF_PLAN, pensionId, {
				status: 'ACTIVE',
				resume_at: resumeDate
			});
			pension = await pensionApi.get<ETFPension>(PensionType.ETF_PLAN, pensionId);
		} catch (error) {
			console.error('Error resuming pension:', error);
			toastStore.error(error instanceof Error ? error.message : m.etf_pension_update_failed());
		}
	}
</script>

<div class="space-y-6">
	<!-- Header -->
	<div class="flex flex-col space-y-4 sm:flex-row sm:justify-between sm:space-y-0 sm:items-center">
		<PageHeader title={m.etf_pension_edit_title()} description={m.etf_pension_edit_description()} />
		<div class="flex space-x-4 shrink-0">
			<button
				type="button"
				onclick={() => history.back()}
				class="px-4 py-2 bg-secondary hover:bg-secondary/80 text-secondary-foreground rounded-lg text-sm font-medium transition-colors"
			>
				{m.cancel()}
			</button>
			<button
				type="submit"
				form="etf-pension-form"
				disabled={submitting}
				class="px-4 py-2 bg-primary hover:bg-primary/90 text-primary-foreground rounded-lg text-sm font-medium transition-colors disabled:opacity-50"
			>
				{m.etf_pension_save()}
			</button>
		</div>
	</div>

	{#if loadError}
		<div class="bg-destructive/10 border border-destructive/30 rounded-xl p-4 text-destructive">
			<p>{loadError}</p>
		</div>
	{:else if !pension}
		<div class="bg-destructive/10 border border-destructive/30 rounded-xl p-4 text-destructive">
			<p>{m.etf_pension_not_found()}</p>
		</div>
	{:else}
		<form id="etf-pension-form" onsubmit={handleSubmit} class="space-y-8">
			<!-- Section 1: Basic Information -->
			<ContentSection>
				{#snippet aside()}
					<Explanation>
						<p>{m.etf_basic_info_explanation_intro()}</p>
						<ExplanationList>
							<ExplanationListItem
								><strong>{m.etf_pension_name()}:</strong>
								{m.etf_basic_info_explanation_name()}</ExplanationListItem
							>
							<ExplanationListItem
								><strong>{m.etf_pension_etf()}:</strong>
								{m.etf_basic_info_explanation_etf()}</ExplanationListItem
							>
							<ExplanationListItem
								><strong>{m.etf_pension_notes()}:</strong>
								{m.etf_basic_info_explanation_notes()}</ExplanationListItem
							>
						</ExplanationList>
					</Explanation>
				{/snippet}
				<Card title={m.etf_pension_edit_title()}>
					{#snippet headerActions()}
						<PensionStatusActions
							status={pension!.status}
							onPause={handlePause}
							onResume={handleResume}
						/>
					{/snippet}
					<BasicInformationCard
						bind:name
						bind:etfId
						bind:etfDisplayName
						bind:existingUnits
						bind:referenceDate
						bind:notes
						isExistingInvestment={pension.is_existing_investment}
						isEditing={true}
						{errors}
					/>
				</Card>
			</ContentSection>

			<!-- Section 2: Contribution Plan -->
			<ContentSection>
				{#snippet aside()}
					<Explanation>
						<p>{m.etf_contribution_explanation_intro()}</p>
						<p class="text-sm text-muted-foreground">{m.etf_contribution_explanation_growth()}</p>
					</Explanation>
				{/snippet}
				<div class="space-y-3">
					<ContributionPlanCard bind:steps={contributionPlanSteps} />
					<div class="flex justify-end">
						<button
							type="button"
							onclick={() => (showOneTimeModal = true)}
							class="px-4 py-2 bg-secondary hover:bg-secondary/80 text-secondary-foreground rounded-lg text-sm font-medium transition-colors"
						>
							{m.etf_add_one_time_investment()}
						</button>
					</div>
				</div>
			</ContentSection>

			<!-- Section 3: Historical Performance -->
			<ContentSection>
				{#snippet aside()}
					{#if statisticsLoading}
						<div class="space-y-2">
							<div class="h-16 animate-pulse bg-muted rounded-lg"></div>
							<div class="h-16 animate-pulse bg-muted rounded-lg"></div>
						</div>
					{:else if statistics}
						<Explanation>
							<p class="text-sm text-muted-foreground">{m.etf_historical_explanation_intro()}</p>
							<ExplanationStats columns={2}>
								<ExplanationStat
									icon={Wallet}
									label={m.etf_total_invested()}
									value={formatCurrency(statistics.total_invested_amount, locale, currency, 0)}
								/>
								<ExplanationStat
									icon={TrendingUp}
									label={m.etf_current_value()}
									value={formatCurrency(statistics.current_value, locale, currency, 0)}
								/>
								<ExplanationStat
									icon={CircleDot}
									label={m.etf_contributions()}
									value={statistics.contribution_history.length}
									subValue={statistics.contribution_history.length > 0
										? formatDate(
												statistics.contribution_history[
													statistics.contribution_history.length - 1
												].contribution_date,
												locale,
												{ month: 'short', year: 'numeric' }
											)
										: undefined}
								/>
								<ExplanationStat
									icon={CalendarClock}
									label={m.etf_total_return()}
									value={formatCurrency(statistics.total_return, locale, currency, 0)}
									subValue={statistics.annual_return != null
										? formatPercent(statistics.annual_return / 100, locale, 1)
										: undefined}
									subLabel={statistics.annual_return != null ? m.etf_annual_return() : undefined}
								/>
							</ExplanationStats>
						</Explanation>
					{:else}
						<Explanation>
							<p class="text-sm text-muted-foreground">{m.etf_historical_explanation_intro()}</p>
						</Explanation>
					{/if}
				{/snippet}
				<Card title={m.etf_historical_title()}>
					<HistoricalPerformanceChart
						contributionHistory={statistics?.contribution_history ?? []}
						valueHistory={statistics?.value_history ?? []}
						loading={statisticsLoading}
					/>
				</Card>
			</ContentSection>

			<!-- Section 4: Value Projection -->
			<ContentSection>
				{#snippet aside()}
					{#if statisticsLoading}
						<div class="space-y-2">
							<div class="h-16 animate-pulse bg-muted rounded-lg"></div>
							<div class="h-16 animate-pulse bg-muted rounded-lg"></div>
							<div class="h-16 animate-pulse bg-muted rounded-lg"></div>
						</div>
					{:else if projectionData}
						<Explanation>
							<p class="text-sm text-muted-foreground">{m.etf_projection_explanation_intro()}</p>
							<ExplanationStats columns={1}>
								<ExplanationStat
									icon={TrendingDown}
									label={m.etf_pessimistic_value()}
									value={formatCurrency(
										projectionData.scenarios.pessimistic.finalValue,
										locale,
										currency,
										0
									)}
									subValue="{settingsStore.current.projection_pessimistic_rate}% p.a."
								/>
								<ExplanationStat
									icon={ArrowRight}
									label={m.etf_realistic_value()}
									value={formatCurrency(
										projectionData.scenarios.realistic.finalValue,
										locale,
										currency,
										0
									)}
									subValue="{settingsStore.current.projection_realistic_rate}% p.a."
								/>
								<ExplanationStat
									icon={TrendingUp}
									label={m.etf_optimistic_value()}
									value={formatCurrency(
										projectionData.scenarios.optimistic.finalValue,
										locale,
										currency,
										0
									)}
									subValue="{settingsStore.current.projection_optimistic_rate}% p.a."
								/>
							</ExplanationStats>
							<ExplanationStats columns={2}>
								<ExplanationStat
									icon={Wallet}
									label={m.etf_total_contributions_label()}
									value={formatCurrency(
										projectionData.scenarios.realistic.totalContributions,
										locale,
										currency,
										0
									)}
								/>
								{#if retirementDateStr}
									<ExplanationStat
										icon={Calendar}
										label={m.etf_retirement_date_label()}
										value={formatDate(retirementDateStr, locale, {
											month: 'short',
											year: 'numeric'
										})}
									/>
								{/if}
							</ExplanationStats>
						</Explanation>
					{:else}
						<Explanation>
							<p class="text-sm text-muted-foreground">{m.etf_projection_explanation_intro()}</p>
							<p class="text-sm text-muted-foreground">{m.etf_projection_explanation_scenarios()}</p>
						</Explanation>
					{/if}
				{/snippet}
				<Card title={m.etf_projection_title()}>
					<ProjectionChart
						{statistics}
						contributionSteps={contributionPlanSteps}
						retirementDate={retirementDateStr}
						loading={statisticsLoading}
					/>
				</Card>
			</ContentSection>
		</form>
	{/if}
</div>

<!-- One-Time Investment Modal -->
<OneTimeInvestmentModal
	open={showOneTimeModal}
	{pensionId}
	pensionName={pension?.name ?? ''}
	onClose={() => (showOneTimeModal = false)}
	onSuccess={() => {
		// Reload statistics after adding one-time investment
		if (pensionId) {
			statisticsLoading = true;
			pensionApi
				.getETFPensionStatistics(pensionId)
				.then((s) => {
					statistics = s;
				})
				.finally(() => {
					statisticsLoading = false;
				});
		}
	}}
/>

// app/pension/etf/[id]/edit/page.tsx
"use client"

import { useForm, useWatch } from "react-hook-form"
import { useRouter } from "next/navigation"
import { Form } from "@/frontend/components/ui/form"
import { Button } from "@/frontend/components/ui/button"
import { ETFPensionFormData } from "@/frontend/types/pension-form"
import { PensionType, type ETFPension } from "@/frontend/types/pension"
import { usePension } from "@/frontend/context/pension"
import { useHousehold } from "@/frontend/context/HouseholdContext"
import { toast } from "sonner"
import { use } from "react"
import { useEffect, useState } from "react"
import { getPensionListRoute } from "@/frontend/lib/routes"
import { Skeleton } from "@/frontend/components/ui/skeleton"
import {
  CombinedProjectionChart,
  HistoricalPerformanceChart
} from "@/frontend/components/charts"
import { useProjectionScenarios } from "@/frontend/hooks/useProjectionScenarios"
import { ErrorBoundary } from "@/frontend/components/shared/ErrorBoundary"
import { LoadingState } from "@/frontend/components/shared/LoadingState"
import { Alert, AlertTitle, AlertDescription } from "@/frontend/components/ui/alert"
import { FormLayout, FormSection } from "@/frontend/components/shared"
import { BasicInformationCard } from "@/frontend/components/pension/etf/BasicInformationCard"
import { ContributionPlanCard } from "@/frontend/components/pension/etf/ContributionPlanCard"
import { PensionStatusActions } from "@/frontend/components/pension/shared/PensionStatusActions"
import { PauseConfirmationDialog } from "@/frontend/components/pension/shared/dialogs/PauseConfirmationDialog"
import { ResumeDateDialog } from "@/frontend/components/pension/shared/dialogs/ResumeDateDialog"
import { ValueProjectionExplanation } from "@/frontend/components/pension/etf/explanations/ValueProjectionExplanation"
import { HistoricalPerformanceExplanation } from "@/frontend/components/pension/etf/explanations/HistoricalPerformanceExplanation"
import { ContributionPlanExplanation } from "@/frontend/components/pension/etf/explanations/ContributionPlanExplanation"
import { TrendingUp } from "lucide-react"
import { toISODateString } from "@/frontend/lib/dateUtils"
import { usePensionData } from "@/frontend/lib/hooks/usePensionData"

interface EditETFPensionPageProps {
  params: Promise<{
    id: string
  }>
}

// Form transformation utilities
const transformPensionToFormData = (pension: ETFPension): ETFPensionFormData => ({
  type: PensionType.ETF_PLAN,
  name: pension.name,
  member_id: pension.member_id.toString(),
  notes: pension.notes || "",
  etf_id: pension.etf_id,
  is_existing_investment: pension.is_existing_investment,
  existing_units: pension.existing_units || 0,
  reference_date: pension.reference_date || new Date(),
  realize_historical_contributions: pension.realize_historical_contributions || false,
  initialization_method: pension.realize_historical_contributions ? "historical" : "none",
  contribution_plan_steps: pension.contribution_plan_steps.map(step => ({
    amount: step.amount,
    frequency: step.frequency,
    start_date: new Date(step.start_date),
    end_date: step.end_date ? new Date(step.end_date) : undefined,
    note: step.note
  }))
})

const transformFormDataToPension = (data: ETFPensionFormData, currentPension: ETFPension): Omit<ETFPension, "id" | "current_value"> => ({
  type: PensionType.ETF_PLAN,
  name: data.name,
  member_id: parseInt(data.member_id),
  notes: data.notes,
  etf_id: data.etf_id,
  is_existing_investment: data.is_existing_investment,
  existing_units: data.existing_units,
  reference_date: data.reference_date,
  contribution_plan_steps: data.contribution_plan_steps.map(step => ({
    amount: step.amount,
    frequency: step.frequency,
    start_date: step.start_date,
    end_date: step.end_date || undefined,
    note: step.note || undefined
  })),
  realize_historical_contributions: data.initialization_method === "historical",
  total_units: currentPension.total_units,
  status: currentPension.status,
  paused_at: currentPension.paused_at,
  resume_at: currentPension.resume_at
})

export default function EditETFPensionPage({ params }: EditETFPensionPageProps) {
  const router = useRouter()
  const { 
    updateEtfPension, 
    pensionStatistics,
    isLoadingStatistics,
    fetchPensionStatistics,
    updatePensionStatus
  } = usePension()
  const { members, fetchMembers } = useHousehold()
  const resolvedParams = use(params)
  const pensionId = parseInt(resolvedParams.id)
  const { data: pension, isLoading, error } = usePensionData<ETFPension>(pensionId, PensionType.ETF_PLAN)
  const statistics = pensionStatistics[pensionId]
  const [showPauseDialog, setShowPauseDialog] = useState(false)
  const [showResumeDialog, setShowResumeDialog] = useState(false)

  // Get the member's retirement date
  const member = pension ? members.find(m => m.id === pension.member_id) : null
  const retirementDate = member ? new Date(member.retirement_date_planned) : undefined

  const form = useForm<ETFPensionFormData>({
    defaultValues: {
      type: PensionType.ETF_PLAN,
      name: "",
      member_id: "",
      notes: "",
      etf_id: "",
      is_existing_investment: false,
      existing_units: 0,
      reference_date: new Date(),
      realize_historical_contributions: false,
      initialization_method: "none",
      contribution_plan_steps: []
    }
  })

  // Use useWatch to get stable value for contribution_plan_steps
  const contributionPlanSteps = useWatch({
    control: form.control,
    name: "contribution_plan_steps",
    defaultValue: []
  })

  // Use the projection scenarios hook with stable contributionPlanSteps
  const { scenarios } = useProjectionScenarios({
    historicalData: statistics?.value_history?.map(point => ({
      date: new Date(point.date),
      value: parseFloat(point.value.toString()),
      isProjection: false
    })) || [],
    contributionSteps: contributionPlanSteps,
    retirementDate: retirementDate || new Date(),
    historicalContributions: statistics?.contribution_history || []
  })

  // Unified loading state
  const loadingState = {
    isPageLoading: isLoading,
    isStatisticsLoading: isLoadingStatistics[pensionId] || false,
    isAnyLoading: isLoading || isLoadingStatistics[pensionId] || false
  }

  // Unified error handler
  const handleError = (error: unknown, action: string) => {
    console.error(`Failed to ${action}:`, error)
    toast.error("Error", { 
      description: `Failed to ${action}. Please try again.`
    })
  }

  // Fetch members on mount
  useEffect(() => {
    fetchMembers()
  }, [fetchMembers])

  // Separate effect for fetching statistics after pension is loaded
  useEffect(() => {
    if (!pension || pension.type !== PensionType.ETF_PLAN) return;
    
    const loadStatistics = async () => {
      try {
        await fetchPensionStatistics(pensionId, PensionType.ETF_PLAN);
      } catch (statsError) {
        console.warn("Failed to fetch pension statistics:", statsError);
        // Don't fail the entire page load if statistics can't be fetched
      }
    };
    
    loadStatistics();
  }, [pension, pensionId, fetchPensionStatistics]);

  // Update form when pension data changes
  useEffect(() => {
    if (pension && pension.type === PensionType.ETF_PLAN) {
      form.reset(transformPensionToFormData(pension))
    }
  }, [pension, form])

  const handleSubmit = async (data: ETFPensionFormData) => {
    try {
      const memberId = parseInt(data.member_id)
      if (isNaN(memberId)) {
        toast.error("Error", { description: "Invalid member ID" })
        return
      }

      if (!pension || pension.type !== PensionType.ETF_PLAN) {
        toast.error("Error", { description: "ETF Pension not found" })
        return
      }

      const payload = transformFormDataToPension(data, pension)
      await updateEtfPension(pensionId, payload)

      toast.success("Success", { description: "ETF pension updated successfully" })
      router.push(getPensionListRoute())
      router.refresh()
    } catch (error) {
      handleError(error, "update pension")
    }
  }

  const handlePauseConfirm = async (pauseDate: Date) => {
    if (!pension) return

    try {
      await updatePensionStatus(pensionId, {
        status: 'PAUSED',
        paused_at: toISODateString(pauseDate)
      })
      setShowPauseDialog(false)
    } catch (error) {
      console.error('Error updating pension status:', error)
      toast.error('Error', {
        description: 'Failed to update pension status'
      })
    }
  }

  const handleResumeConfirm = async (resumeDate: Date) => {
    if (!pension) return

    try {
      await updatePensionStatus(pensionId, {
        status: 'ACTIVE',
        resume_at: toISODateString(resumeDate)
      })
      setShowResumeDialog(false)
    } catch (error) {
      console.error('Error updating pension status:', error)
      toast.error('Error', {
        description: 'Failed to update pension status'
      })
    }
  }

  return (
    <ErrorBoundary>
      <div className="container mx-auto py-10">
        {/* Page Header */}
        <div className="flex flex-col space-y-4 sm:flex-row sm:justify-between sm:items-center mb-6">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Edit ETF Pension Plan</h1>
            <p className="text-muted-foreground mt-2">
              Update your ETF-based pension plan details and contribution schedule.
            </p>
          </div>
          <div className="flex space-x-4">
            <Button
              type="button"
              variant="outline"
              onClick={() => router.back()}
            >
              Cancel
            </Button>
            <Button type="submit" form="etf-pension-form" disabled={loadingState.isAnyLoading}>
              Save Changes
            </Button>
          </div>
        </div>

        {loadingState.isPageLoading ? (
          <LoadingState message="Loading pension details..." />
        ) : error ? (
          <Alert variant="destructive">
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>{error.message}</AlertDescription>
          </Alert>
        ) : !pension ? (
          <Alert variant="destructive">
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>Pension not found</AlertDescription>
          </Alert>
        ) : pension.type !== PensionType.ETF_PLAN ? (
          <Alert variant="destructive">
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>Invalid pension type</AlertDescription>
          </Alert>
        ) : (
          <Form {...form}>
            <form id="etf-pension-form" onSubmit={form.handleSubmit(handleSubmit)}>
              <FormLayout>
                {/* Basic Information Section */}
                <FormSection
                  title="Basic Information"
                  description="Enter the basic details of your ETF pension plan"
                  headerActions={
                    <PensionStatusActions
                      status={pension.status}
                      onPause={() => setShowPauseDialog(true)}
                      onResume={() => setShowResumeDialog(true)}
                    />
                  }
                >
                  <BasicInformationCard form={form} isEditing={true} />
                </FormSection>

                {/* Contribution Plan Section */}
                <FormSection
                  title="Contribution Plan"
                  description="Set up your contribution schedule"
                  explanation={<ContributionPlanExplanation form={form} retirementDate={retirementDate} />}
                  explanationTitle={
                    <div className="flex items-center gap-2">
                      <TrendingUp className="h-4 w-4 text-muted-foreground shrink-0" /> 
                      <span>Growth Opportunity</span>
                    </div>
                  }
                >
                  <ContributionPlanCard form={form} memberId={form.watch('member_id')} />
                </FormSection>

                {/* Historical Performance Section */}
                <FormSection
                  title="Historical Performance"
                  description="Track the performance of your pension plan"
                  explanation={<HistoricalPerformanceExplanation pensionId={pensionId} />}
                  explanationTitle="Historical Statistics"
                >
                  {loadingState.isStatisticsLoading ? (
                    <Skeleton className="h-[400px] w-full" />
                  ) : statistics?.value_history ? (
                    <HistoricalPerformanceChart
                      contributionData={statistics.contribution_history}
                      valueData={statistics.value_history.map(point => ({
                        date: new Date(point.date),
                        value: parseFloat(point.value.toString())
                      }))}
                      asCard={false}
                    />
                  ) : (
                    <div className="p-8 text-center text-muted-foreground">
                      No historical data available
                    </div>
                  )}
                </FormSection>

                {/* Value Projection Section */}
                <FormSection
                  title="Value Projection"
                  description="Projected future value of your pension plan"
                  explanation={
                    !loadingState.isStatisticsLoading && (
                      <ValueProjectionExplanation
                        scenarios={scenarios?.scenarios || {
                          pessimistic: { type: 'pessimistic', dataPoints: [], finalValue: 0, totalContributions: 0, totalReturns: 0, returnRate: 2 },
                          realistic: { type: 'realistic', dataPoints: [], finalValue: 0, totalContributions: 0, totalReturns: 0, returnRate: 5 },
                          optimistic: { type: 'optimistic', dataPoints: [], finalValue: 0, totalContributions: 0, totalReturns: 0, returnRate: 8 }
                        }}
                      />
                    )
                  }
                  explanationTitle="Scenario Analysis"
                >
                  {loadingState.isStatisticsLoading ? (
                    <Skeleton className="h-[400px] w-full" />
                  ) : statistics?.value_history ? (
                    <CombinedProjectionChart
                      data={statistics.value_history.map(point => ({
                        date: new Date(point.date),
                        value: parseFloat(point.value.toString()),
                        isProjection: false
                      }))}
                      contributionData={statistics.contribution_history}
                      contributionSteps={contributionPlanSteps}
                      timeRange={{
                        start: new Date(statistics.value_history[0].date),
                        end: retirementDate || new Date()
                      }}
                      height={600}
                      expandable={false}
                      asCard={false}
                    />
                  ) : (
                    <div className="p-8 text-center text-muted-foreground">
                      No projection data available
                    </div>
                  )}
                </FormSection>
              </FormLayout>
            </form>
          </Form>
        )}

        {/* Dialogs */}
        {showPauseDialog && (
          <PauseConfirmationDialog
            open={showPauseDialog}
            onOpenChange={setShowPauseDialog}
            onConfirm={handlePauseConfirm}
          />
        )}
        {showResumeDialog && (
          <ResumeDateDialog
            open={showResumeDialog}
            onOpenChange={setShowResumeDialog}
            onConfirm={handleResumeConfirm}
          />
        )}
      </div>
    </ErrorBoundary>
  )
}
