// app/household/page.tsx
"use client"

import { MemberList } from "@/frontend/components/household/MemberList"
import { AddMemberDialog } from "@/frontend/components/household/AddMemberDialog"
import { EditMemberDialog } from "@/frontend/components/household/EditMemberDialog"
import { HouseholdMember, HouseholdMemberFormData } from "@/frontend/types/household"
import { 
  useHouseholdMembers, 
  useCreateHouseholdMember, 
  useUpdateHouseholdMember, 
  useDeleteHouseholdMember 
} from "@/frontend/hooks/useHouseholdMembers"
import { toast } from "sonner"
import { useState } from "react"
/**
 * Main Household page component
 * 
 * Responsibilities:
 * - Manages household members state
 * - Coordinates between child components
 * - Handles member operations (add/edit/delete)
 * - Layout for member list and add member button
 * 
 * Components used:
 * - AddMemberDialog
 * - EditMemberDialog
 * - MemberList
 */

export default function HouseholdPage() {
  // Replace context with React Query hooks
  const { data: members = [], isLoading } = useHouseholdMembers()
  const createMutation = useCreateHouseholdMember()
  const updateMutation = useUpdateHouseholdMember()
  const deleteMutation = useDeleteHouseholdMember()
  
  const [editingMember, setEditingMember] = useState<HouseholdMember | null>(null)
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false)

  const handleAddMember = async (newMember: HouseholdMemberFormData) => {
    try {
      await createMutation.mutateAsync(newMember)
      setIsAddDialogOpen(false)
      toast.success('Household member added successfully')
    } catch (error) {
      console.error('Failed to add member:', error)
      toast.error('Failed to add household member')
    }
  }

  const handleDeleteMember = async (id: number) => {
    try {
      await deleteMutation.mutateAsync(id)
      toast.success('Household member deleted successfully')
    } catch (error) {
      console.error('Failed to delete member:', error)
      toast.error('Failed to delete household member')
    }
  }

  const handleUpdateMember = async (updatedMember: HouseholdMemberFormData) => {
    if (!editingMember) return
    
    try {
      await updateMutation.mutateAsync({ 
        id: editingMember.id, 
        data: updatedMember 
      })
      setEditingMember(null)
      toast.success('Household member updated successfully')
    } catch (error) {
      console.error('Failed to update member:', error)
      toast.error('Failed to update household member')
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center mb-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Household</h1>
          <p className="text-muted-foreground mt-2">
            Manage your household members and their retirement planning preferences
          </p>
        </div>
        <AddMemberDialog 
          onAdd={handleAddMember}
          open={isAddDialogOpen}
          onOpenChange={setIsAddDialogOpen}
        />
      </div>
      <MemberList 
        members={members} 
        onDelete={handleDeleteMember}
        onEdit={setEditingMember}
        onAdd={() => setIsAddDialogOpen(true)}
        isLoading={isLoading}
      />
      {editingMember && (
        <EditMemberDialog
          member={editingMember}
          open={!!editingMember}
          onOpenChange={(open) => !open && setEditingMember(null)}
          onEdit={(id, updatedMember) => handleUpdateMember(updatedMember)}
        />
      )}
    </div>
  )
}

// src/svelte-frontend/src/routes/household/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { householdApi } from '$lib/api/household';
	import type { HouseholdMember, HouseholdMemberFormData } from '$lib/types/household';
	import { formatMemberName } from '$lib/types/household';
	import MemberCard from '$lib/components/household/MemberCard.svelte';
	import MemberModal from '$lib/components/household/MemberModal.svelte';
	import DeleteConfirm from '$lib/components/household/DeleteConfirm.svelte';
	import PageHeader from '$lib/components/ui/PageHeader.svelte';

	// State
	let members = $state<HouseholdMember[]>([]);
	let loading = $state(true);
	let error = $state('');

	// Dialog state
	let showAddModal = $state(false);
	let editingMember = $state<HouseholdMember | undefined>(undefined);
	let deletingMember = $state<HouseholdMember | undefined>(undefined);

	// Toast
	let toast = $state<{ message: string; type: 'success' | 'error' } | null>(null);

	function showToast(message: string, type: 'success' | 'error') {
		toast = { message, type };
		setTimeout(() => {
			toast = null;
		}, 3000);
	}

	// Load members
	async function loadMembers() {
		loading = true;
		error = '';
		try {
			members = await householdApi.list();
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to load';
		} finally {
			loading = false;
		}
	}

	// Load on mount
	onMount(() => {
		loadMembers();
	});

	// CRUD handlers
	async function handleAdd(data: HouseholdMemberFormData) {
		try {
			await householdApi.create(data);
			showAddModal = false;
			showToast('Member added', 'success');
			await loadMembers();
		} catch {
			showToast('Failed to add member', 'error');
		}
	}

	async function handleEdit(data: HouseholdMemberFormData) {
		if (!editingMember) return;
		try {
			await householdApi.update(editingMember.id, data);
			editingMember = undefined;
			showToast('Member updated', 'success');
			await loadMembers();
		} catch {
			showToast('Failed to update member', 'error');
		}
	}

	async function handleDelete() {
		if (!deletingMember) return;
		try {
			await householdApi.delete(deletingMember.id);
			deletingMember = undefined;
			showToast('Member deleted', 'success');
			await loadMembers();
		} catch {
			showToast('Failed to delete member', 'error');
		}
	}
</script>

<!-- Toast -->
{#if toast}
	<div
		class="fixed top-4 right-4 z-50 px-4 py-3 rounded-xl shadow-lg text-sm font-medium border {toast.type ===
		'success'
			? 'bg-card text-foreground border-primary/30'
			: 'bg-card text-destructive border-destructive/30'}"
	>
		{toast.message}
	</div>
{/if}

<div class="space-y-6">
	<PageHeader
		title="Household"
		description="Manage your household members and their retirement planning."
	/>

	<!-- Content -->
	{#if loading}
		<p class="text-center text-muted-foreground py-8">Loading household members...</p>
	{:else if error}
		<div class="bg-destructive/10 border border-destructive/30 rounded-xl p-4 text-destructive">
			<p>{error}</p>
			<button onclick={loadMembers} class="mt-2 text-sm underline">Try again</button>
		</div>
	{:else}
		<div class="flex flex-wrap gap-4">
			{#each members as member (member.id)}
				<MemberCard
					{member}
					onEdit={(m) => {
						editingMember = m;
					}}
					onDelete={(m) => {
						deletingMember = m;
					}}
				/>
			{/each}

			<!-- Add Member Button -->
			<button
				onclick={() => {
					showAddModal = true;
				}}
				class="flex flex-col items-center justify-center w-[270px] min-h-[200px]
					border-2 border-dashed border-border rounded-xl
					hover:border-primary/50 hover:bg-accent/30 transition-colors cursor-pointer"
			>
				<svg
					class="w-8 h-8 text-muted-foreground mb-2"
					fill="none"
					stroke="currentColor"
					viewBox="0 0 24 24"
					stroke-width="1.5"
				>
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"
					/>
				</svg>
				<span class="text-sm text-muted-foreground">New Member</span>
			</button>
		</div>
	{/if}
</div>

<!-- Add Modal -->
<MemberModal
	open={showAddModal}
	onSubmit={handleAdd}
	onClose={() => {
		showAddModal = false;
	}}
/>

<!-- Edit Modal -->
<MemberModal
	open={editingMember !== undefined}
	member={editingMember}
	onSubmit={handleEdit}
	onClose={() => {
		editingMember = undefined;
	}}
/>

<!-- Delete Confirmation -->
<DeleteConfirm
	open={deletingMember !== undefined}
	memberName={deletingMember ? formatMemberName(deletingMember) : ''}
	onConfirm={handleDelete}
	onCancel={() => {
		deletingMember = undefined;
	}}
/>
