// src/frontend/components/pension/savings/ContributionPlanCard.tsx
"use client"

import { FormField, FormItem, FormControl, FormMessage } from "@/frontend/components/ui/form"
import { UseFormReturn, useFieldArray } from "react-hook-form"
import { SavingsPensionFormData } from "@/frontend/types/pension-form"
import { Button } from "@/frontend/components/ui/button"
import { Plus, Trash2 } from "lucide-react"
import { ContributionFrequency } from "@/frontend/types/pension"
import { EnumSelect } from "@/frontend/components/ui/enum-select"
import { DateEndPicker } from "@/frontend/components/ui/date-end-picker"
import { DateInput } from '@/frontend/components/ui/date-input'
import { CurrencyInput } from "@/frontend/components/shared/inputs/CurrencyInput"

interface ContributionPlanCardProps {
  form: UseFormReturn<SavingsPensionFormData>
  memberId?: string
}

/**
 * Component for managing contribution plan steps.
 * Handles adding, editing, and removing contribution steps with dates and amounts.
 */
export function ContributionPlanCard({ form, memberId }: ContributionPlanCardProps) {
  const { fields, append, remove } = useFieldArray({
    control: form.control,
    name: "contribution_plan_steps"
  })

  const handleAddContribution = () => {
    let startDate = new Date()

    // If there are existing contributions, check the last one's end date
    if (fields.length > 0) {
      const lastEndDate = form.getValues(`contribution_plan_steps.${fields.length - 1}.end_date`)
      
      if (lastEndDate) {
        // Use the day after the last end date as the start date
        startDate = new Date(lastEndDate)
        startDate.setDate(startDate.getDate() + 1)
      }
    }

    append({
      amount: 0,
      frequency: ContributionFrequency.MONTHLY,
      start_date: startDate,
      end_date: undefined,
      note: undefined
    })
  }

  return (
    <div className="relative">
      {fields.length > 0 && (
        <div className="grid grid-cols-[1fr_1fr_1fr_1fr_auto] gap-4 mb-2 px-2">
          <div className="text-sm font-medium text-muted-foreground">Amount</div>
          <div className="text-sm font-medium text-muted-foreground">Frequency</div>
          <div className="text-sm font-medium text-muted-foreground">Start Date</div>
          <div className="text-sm font-medium text-muted-foreground">End Date</div>
          <div className="w-9"></div>
        </div>
      )}

      <div className="space-y-4">
        {fields.map((field, index) => (
          <div key={field.id} className="grid grid-cols-[1fr_1fr_1fr_1fr_auto] gap-4 items-end p-3 pt-1 rounded-lg bg-muted">
            <FormField
              control={form.control}
              name={`contribution_plan_steps.${index}.amount`}
              render={({ field }) => (
                <FormItem className="space-y-0">
                  <FormControl>
                    <CurrencyInput
                      value={field.value}
                      onChange={field.onChange}
                      onBlur={field.onBlur}
                      decimals={2}
                      min={0}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name={`contribution_plan_steps.${index}.frequency`}
              render={() => (
                <FormItem className="space-y-0">
                  <FormControl>
                    <EnumSelect<ContributionFrequency, SavingsPensionFormData>
                      name={`contribution_plan_steps.${index}.frequency`}
                      control={form.control}
                      options={[
                        { value: ContributionFrequency.MONTHLY, label: "Monthly" },
                        { value: ContributionFrequency.QUARTERLY, label: "Quarterly" },
                        { value: ContributionFrequency.SEMI_ANNUALLY, label: "Semi-Annually" },
                        { value: ContributionFrequency.ANNUALLY, label: "Annually" },
                        { value: ContributionFrequency.ONE_TIME, label: "One-Time" }
                      ]}
                      defaultValue={ContributionFrequency.MONTHLY}
                      label=""
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name={`contribution_plan_steps.${index}.start_date`}
              render={({ field }) => (
                <DateInput
                  field={field}
                  className="space-y-0"
                />
              )}
            />

            <FormField
              control={form.control}
              name={`contribution_plan_steps.${index}.end_date`}
              render={({ field }) => (
                <DateEndPicker
                  field={field}
                  startDate={form.getValues(`contribution_plan_steps.${index}.start_date`)}
                  memberId={memberId || form.watch('member_id')}
                  className="space-y-0"
                />
              )}
            />

            <Button
              type="button"
              variant="ghost"
              size="icon"
              onClick={() => remove(index)}
              className="h-9 w-9 self-end"
            >
              <Trash2 className="h-4 w-4" />
            </Button>
          </div>
        ))}

        <Button
          type="button"
          variant="outline"
          className="w-full border-dashed text-center py-6 text-sm text-muted-foreground border-2 rounded-lg"
          onClick={handleAddContribution}
        >
          <Plus className="h-4 w-4 mr-2" />
          {fields.length === 0 ? (
            <span>No contributions planned yet. Click to add your first contribution.</span>
          ) : (
            <span>Add Contribution</span>
          )}
        </Button>
      </div>
    </div>
  )
}

// src/svelte-frontend/src/lib/components/pension/ContributionPlanCard.svelte
<script lang="ts">
	import { m } from '$lib/paraglide/messages.js';
	import { Plus, Trash2 } from '@lucide/svelte';
	import { ContributionFrequency, type ContributionStep } from '$lib/types/pension';
	import { toISODate } from '$lib/utils/format';
	import CurrencyInput from '$lib/components/ui/CurrencyInput.svelte';
	import Card from '$lib/components/ui/Card.svelte';

	let {
		steps = $bindable([]),
	}: {
		steps: ContributionStep[];
	} = $props();

	const frequencyOptions: { value: ContributionFrequency; label: () => string }[] = [
		{ value: ContributionFrequency.MONTHLY, label: () => m.pension_per_month() },
		{ value: ContributionFrequency.QUARTERLY, label: () => m.pension_per_quarter() },
		{ value: ContributionFrequency.SEMI_ANNUALLY, label: () => m.pension_per_half_year() },
		{ value: ContributionFrequency.ANNUALLY, label: () => m.pension_per_year() },
		{ value: ContributionFrequency.ONE_TIME, label: () => m.pension_one_time() }
	];

	function addStep() {
		let startDate = toISODate(new Date());
		if (steps.length > 0) {
			const lastStep = steps[steps.length - 1];
			if (lastStep.end_date) {
				const nextDay = new Date(lastStep.end_date);
				nextDay.setDate(nextDay.getDate() + 1);
				startDate = toISODate(nextDay);
			}
		}
		steps = [
			...steps,
			{
				amount: 0,
				frequency: ContributionFrequency.MONTHLY,
				start_date: startDate
			}
		];
	}

	function removeStep(index: number) {
		steps = steps.filter((_, i) => i !== index);
	}
</script>

<Card title={m.contribution_plan_title()}>
	{#if steps.length > 0}
		<!-- Header row -->
		<div class="grid grid-cols-[1fr_1fr_1fr_1fr_auto] gap-4 mb-2">
			<span class="text-xs font-medium text-muted-foreground">{m.contribution_amount()}</span>
			<span class="text-xs font-medium text-muted-foreground">{m.contribution_frequency()}</span>
			<span class="text-xs font-medium text-muted-foreground">{m.contribution_start_date()}</span>
			<span class="text-xs font-medium text-muted-foreground">{m.contribution_end_date()}</span>
			<span class="w-9"></span>
		</div>

		<!-- Step rows -->
		{#each steps as step, i}
			<div class="grid grid-cols-[1fr_1fr_1fr_1fr_auto] gap-4 mb-3 items-center">
				<CurrencyInput bind:value={step.amount} min={0} decimals={2} />

				<select
					bind:value={step.frequency}
					class="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm"
				>
					{#each frequencyOptions as opt}
						<option value={opt.value}>{opt.label()}</option>
					{/each}
				</select>

				<input
					type="date"
					bind:value={step.start_date}
					class="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm"
				/>

				<input
					type="date"
					bind:value={step.end_date}
					class="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm"
				/>

				<button
					type="button"
					onclick={() => removeStep(i)}
					class="p-2 text-muted-foreground hover:text-destructive transition-colors rounded-lg hover:bg-accent/50"
				>
					<Trash2 class="h-4 w-4" />
				</button>
			</div>
		{/each}
	{/if}

	<!-- Add button -->
	<button
		type="button"
		onclick={addStep}
		class="w-full border-2 border-dashed border-border rounded-lg py-3 text-sm text-muted-foreground hover:border-primary hover:text-primary transition-colors flex items-center justify-center gap-2"
	>
		<Plus class="h-4 w-4" />
		{#if steps.length === 0}
			{m.contribution_add_first()}
		{:else}
			{m.contribution_add()}
		{/if}
	</button>
</Card>
