// src/svelte-frontend/src/routes/settings/+page.svelte
<script lang="ts">
	import type { FrontendSettings } from '$lib/types/settings';
	import {
		UILocale,
		UI_LOCALE_LABELS,
		NumberLocale,
		NUMBER_LOCALE_LABELS,
		Currency,
		CURRENCY_LABELS
	} from '$lib/types/settings';
	import { settingsStore } from '$lib/stores/settings.svelte';
	import { themeStore } from '$lib/stores/theme.svelte';
	import PageHeader from '$lib/components/ui/PageHeader.svelte';
	import Card from '$lib/components/ui/Card.svelte';
	import ContentSection from '$lib/components/ui/ContentSection.svelte';
	import Explanation from '$lib/components/ui/Explanation.svelte';
	import NumberFormatPreview from '$lib/components/settings/NumberFormatPreview.svelte';
	import ProjectionPreview from '$lib/components/settings/ProjectionPreview.svelte';
	import ScenarioRatesGrid from '$lib/components/settings/ScenarioRatesGrid.svelte';

	// Bind to the global settings store
	let settings = $derived(settingsStore.current);
	let loading = $derived(!settingsStore.loaded);
	let rateErrors = $state<Record<string, string>>({});


	// Update a setting via the global store
	async function updateSetting(updates: Partial<FrontendSettings>) {
		await settingsStore.update(updates);
	}

	// Rate validation
	function validateRateRelationships(
		type: 'projection' | 'state_pension',
		scenario: 'pessimistic' | 'realistic' | 'optimistic',
		newValue: number
	): boolean {
		const values = {
			pessimistic:
				scenario === 'pessimistic'
					? newValue
					: settings[`${type}_pessimistic_rate` as keyof FrontendSettings],
			realistic:
				scenario === 'realistic'
					? newValue
					: settings[`${type}_realistic_rate` as keyof FrontendSettings],
			optimistic:
				scenario === 'optimistic'
					? newValue
					: settings[`${type}_optimistic_rate` as keyof FrontendSettings]
		};

		const errorKey = `${type}_${scenario}_rate`;
		const label = type === 'projection' ? 'ETF' : 'State pension';

		if (scenario === 'pessimistic' && values.pessimistic > values.realistic) {
			rateErrors = { ...rateErrors, [errorKey]: `${label} pessimistic rate cannot exceed realistic rate` };
			return false;
		}
		if (scenario === 'realistic') {
			if (values.realistic < values.pessimistic) {
				rateErrors = { ...rateErrors, [errorKey]: `${label} realistic rate cannot be below pessimistic rate` };
				return false;
			}
			if (values.realistic > values.optimistic) {
				rateErrors = { ...rateErrors, [errorKey]: `${label} realistic rate cannot exceed optimistic rate` };
				return false;
			}
		}
		if (scenario === 'optimistic' && values.optimistic < values.realistic) {
			rateErrors = { ...rateErrors, [errorKey]: `${label} optimistic rate cannot be below realistic rate` };
			return false;
		}

		// Clear error
		if (rateErrors[errorKey]) {
			rateErrors = { ...rateErrors, [errorKey]: '' };
		}
		return true;
	}

	function handleRateChange(key: keyof FrontendSettings, value: number) {
		if (key === 'inflation_rate') {
			updateSetting({ [key]: value });
			return;
		}

		// Parse type and scenario from key like "projection_pessimistic_rate"
		const parts = key.split('_');
		const scenario = parts[parts.length - 2] as 'pessimistic' | 'realistic' | 'optimistic';
		const type = key.startsWith('state_pension') ? 'state_pension' : 'projection';

		if (validateRateRelationships(type, scenario, value)) {
			updateSetting({ [key]: value });
		}
	}
</script>

<div class="space-y-6">
	<PageHeader
		title="Settings"
		description="Customize your experience with personalized preferences and calculation parameters"
	/>

	{#if !settingsStore.loaded}
		<p class="text-center text-muted-foreground py-8">Loading settings...</p>
	{/if}

	<!-- Language Settings -->
	<ContentSection>
		<Card title="Language Settings" description="Choose your preferred language and formats">
			<div class="space-y-4">
				<div>
					<label for="ui-locale" class="block text-sm font-medium mb-2">Interface Language</label>
					<select
						id="ui-locale"
						value={settings.ui_locale}
						onchange={(e) => updateSetting({ ui_locale: (e.target as HTMLSelectElement).value })}
						disabled={loading}
						class="w-[280px] rounded-lg border border-input bg-background px-3 py-2 text-sm
							focus:border-ring focus:ring-1 focus:ring-ring outline-none transition-colors"
					>
						{#each Object.values(UILocale) as locale}
							<option value={locale}>{UI_LOCALE_LABELS[locale]}</option>
						{/each}
					</select>
				</div>
			</div>
		</Card>
	</ContentSection>

	<!-- Number & Currency Format -->
	<ContentSection>
		<Card title="Number & Currency Format" description="Configure how numbers, dates, and currency values are displayed">
			<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
				<div>
					<label for="number-locale" class="block text-sm font-medium mb-2">Number & Date Format</label>
					<select
						id="number-locale"
						value={settings.number_locale}
						onchange={(e) => updateSetting({ number_locale: (e.target as HTMLSelectElement).value })}
						disabled={loading}
						class="w-[280px] rounded-lg border border-input bg-background px-3 py-2 text-sm
							focus:border-ring focus:ring-1 focus:ring-ring outline-none transition-colors"
					>
						{#each Object.values(NumberLocale) as locale}
							<option value={locale}>{NUMBER_LOCALE_LABELS[locale]}</option>
						{/each}
					</select>
				</div>

				<div>
					<label for="currency" class="block text-sm font-medium mb-2">Default Currency</label>
					<select
						id="currency"
						value={settings.currency}
						onchange={(e) => updateSetting({ currency: (e.target as HTMLSelectElement).value })}
						disabled={loading}
						class="w-[280px] rounded-lg border border-input bg-background px-3 py-2 text-sm
							focus:border-ring focus:ring-1 focus:ring-ring outline-none transition-colors"
					>
						{#each Object.values(Currency) as cur}
							<option value={cur}>{CURRENCY_LABELS[cur]}</option>
						{/each}
					</select>
				</div>
			</div>
		</Card>

		{#snippet aside()}
			<Explanation title="Format Preview">
				<NumberFormatPreview locale={settings.number_locale} currency={settings.currency} />
			</Explanation>
		{/snippet}
	</ContentSection>

	<!-- Growth Rate Scenarios -->
	<ContentSection>
		<ScenarioRatesGrid
			{settings}
			onUpdate={handleRateChange}
			disabled={loading}
			{rateErrors}
		/>

		{#snippet aside()}
			<ProjectionPreview
				locale={settings.number_locale}
				currency={settings.currency}
				inflationRate={settings.inflation_rate}
				pessimisticRate={settings.projection_pessimistic_rate}
				realisticRate={settings.projection_realistic_rate}
				optimisticRate={settings.projection_optimistic_rate}
			/>
		{/snippet}
	</ContentSection>

	<!-- Theme Settings -->
	<ContentSection>
		<Card title="Theme Settings" description="Choose your preferred color theme">
			<div class="grid grid-cols-3 gap-4">
				{#each [
					{ value: 'light', label: 'Light', icon: 'M12 3v2.25m6.364.386l-1.591 1.591M21 12h-2.25m-.386 6.364l-1.591-1.591M12 18.75V21m-4.773-4.227l-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z' },
					{ value: 'dark', label: 'Dark', icon: 'M21.752 15.002A9.72 9.72 0 0118 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 003 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 009.002-5.998z' },
					{ value: 'system', label: 'System', icon: 'M9 17.25v1.007a3 3 0 01-.879 2.122L7.5 21h9l-.621-.621A3 3 0 0115 18.257V17.25m6-12V15a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 15V5.25m18 0A2.25 2.25 0 0018.75 3H5.25A2.25 2.25 0 003 5.25m18 0V12a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 12V5.25' }
				] as option}
					<button
						onclick={() => themeStore.set(option.value as 'light' | 'dark' | 'system')}
						class="p-3 rounded-lg border cursor-pointer transition-colors
							{themeStore.current === option.value
							? 'bg-primary/10 border-primary'
							: 'bg-card border-border hover:border-primary/50'}"
					>
						<div class="flex items-center justify-center mb-2">
							<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="1.5">
								<path stroke-linecap="round" stroke-linejoin="round" d={option.icon} />
							</svg>
						</div>
						<p class="text-xs font-medium text-center">{option.label}</p>
					</button>
				{/each}
			</div>
		</Card>
	</ContentSection>
</div>

// app/settings/page.tsx
"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/frontend/components/ui/card"
import { Label } from "@/frontend/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/frontend/components/ui/select"
import { Currency, CURRENCY_LABELS, NumberLocale, NUMBER_LOCALE_LABELS, UILocale, UI_LOCALE_LABELS } from "@/frontend/types/enums"
import { useSettings } from "@/frontend/context/SettingsContext"
import { useEffect, useState } from "react"
import { RateInput } from "@/frontend/components/ui/rate-input"
import { useTheme } from "next-themes"
import { Moon, Sun, Laptop } from "lucide-react"
import { NumberFormatPreview } from "@/frontend/components/settings/number-format-preview"
import { ProjectionPreview } from "@/frontend/components/settings/projection-preview"

export default function SettingsPage() {
  const { settings, updateSettings, isLoading, error } = useSettings()
  const { theme, setTheme } = useTheme()
  const [mounted, setMounted] = useState(false)
  const [rateErrors, setRateErrors] = useState<{[key: string]: string}>({})

  // Ensure client-side rendering for preview
  useEffect(() => {
    setMounted(true)
  }, [])

  const handleCurrencyChange = (value: string) => {
    updateSettings({ currency: value })
  }

  const handleUILocaleChange = (value: string) => {
    updateSettings({ ui_locale: value })
  }

  const handleNumberLocaleChange = (value: string) => {
    updateSettings({ number_locale: value })
  }

  const validateRateRelationships = (
    type: 'pessimistic' | 'realistic' | 'optimistic',
    newValue: number
  ): boolean => {
    // Create a temporary object with the new value
    const updatedValues = {
      pessimistic: type === 'pessimistic' ? newValue : settings.projection_pessimistic_rate,
      realistic: type === 'realistic' ? newValue : settings.projection_realistic_rate,
      optimistic: type === 'optimistic' ? newValue : settings.projection_optimistic_rate
    }

    if (type === 'pessimistic' && updatedValues.pessimistic > updatedValues.realistic) {
      setRateErrors({
        ...rateErrors,
        pessimistic: 'Pessimistic rate cannot be higher than realistic rate'
      })
      return false
    }

    if (type === 'realistic') {
      if (updatedValues.realistic < updatedValues.pessimistic) {
        setRateErrors({
          ...rateErrors,
          realistic: 'Realistic rate cannot be lower than pessimistic rate'
        })
        return false
      }
      if (updatedValues.realistic > updatedValues.optimistic) {
        setRateErrors({
          ...rateErrors,
          realistic: 'Realistic rate cannot be higher than optimistic rate'
        })
        return false
      }
    }

    if (type === 'optimistic' && updatedValues.optimistic < updatedValues.realistic) {
      setRateErrors({
        ...rateErrors,
        optimistic: 'Optimistic rate cannot be lower than realistic rate'
      })
      return false
    }

    // Clear errors for the current type if validation passes
    if (rateErrors[type]) {
      setRateErrors({
        ...rateErrors,
        [type]: ''
      })
    }

    return true
  }

  const handleProjectionRateChange = (type: 'pessimistic' | 'realistic' | 'optimistic' | 'inflation', value: number) => {
    if (type === 'inflation') {
      updateSettings({ inflation_rate: value })
      return
    }

    // Validate rate relationships before updating
    if (validateRateRelationships(type, value)) {
      const rateKey = `projection_${type}_rate` as const
      updateSettings({ [rateKey]: value })
    }
  }

  // Replace renderPreview with NumberFormatPreview component
  const renderPreview = () => {
    if (!mounted) return null
    return (
      <NumberFormatPreview
        locale={settings.number_locale}
        currency={settings.currency}
      />
    )
  }

  // Replace renderProjectionPreview with ProjectionPreview component
  const renderProjectionPreview = () => {
    if (!mounted) return null
    return (
      <ProjectionPreview
        locale={settings.number_locale}
        currency={settings.currency}
        rates={settings}
      />
    )
  }

  // Only render rate inputs after client-side hydration
  const renderRateInputs = () => {
    if (!mounted) return null

    return (
      <div>
        <div>
          <RateInput
            label="Inflation Rate"
            value={settings.inflation_rate}
            onChange={(value) => handleProjectionRateChange('inflation', value)}
            min={0}
            max={10}
            step={0.1}
            disabled={isLoading}
          />
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mt-4">
          <div>
            <RateInput
              label="Pessimistic Scenario Return Rate"
              value={settings.projection_pessimistic_rate}
              onChange={(value) => handleProjectionRateChange('pessimistic', value)}
              min={0}
              max={15}
              step={0.1}
              disabled={isLoading}
              error={rateErrors.pessimistic}
            />
          </div>

          <div>
            <RateInput
              label="Realistic Scenario Return Rate"
              value={settings.projection_realistic_rate}
              onChange={(value) => handleProjectionRateChange('realistic', value)}
              min={0}
              max={15}
              step={0.1}
              disabled={isLoading}
              error={rateErrors.realistic}
            />
          </div>

          <div>
            <RateInput
              label="Optimistic Scenario Return Rate"
              value={settings.projection_optimistic_rate}
              onChange={(value) => handleProjectionRateChange('optimistic', value)}
              min={0}
              max={15}
              step={0.1}
              disabled={isLoading}
              error={rateErrors.optimistic}
            />
          </div>
        </div>
      </div>
    )
  }

  // Render theme preview
  const renderThemePreview = () => {
    if (!mounted) return null

    return (
      <div className="space-y-6">
        <div className="grid grid-cols-3 gap-4">
          <div 
            className={`p-2 rounded-lg border cursor-pointer transition-colors ${
              theme === 'light' ? 'bg-primary/10 border-primary' : 'bg-card border-border hover:border-primary/50'
            }`}
            onClick={() => setTheme('light')}
          >
            <div className="flex items-center justify-center mb-2">
              <Sun className="h-4 w-4" />
            </div>
            <p className="text-xs font-medium text-center">Light</p>
          </div>

          <div 
            className={`p-2 rounded-lg border cursor-pointer transition-colors ${
              theme === 'dark' ? 'bg-primary/10 border-primary' : 'bg-card border-border hover:border-primary/50'
            }`}
            onClick={() => setTheme('dark')}
          >
            <div className="flex items-center justify-center mb-2">
              <Moon className="h-4 w-4" />
            </div>
            <p className="text-xs font-medium text-center">Dark</p>
          </div>

          <div 
            className={`p-2 rounded-lg border cursor-pointer transition-colors ${
              theme === 'system' ? 'bg-primary/10 border-primary' : 'bg-card border-border hover:border-primary/50'
            }`}
            onClick={() => setTheme('system')}
          >
            <div className="flex items-center justify-center mb-2">
              <Laptop className="h-4 w-4" />
            </div>
            <p className="text-xs font-medium text-center">System</p>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Settings</h1>
          <p className="text-muted-foreground mt-2">
            Customize your experience with personalized preferences and calculation parameters
          </p>
        </div>
      </div>
      
      {error && (
        <div className="bg-destructive/15 text-destructive px-4 py-2 rounded-md">
          {error}
        </div>
      )}
      
      {/* Language Settings */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 lg:gap-6">
        <div className="lg:col-span-8">
          <Card>
            <CardHeader>
              <CardTitle>Language Settings</CardTitle>
              <CardDescription>Choose your preferred language and formats</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-4">
                <div>
                <div className="mb-2">
                  <Label htmlFor="ui-locale">Interface Language</Label>
                  </div>
                  <Select
                    value={settings.ui_locale}
                    onValueChange={handleUILocaleChange}
                    disabled={isLoading}
                  >
                    <SelectTrigger className="w-[280px]">
                      <SelectValue placeholder="Select Language" />
                    </SelectTrigger>
                    <SelectContent>
                      {Object.values(UILocale).map((locale) => (
                        <SelectItem key={locale} value={locale}>
                          {UI_LOCALE_LABELS[locale as UILocale]}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Number & Currency Format */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 lg:gap-6">
        <div className="lg:col-span-8">
          <Card>
            <CardHeader>
              <CardTitle>Number & Currency Format</CardTitle>
              <CardDescription>Configure how numbers, dates, and currency values are displayed</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                <div className="mb-2">
                  <Label htmlFor="number-locale">Number & Date Format</Label>
                  </div>
                  <Select
                    value={settings.number_locale}
                    onValueChange={handleNumberLocaleChange}
                    disabled={isLoading}
                  >
                    <SelectTrigger className="w-[280px]">
                      <SelectValue placeholder="Select Format" />
                    </SelectTrigger>
                    <SelectContent>
                      {Object.values(NumberLocale).map((locale) => (
                        <SelectItem key={locale} value={locale}>
                          {NUMBER_LOCALE_LABELS[locale as NumberLocale]}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <div className="mb-2">
                    <Label htmlFor="currency">Default Currency</Label>
                  </div>
                  <Select
                    value={settings.currency}
                    onValueChange={handleCurrencyChange}
                    disabled={isLoading}
                  >
                    <SelectTrigger className="w-[280px]">
                      <SelectValue placeholder="Select Currency" />
                    </SelectTrigger>
                    <SelectContent>
                      {Object.values(Currency).map((currency) => (
                        <SelectItem key={currency} value={currency}>
                          {CURRENCY_LABELS[currency as Currency]}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>

            </CardContent>
          </Card>
        </div>
        <div className="lg:col-span-4">
              {renderPreview()}
        </div>
      </div>

      {/* Investment Settings */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 lg:gap-6">
        <div className="lg:col-span-8">
          <Card>
            <CardHeader>
              <CardTitle>Investment Projections</CardTitle>
              <CardDescription>Configure return rate scenarios and inflation for investment projections</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {renderRateInputs()}
            </CardContent>
          </Card>
        </div>
        <div className="lg:col-span-4">
          {renderProjectionPreview()}
        </div>
      </div>

      {/* Theme Settings */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 lg:gap-6">
        <div className="lg:col-span-8">
          <Card>
            <CardHeader>
              <CardTitle>Theme Settings</CardTitle>
              <CardDescription>Choose your preferred color theme</CardDescription>
            </CardHeader>
            <CardContent>
              {renderThemePreview()}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
