// src/svelte-frontend/src/lib/components/ui/Card.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	let {
		title,
		description,
		headerActions,
		children
	}: {
		title?: string;
		description?: string;
		headerActions?: Snippet;
		children: Snippet;
	} = $props();
</script>

<div class="bg-card rounded-xl border border-border shadow-sm p-6">
	{#if title || headerActions}
		<div class="flex justify-between items-start pb-6">
			<div class="space-y-1.5">
				{#if title}
					<h3 class="text-lg font-semibold">{title}</h3>
				{/if}
				{#if description}
					<p class="text-sm text-muted-foreground">{description}</p>
				{/if}
			</div>
			{#if headerActions}
				<div class="flex items-center space-x-2">
					{@render headerActions()}
				</div>
			{/if}
		</div>
	{:else if description}
		<p class="text-sm text-muted-foreground mb-3">{description}</p>
	{/if}
	{@render children()}
</div>

// src/frontend/components/ui/card.tsx
import * as React from "react"

import { cn } from "@/frontend/lib/utils"

function Card({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card"
      className={cn(
        "bg-card text-card-foreground rounded-xl border shadow-sm",
        className
      )}
      {...props}
    />
  )
}

function CardHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-header"
      className={cn("flex flex-col gap-1.5 p-6", className)}
      {...props}
    />
  )
}

function CardTitle({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-title"
      className={cn("leading-none font-semibold tracking-tight", className)}
      {...props}
    />
  )
}

function CardDescription({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-description"
      className={cn("text-muted-foreground text-sm", className)}
      {...props}
    />
  )
}

function CardContent({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-content"
      className={cn("p-6 pt-0", className)}
      {...props}
    />
  )
}

function CardFooter({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-footer"
      className={cn("flex items-center p-6 pt-0", className)}
      {...props}
    />
  )
}

export { Card, CardHeader, CardFooter, CardTitle, CardDescription, CardContent }
