// src/frontend/src/lib/components/settings/ScenarioRatesGrid.svelte
<!--
@file src/lib/components/settings/ScenarioRatesGrid.svelte
@kind component
@purpose Rendert das Eingaberaster fuer pessimistische, realistische und optimistische Renditeannahmen.
@contains Das Template verbindet Props/Bindings mit UI-Abschnitten, Dialogen oder Datenvisualisierung.
-->

<script lang="ts">
	import Card from '$lib/components/ui/Card.svelte';
	import RateStepperInput from './RateStepperInput.svelte';
	import type { FrontendSettings } from '$lib/types/settings';
	import { m } from '$lib/paraglide/messages.js';
	import { TrendingDown, ArrowRight, TrendingUp } from '@lucide/svelte';

	let {
		settings,
		onUpdate,
		disabled = false,
		rateErrors = {}
	}: {
		settings: FrontendSettings;
		onUpdate: (key: keyof FrontendSettings, value: number) => void;
		disabled?: boolean;
		rateErrors?: Record<string, string>;
	} = $props();

	const etfKeys = [
		'projection_pessimistic_rate',
		'projection_realistic_rate',
		'projection_optimistic_rate'
	] as const;
	const stateKeys = [
		'state_pension_pessimistic_rate',
		'state_pension_realistic_rate',
		'state_pension_optimistic_rate'
	] as const;
</script>

<Card
	title={m.settings_growth_rates_title()}
	description={m.settings_growth_rates_description()}
>
	<div class="space-y-8">
		<!-- Inflation Rate -->
		<div class="grid grid-cols-4 gap-6">
			<div class="flex items-center">
				<span class="text-base font-semibold">{m.settings_inflation_rate()}</span>
			</div>
			<div>
				<RateStepperInput
					value={settings.inflation_rate}
					onChange={(v) => onUpdate('inflation_rate', v)}
					{disabled}
				/>
				{#if rateErrors.inflation_rate}
					<p class="text-xs text-destructive mt-1">{rateErrors.inflation_rate}</p>
				{/if}
			</div>
		</div>

		<hr class="border-border" />

		<!-- Scenario Rates Grid -->
		<div class="space-y-6">
			<!-- Header row -->
			<div class="grid grid-cols-4 gap-6">
				<div></div>
				<div class="grid grid-cols-3 gap-6 col-span-3 justify-items-center">
					<div class="flex flex-col items-center w-24">
						<TrendingDown class="w-5 h-5 mb-2 text-yellow-500" />
						<span class="text-sm font-medium">{m.settings_pessimistic()}</span>
					</div>
					<div class="flex flex-col items-center w-24">
						<ArrowRight class="w-5 h-5 mb-2 text-blue-500" />
						<span class="text-sm font-medium">{m.settings_realistic()}</span>
					</div>
					<div class="flex flex-col items-center w-24">
						<TrendingUp class="w-5 h-5 mb-2 text-green-500" />
						<span class="text-sm font-medium">{m.settings_optimistic()}</span>
					</div>
				</div>
			</div>

			<!-- ETF Pension row -->
			<div class="grid grid-cols-4 gap-6">
				<div class="flex items-center">
					<span class="text-base">{m.settings_etf_pension()}</span>
				</div>
				<div class="grid grid-cols-3 gap-6 col-span-3">
					{#each etfKeys as key}
						<div>
							<RateStepperInput
								value={settings[key]}
								onChange={(v) => onUpdate(key, v)}
								{disabled}
							/>
							{#if rateErrors[key]}
								<p class="text-xs text-destructive mt-1">{rateErrors[key]}</p>
							{/if}
						</div>
					{/each}
				</div>
			</div>

			<!-- State Pension row -->
			<div class="grid grid-cols-4 gap-6">
				<div class="flex items-center">
					<span class="text-base">{m.settings_state_pension()}</span>
				</div>
				<div class="grid grid-cols-3 gap-6 col-span-3">
					{#each stateKeys as key}
						<div>
							<RateStepperInput
								value={settings[key]}
								onChange={(v) => onUpdate(key, v)}
								{disabled}
							/>
							{#if rateErrors[key]}
								<p class="text-xs text-destructive mt-1">{rateErrors[key]}</p>
							{/if}
						</div>
					{/each}
				</div>
			</div>
		</div>
	</div>
</Card>

// src/frontend/components/settings/ScenarioRatesGrid.tsx
"use client"

import { RateInput } from "@/frontend/components/ui/rate-input"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/frontend/components/ui/card"
import { Label } from "@/frontend/components/ui/label"
import { FrontendSettings } from "@/frontend/types/settings"
import { TrendingDown, ArrowRight, TrendingUp } from "lucide-react"
import { Separator } from "@/frontend/components/ui/separator"

interface ScenarioRatesGridProps {
  settings: FrontendSettings;
  onUpdate: (key: keyof FrontendSettings, value: number) => void;
  isLoading: boolean;
  rateErrors: { [key: string]: string };
}

export function ScenarioRatesGrid({ settings, onUpdate, isLoading, rateErrors }: ScenarioRatesGridProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Growth Rate Scenarios</CardTitle>
        <CardDescription>Configure annual growth rates for different pension types</CardDescription>
      </CardHeader>
      <CardContent className="space-y-8">
        {/* Inflation Rate (standalone) */}
        <div className="grid grid-cols-4 gap-6">
          <div className="flex items-center">
            <Label className="text-base font-semibold">Inflation Rate</Label>
          </div>
          <div>
            <RateInput
              label="Inflation Rate"
              value={settings.inflation_rate}
              onChange={(value) => onUpdate('inflation_rate', value)}
              min={0}
              max={15}
              step={0.1}
              disabled={isLoading}
              error={rateErrors.inflation_rate}
              hideLabel
            />
          </div>
        </div>

        <Separator className="my-6" />

        {/* Scenario Rates Grid */}
        <div className="space-y-6">
          {/* Header row */}
          <div className="grid grid-cols-4 gap-6">
            <div className="col-span-1"></div>
            <div className="col-span-3 grid grid-cols-3 gap-6">
              <div className="flex flex-col items-center">
                <TrendingDown className="h-5 w-5 mb-2 text-yellow-500" />
                <span className="text-sm font-medium">Pessimistic</span>
              </div>
              <div className="flex flex-col items-center">
                <ArrowRight className="h-5 w-5 mb-2 text-blue-500" />
                <span className="text-sm font-medium">Realistic</span>
              </div>
              <div className="flex flex-col items-center">
                <TrendingUp className="h-5 w-5 mb-2 text-green-500" />
                <span className="text-sm font-medium">Optimistic</span>
              </div>
            </div>
          </div>
          
          {/* ETF Pension row */}
          <div className="grid grid-cols-4 gap-6">
            <div className="flex items-center">
              <Label className="text-base">ETF Pension</Label>
            </div>
            <div className="col-span-3 grid grid-cols-3 gap-6">
              <RateInput
                label="ETF Pension Pessimistic Rate"
                value={settings.projection_pessimistic_rate}
                onChange={(value) => onUpdate('projection_pessimistic_rate', value)}
                min={0}
                max={15}
                step={0.1}
                disabled={isLoading}
                error={rateErrors.projection_pessimistic_rate}
                hideLabel
              />
              <RateInput
                label="ETF Pension Realistic Rate"
                value={settings.projection_realistic_rate}
                onChange={(value) => onUpdate('projection_realistic_rate', value)}
                min={0}
                max={15}
                step={0.1}
                disabled={isLoading}
                error={rateErrors.projection_realistic_rate}
                hideLabel
              />
              <RateInput
                label="ETF Pension Optimistic Rate"
                value={settings.projection_optimistic_rate}
                onChange={(value) => onUpdate('projection_optimistic_rate', value)}
                min={0}
                max={15}
                step={0.1}
                disabled={isLoading}
                error={rateErrors.projection_optimistic_rate}
                hideLabel
              />
            </div>
          </div>
          
          {/* State Pension row */}
          <div className="grid grid-cols-4 gap-6">
            <div className="flex items-center">
              <Label className="text-base">State Pension</Label>
            </div>
            <div className="col-span-3 grid grid-cols-3 gap-6">
              <RateInput
                label="State Pension Pessimistic Rate"
                value={settings.state_pension_pessimistic_rate}
                onChange={(value) => onUpdate('state_pension_pessimistic_rate', value)}
                min={0}
                max={15}
                step={0.1}
                disabled={isLoading}
                error={rateErrors.state_pension_pessimistic_rate}
                hideLabel
              />
              <RateInput
                label="State Pension Realistic Rate"
                value={settings.state_pension_realistic_rate}
                onChange={(value) => onUpdate('state_pension_realistic_rate', value)}
                min={0}
                max={15}
                step={0.1}
                disabled={isLoading}
                error={rateErrors.state_pension_realistic_rate}
                hideLabel
              />
              <RateInput
                label="State Pension Optimistic Rate"
                value={settings.state_pension_optimistic_rate}
                onChange={(value) => onUpdate('state_pension_optimistic_rate', value)}
                min={0}
                max={15}
                step={0.1}
                disabled={isLoading}
                error={rateErrors.state_pension_optimistic_rate}
                hideLabel
              />
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
