// app/pension/company/new/page.tsx
"use client"

import { useForm } from "react-hook-form"
import { useRouter, useSearchParams } from "next/navigation"
import { Form } from "@/frontend/components/ui/form"
import { Button } from "@/frontend/components/ui/button"
import { CompanyPensionFormData } from "@/frontend/types/pension-form"
import { PensionType, CompanyPension } from "@/frontend/types/pension"
import { usePension } from "@/frontend/context/pension"
import { toast } from "sonner"
import { getPensionListRoute } from "@/frontend/lib/routes"
import { BasicInformationCard } from "@/frontend/components/pension/company/BasicInformationCard"
import { PensionStatementsCard } from "@/frontend/components/pension/company/PensionStatementsCard"
import { zodResolver } from "@hookform/resolvers/zod"
import { companyPensionSchema } from "@/frontend/lib/validations/pension"
import { ContributionFrequency } from "@/frontend/types/pension"
import { toISODateString } from "@/frontend/lib/dateUtils"
import { ContributionPlanCard } from "@/frontend/components/pension/company/ContributionPlanCard"
import { FormLayout, FormSection } from "@/frontend/components/shared"
import { BasicInformationExplanation } from "@/frontend/components/pension/company/explanations/BasicInformationExplanation"
import { ContributionPlanExplanation } from "@/frontend/components/pension/company/explanations/ContributionPlanExplanation"
import { StatementsExplanation } from "@/frontend/components/pension/company/explanations/StatementsExplanation"

export default function NewCompanyPensionPage() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const { createCompanyPension, createCompanyPensionWithStatement } = usePension()
  
  const memberId = searchParams?.get('member_id') || ""

  const form = useForm<CompanyPensionFormData>({
    resolver: zodResolver(companyPensionSchema),
    defaultValues: {
      type: PensionType.COMPANY,
      name: "",
      member_id: memberId,
      employer: "",
      start_date: new Date(),
      contribution_amount: undefined,
      contribution_frequency: ContributionFrequency.MONTHLY,
      notes: "",
      contribution_plan_steps: [],
      statements: []
    }
  })

  const handleSubmit = async (data: CompanyPensionFormData) => {
    try {
      const memberId = parseInt(data.member_id)
      if (isNaN(memberId)) {
        toast.error("Error", { description: "Invalid member ID" })
        return
      }

      // Create a pension data object that matches what the API expects
      const pensionData = {
        type: PensionType.COMPANY as const,
        name: data.name,
        member_id: memberId,
        employer: data.employer,
        start_date: toISODateString(data.start_date),
        contribution_amount: data.contribution_amount !== undefined ? Number(data.contribution_amount) : null,
        contribution_frequency: data.contribution_frequency || null,
        notes: data.notes || "",
        contribution_plan_steps: data.contribution_plan_steps.map(step => ({
          amount: typeof step.amount === 'string' ? parseFloat(step.amount) : step.amount,
          frequency: step.frequency,
          start_date: toISODateString(step.start_date),
          end_date: step.end_date ? toISODateString(step.end_date) : null,
          note: step.note || null
        })),
        status: 'ACTIVE'
      }

      // If there are statements, use createCompanyPensionWithStatement
      if (data.statements && data.statements.length > 0) {
        const firstStatement = data.statements[0]
        await createCompanyPensionWithStatement(
          pensionData as unknown as Omit<CompanyPension, 'id' | 'current_value'>,
          {
            statement_date: toISODateString(firstStatement.statement_date),
            value: typeof firstStatement.value === 'string' ? parseFloat(firstStatement.value) : firstStatement.value,
            note: firstStatement.note || "",
            retirement_projections: firstStatement.retirement_projections && firstStatement.retirement_projections.length > 0
              ? firstStatement.retirement_projections.map(projection => ({
                  retirement_age: typeof projection.retirement_age === 'string' ? 
                    parseInt(projection.retirement_age) : projection.retirement_age,
                  monthly_payout: typeof projection.monthly_payout === 'string' ? 
                    parseFloat(projection.monthly_payout) : projection.monthly_payout,
                  total_capital: typeof projection.total_capital === 'string' ? 
                    parseFloat(projection.total_capital) : projection.total_capital
                }))
              : []
          }
        )
      } else {
        // If no statements, use regular createCompanyPension
        await createCompanyPension(pensionData as unknown as Omit<CompanyPension, 'id' | 'current_value'>)
      }

      toast.success("Success", { description: "Company pension created successfully" })
      router.push(getPensionListRoute())
      router.refresh()
    } catch (error) {
      console.error('Failed to create pension:', error)
      // Error is handled by the context
    }
  }

  return (
    <div className="container mx-auto py-10">
      <div className="flex flex-col space-y-4 sm:flex-row sm:justify-between sm:space-y-0 sm:items-center mb-6">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Create Company Pension Plan</h1>
          <p className="text-muted-foreground mt-2">
            Set up a new company pension plan. You&apos;ll need to provide employer information
            and set up your contribution plan.
          </p>
        </div>
        
        <div className="flex space-x-4">
          <Button
            type="button"
            variant="outline"
            onClick={() => router.back()}
          >
            Cancel
          </Button>
          <Button 
            type="submit"
            form="company-pension-form"
          >
            Create Pension
          </Button>
        </div>
      </div>

      {/* Form */}
      <Form {...form}>
        <form 
          id="company-pension-form"
          onSubmit={form.handleSubmit(handleSubmit)} 
        >
          <FormLayout>
            {/* Basic Information Section */}
            <FormSection
              title="Basic Information"
              description="Manage your company pension plan details and status"
              explanation={<BasicInformationExplanation />}
            >
              <BasicInformationCard form={form} />
            </FormSection>
            
            {/* Contribution Plan Section */}
            <FormSection
              title="Contribution Plan"
              description="Set up your contribution schedule"
              explanation={<ContributionPlanExplanation />}
            >
              <ContributionPlanCard form={form} />
            </FormSection>
            
            {/* Statements Section */}
            <FormSection
              title="Pension Statements"
              description="Track the value of your pension over time"
              explanation={<StatementsExplanation />}
            >
              <PensionStatementsCard form={form} />
            </FormSection>
          </FormLayout>
        </form>
      </Form>
    </div>
  )
}

// src/svelte-frontend/src/routes/pension/company/new/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { m } from '$lib/paraglide/messages.js';
	import { pensionApi } from '$lib/api/pension';
	import { toastStore } from '$lib/stores/toast.svelte';
	import { PensionType } from '$lib/types/pension';
	import type { ContributionStep, ContributionFrequency } from '$lib/types/pension';
	import { todayIsoDate } from '$lib/utils/date-only';
	import PageHeader from '$lib/components/ui/PageHeader.svelte';
	import Card from '$lib/components/ui/Card.svelte';
	import ContentSection from '$lib/components/ui/ContentSection.svelte';
	import Explanation from '$lib/components/ui/Explanation.svelte';
	import ExplanationAlert from '$lib/components/ui/ExplanationAlert.svelte';
	import ExplanationList from '$lib/components/ui/ExplanationList.svelte';
	import ExplanationListItem from '$lib/components/ui/ExplanationListItem.svelte';
	import BasicInformationCard from '$lib/components/pension/company/BasicInformationCard.svelte';
	import StatementsCard from '$lib/components/pension/company/StatementsCard.svelte';
	import ContributionPlanCard from '$lib/components/pension/ContributionPlanCard.svelte';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	interface RetirementProjectionFormData {
		id: number;
		retirement_age: number;
		monthly_payout: number;
		total_capital: number;
	}

	interface StatementFormData {
		id: number;
		pension_id: number;
		statement_date: string;
		value: number;
		note?: string;
		retirement_projections: RetirementProjectionFormData[];
	}

	// Form state
	let name = $state('');
	let employer = $state('');
	let startDate = $state(todayIsoDate());
	let contributionAmount = $state(0);
	let contributionFrequency = $state<ContributionFrequency | undefined>(undefined);
	let notes = $state('');
	let statements = $state<StatementFormData[]>([]);
	let contributionPlanSteps = $state<ContributionStep[]>([]);
	let errors = $state<Record<string, string>>({});
	let submitting = $state(false);

	let memberId = $derived(data.memberId);

	function validate(): boolean {
		const newErrors: Record<string, string> = {};
		if (!name.trim()) newErrors.name = m.company_pension_name_required();
		if (!startDate) newErrors.start_date = m.company_pension_start_date_required();
		if (!employer.trim()) newErrors.employer = m.company_pension_employer_required();
		errors = newErrors;
		return Object.keys(newErrors).length === 0;
	}

	async function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		if (!validate()) return;

		submitting = true;
		try {
			const pensionData = {
				type: PensionType.COMPANY,
				name: name.trim(),
				member_id: memberId,
				start_date: startDate,
				employer: employer.trim(),
				contribution_amount: contributionAmount || undefined,
				contribution_frequency: contributionFrequency || undefined,
				notes: notes.trim() || '',
				status: 'ACTIVE' as const,
				contribution_plan_steps: contributionPlanSteps.map((step) => ({
					amount: step.amount,
					frequency: step.frequency,
					start_date: step.start_date,
					end_date: step.end_date || undefined,
					note: step.note || ''
				}))
			};

			const created = await pensionApi.create<{ id: number }>(PensionType.COMPANY, pensionData);

			// POST each statement separately (company does NOT accept statements in create body)
			await Promise.all(
				statements
					.filter((s) => s.statement_date)
					.map((s) =>
						pensionApi.addCompanyPensionStatement(created.id, {
							statement_date: s.statement_date,
							value: s.value || 0,
							note: s.note || '',
							retirement_projections: s.retirement_projections.map((p) => ({
								retirement_age: p.retirement_age || 67,
								monthly_payout: p.monthly_payout || 0,
								total_capital: p.total_capital || 0
							}))
						})
					)
			);

			toastStore.success(m.company_pension_created());
			goto('/pension');
		} catch (error) {
			console.error('Error creating company pension:', error);
			toastStore.error(
				error instanceof Error ? error.message : m.company_pension_create_failed()
			);
		} finally {
			submitting = false;
		}
	}
</script>

<div class="space-y-6">
	<!-- Header -->
	<div class="flex flex-col space-y-4 sm:flex-row sm:justify-between sm:space-y-0 sm:items-center">
		<PageHeader
			title={m.company_pension_new_title()}
			description={m.company_pension_new_description()}
		/>
		<div class="flex space-x-4 shrink-0">
			<button
				type="button"
				onclick={() => history.back()}
				class="px-4 py-2 bg-secondary hover:bg-secondary/80 text-secondary-foreground rounded-lg text-sm font-medium transition-colors"
			>
				{m.cancel()}
			</button>
			<button
				type="submit"
				form="company-pension-form"
				disabled={submitting}
				class="px-4 py-2 bg-primary hover:bg-primary/90 text-primary-foreground rounded-lg text-sm font-medium transition-colors disabled:opacity-50"
			>
				{m.company_pension_create()}
			</button>
		</div>
	</div>

	<form id="company-pension-form" onsubmit={handleSubmit} class="space-y-8">
		<!-- Basic Information Section -->
		<ContentSection>
			{#snippet aside()}
				<Explanation>
					<p>{m.company_pension_explanation_intro()}</p>
					<ExplanationList>
						<ExplanationListItem><strong>{m.company_pension_name()}:</strong> {m.company_pension_explanation_name()}</ExplanationListItem>
						<ExplanationListItem><strong>{m.company_pension_employer()}:</strong> {m.company_pension_explanation_employer()}</ExplanationListItem>
						<ExplanationListItem><strong>{m.company_pension_start_date()}:</strong> {m.company_pension_explanation_start_date()}</ExplanationListItem>
						<ExplanationListItem><strong>{m.company_pension_contribution_amount()}:</strong> {m.company_pension_explanation_contribution()}</ExplanationListItem>
						<ExplanationListItem><strong>{m.company_pension_notes()}:</strong> {m.company_pension_explanation_notes()}</ExplanationListItem>
					</ExplanationList>
					<ExplanationAlert>
						{m.company_pension_explanation_alert()}
					</ExplanationAlert>
				</Explanation>
			{/snippet}
			<Card
				title={m.company_pension_basic_info()}
				description={m.company_pension_basic_info_description()}
			>
				<BasicInformationCard
					bind:name
					bind:employer
					bind:startDate
					bind:contributionAmount
					bind:contributionFrequency
					bind:notes
					{errors}
				/>
			</Card>
		</ContentSection>

		<!-- Statements Section -->
		<ContentSection>
			{#snippet aside()}
				<Explanation>
					<p>{m.company_pension_statements_explanation_intro()}</p>
					<ExplanationList>
						<ExplanationListItem><strong>{m.company_pension_value()}:</strong> {m.company_pension_statements_explanation_value()}</ExplanationListItem>
						<ExplanationListItem><strong>{m.company_pension_projections()}:</strong> {m.company_pension_statements_explanation_projections()}</ExplanationListItem>
					</ExplanationList>
					<ExplanationAlert>
						{m.company_pension_statements_explanation_alert()}
					</ExplanationAlert>
				</Explanation>
			{/snippet}
			<Card
				title={m.company_pension_statements()}
				description={m.company_pension_statements_description()}
			>
				<StatementsCard bind:statements />
			</Card>
		</ContentSection>

		<!-- Contribution Plan Section -->
		<ContentSection>
			{#snippet aside()}
				<Explanation>
					<ExplanationList>
						<ExplanationListItem><strong>{m.contribution_amount()}:</strong> {m.contribution_amount()}</ExplanationListItem>
						<ExplanationListItem><strong>{m.contribution_frequency()}:</strong> {m.contribution_frequency()}</ExplanationListItem>
						<ExplanationListItem><strong>{m.contribution_start_date()} / {m.contribution_end_date()}:</strong> {m.contribution_start_date()}</ExplanationListItem>
					</ExplanationList>
				</Explanation>
			{/snippet}
			<ContributionPlanCard bind:steps={contributionPlanSteps} />
		</ContentSection>
	</form>
</div>
