// src/svelte-frontend/src/lib/components/household/MemberForm.svelte
<script lang="ts">
	import type {
		HouseholdMember,
		HouseholdMemberFormData,
		ValidationErrors
	} from '$lib/types/household';
	import { validateMemberForm } from '$lib/types/household';

	let {
		member,
		onSubmit,
		onCancel
	}: {
		member?: HouseholdMember;
		onSubmit: (data: HouseholdMemberFormData) => void;
		onCancel: () => void;
	} = $props();

	let first_name = $state('');
	let last_name = $state('');
	let birthday = $state('');
	let retirement_age_planned = $state(67);
	let retirement_age_possible = $state(63);

	let errors = $state<ValidationErrors>({});
	let submitted = $state(false);

	// Reset form when member prop changes (edit mode)
	$effect(() => {
		if (member) {
			first_name = member.first_name;
			last_name = member.last_name;
			birthday = member.birthday;
			retirement_age_planned = member.retirement_age_planned;
			retirement_age_possible = member.retirement_age_possible;
		} else {
			first_name = '';
			last_name = '';
			birthday = '';
			retirement_age_planned = 67;
			retirement_age_possible = 63;
		}
		errors = {};
		submitted = false;
	});

	function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		submitted = true;

		const data: HouseholdMemberFormData = {
			first_name: first_name.trim(),
			last_name: last_name.trim(),
			birthday,
			retirement_age_planned: Number(retirement_age_planned),
			retirement_age_possible: Number(retirement_age_possible)
		};

		const validationErrors = validateMemberForm(data);
		errors = validationErrors;

		if (Object.keys(validationErrors).length === 0) {
			onSubmit(data);
		}
	}

	const inputClass =
		'w-full rounded-lg border border-input bg-background px-3 py-2 text-sm focus:border-ring focus:ring-1 focus:ring-ring outline-none transition-colors';
</script>

<form onsubmit={handleSubmit} class="space-y-4">
	<div class="grid grid-cols-2 gap-4">
		<div>
			<label for="first_name" class="block text-sm font-medium text-foreground/80 mb-1">First Name</label>
			<input id="first_name" type="text" bind:value={first_name} class={inputClass} />
			{#if submitted && errors.first_name}
				<p class="text-sm text-destructive mt-1">{errors.first_name}</p>
			{/if}
		</div>
		<div>
			<label for="last_name" class="block text-sm font-medium text-foreground/80 mb-1">Last Name</label>
			<input id="last_name" type="text" bind:value={last_name} class={inputClass} />
			{#if submitted && errors.last_name}
				<p class="text-sm text-destructive mt-1">{errors.last_name}</p>
			{/if}
		</div>
	</div>

	<div>
		<label for="birthday" class="block text-sm font-medium text-foreground/80 mb-1">Birthday</label>
		<input id="birthday" type="date" bind:value={birthday} class={inputClass} />
		{#if submitted && errors.birthday}
			<p class="text-sm text-destructive mt-1">{errors.birthday}</p>
		{/if}
	</div>

	<div class="grid grid-cols-2 gap-4">
		<div>
			<label for="retirement_planned" class="block text-sm font-medium text-foreground/80 mb-1"
				>Planned Retirement Age</label
			>
			<input
				id="retirement_planned"
				type="number"
				min="40"
				max="100"
				bind:value={retirement_age_planned}
				class={inputClass}
			/>
			{#if submitted && errors.retirement_age_planned}
				<p class="text-sm text-destructive mt-1">{errors.retirement_age_planned}</p>
			{/if}
		</div>
		<div>
			<label for="retirement_possible" class="block text-sm font-medium text-foreground/80 mb-1"
				>Earliest Retirement Age</label
			>
			<input
				id="retirement_possible"
				type="number"
				min="40"
				max="100"
				bind:value={retirement_age_possible}
				class={inputClass}
			/>
			{#if submitted && errors.retirement_age_possible}
				<p class="text-sm text-destructive mt-1">{errors.retirement_age_possible}</p>
			{/if}
		</div>
	</div>

	<div class="flex justify-end gap-2 pt-2">
		<button
			type="button"
			onclick={onCancel}
			class="px-4 py-2 bg-secondary hover:bg-secondary/80 text-secondary-foreground rounded-lg text-sm font-medium transition-colors"
		>
			Cancel
		</button>
		<button
			type="submit"
			class="px-4 py-2 bg-primary hover:bg-primary/90 text-primary-foreground rounded-lg text-sm font-medium transition-colors"
		>
			{member ? 'Save' : 'Add'}
		</button>
	</div>
</form>

// src/frontend/components/household/MemberForm.tsx
"use client"

import { useState, useEffect } from "react"
import { Button } from "@/frontend/components/ui/button"
import { Input } from "@/frontend/components/ui/input"
import { Label } from "@/frontend/components/ui/label"
import { HouseholdMember } from "@/frontend/types/household"
import { format } from "date-fns"

interface MemberFormProps {
  member?: HouseholdMember
  onSubmit: (data: Omit<HouseholdMember, "id">) => void
  onCancel: () => void
}

/**
 * Shared form component for adding and editing household members
 * 
 * A reusable form that handles:
 * - Input fields for all member properties
 * - Form state management
 * - Data validation
 * - Submit and cancel actions
 * 
 * Used by both AddMemberDialog and EditMemberDialog to maintain
 * consistency and reduce code duplication
 */

export function MemberForm({ member, onSubmit, onCancel }: MemberFormProps) {
  const [formData, setFormData] = useState({
    first_name: member?.first_name ?? "",
    last_name: member?.last_name ?? "",
    birthday: member ? format(member.birthday, 'yyyy-MM-dd') : "",
    retirement_age_planned: member?.retirement_age_planned.toString() ?? "",
    retirement_age_possible: member?.retirement_age_possible.toString() ?? "",
  })

  // Update form when member changes (for edit mode)
  useEffect(() => {
    if (member) {
      setFormData({
        first_name: member.first_name,
        last_name: member.last_name,
        birthday: format(member.birthday, 'yyyy-MM-dd'),
        retirement_age_planned: member.retirement_age_planned.toString(),
        retirement_age_possible: member.retirement_age_possible.toString(),
      })
    }
  }, [member])

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    onSubmit({
      first_name: formData.first_name,
      last_name: formData.last_name,
      birthday: new Date(formData.birthday),
      retirement_age_planned: parseInt(formData.retirement_age_planned),
      retirement_age_possible: parseInt(formData.retirement_age_possible),
    })
  }

  // TODO: Add form validation matching backend requirements
  // const validationSchema = z.object({ ... })

  // TODO: Add error handling for failed API calls
  // const [apiError, setApiError] = useState<string | null>(null)

  // TODO: Add loading state for submit action
  // const [isSubmitting, setIsSubmitting] = useState(false)

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-2">
          <Label htmlFor="first_name">First Name</Label>
          <Input
            id="first_name"
            value={formData.first_name}
            onChange={(e) => setFormData({ ...formData, first_name: e.target.value })}
            required
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="last_name">Last Name</Label>
          <Input
            id="last_name"
            value={formData.last_name}
            onChange={(e) => setFormData({ ...formData, last_name: e.target.value })}
            required
          />
        </div>
      </div>
      <div className="space-y-2">
        <Label htmlFor="birthday">Birthday</Label>
        <Input
          id="birthday"
          type="date"
          value={formData.birthday}
          onChange={(e) => setFormData({ ...formData, birthday: e.target.value })}
          required
        />
      </div>
      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-2">
          <Label htmlFor="retirement_age_planned">Planned Retirement Age</Label>
          <Input
            id="retirement_age_planned"
            type="number"
            min="40"
            max="100"
            value={formData.retirement_age_planned}
            onChange={(e) => setFormData({ ...formData, retirement_age_planned: e.target.value })}
            required
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="retirement_age_possible">Possible Retirement Age</Label>
          <Input
            id="retirement_age_possible"
            type="number"
            min="40"
            max="100"
            value={formData.retirement_age_possible}
            onChange={(e) => setFormData({ ...formData, retirement_age_possible: e.target.value })}
            required
          />
        </div>
      </div>
      <div className="flex justify-end space-x-2">
        <Button type="button" variant="outline" onClick={onCancel}>
          Cancel
        </Button>
        <Button type="submit">{member ? 'Save Changes' : 'Add Member'}</Button>
      </div>
    </form>
  )
}
