// src/svelte-frontend/src/lib/components/pension/ContributionHistoryTable.svelte
<script lang="ts">
	import { m } from '$lib/paraglide/messages.js';
	import { settingsStore } from '$lib/stores/settings.svelte';
	import { formatCurrency, formatDate } from '$lib/utils/format';
	import type { ExtraContribution } from '$lib/types/pension';

	let {
		contributions
	}: {
		contributions: ExtraContribution[];
	} = $props();

	let sorted = $derived(
		[...contributions].sort((a, b) =>
			new Date(b.contribution_date).getTime() - new Date(a.contribution_date).getTime()
		)
	);
</script>

<div>
	<h3 class="text-lg font-medium mb-4">{m.contribution_history_title()}</h3>

	<div class="border border-border rounded-lg overflow-hidden">
		<table class="w-full text-sm">
			<thead>
				<tr class="border-b border-border bg-muted/50">
					<th class="px-4 py-3 text-left font-medium text-muted-foreground">{m.contribution_history_date()}</th>
					<th class="px-4 py-3 text-left font-medium text-muted-foreground">{m.contribution_amount()}</th>
					<th class="px-4 py-3 text-left font-medium text-muted-foreground">{m.contribution_history_note()}</th>
				</tr>
			</thead>
			<tbody>
				{#each sorted as contribution (contribution.id)}
					<tr class="border-b border-border last:border-0">
						<td class="px-4 py-3">
							{formatDate(contribution.contribution_date, settingsStore.current.ui_locale)}
						</td>
						<td class="px-4 py-3">
							{formatCurrency(contribution.amount, settingsStore.current.number_locale, settingsStore.current.currency)}
						</td>
						<td class="px-4 py-3 text-muted-foreground">
							{contribution.note || '-'}
						</td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>
</div>

// src/frontend/components/pension/shared/ContributionHistoryTable.tsx
"use client"

import { useState, useEffect } from "react"
import { ExtraContribution } from "@/frontend/types/pension"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/frontend/components/ui/table"
import { formatCurrency, formatDate } from "@/frontend/lib/transforms"
import { useSettings } from "@/frontend/context/SettingsContext"

interface ContributionHistoryTableProps {
  contributions: ExtraContribution[]
}

interface FormattedContribution {
  id: number
  date: string
  amount: string
  note: string
}

export function ContributionHistoryTable({ contributions }: ContributionHistoryTableProps) {
  const { settings } = useSettings()
  const [formattedContributions, setFormattedContributions] = useState<FormattedContribution[]>([])
  
  // Format values client-side only after hydration
  useEffect(() => {
    const formatted = contributions.map(contribution => ({
      id: contribution.id,
      date: formatDate(contribution.contribution_date, { locale: settings.ui_locale }).formatted,
      amount: formatCurrency(contribution.amount, {
        locale: settings.number_locale,
        currency: settings.currency
      }).formatted,
      note: contribution.note || "-"
    }))
    
    // Sort contributions by date (newest first)
    const sortedContributions = [...formatted].sort((a, b) => {
      const dateA = new Date(contributions.find(c => c.id === a.id)?.contribution_date || 0)
      const dateB = new Date(contributions.find(c => c.id === b.id)?.contribution_date || 0)
      return dateB.getTime() - dateA.getTime()
    })
    
    setFormattedContributions(sortedContributions)
  }, [contributions, settings])
  
  return (
    <div>
      <h3 className="text-lg font-medium mb-4">Contribution History</h3>
      
      <div className="border rounded-md">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Date</TableHead>
              <TableHead>Amount</TableHead>
              <TableHead>Note</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {formattedContributions.map((contribution) => (
              <TableRow key={contribution.id}>
                <TableCell>{contribution.date}</TableCell>
                <TableCell>{contribution.amount}</TableCell>
                <TableCell>{contribution.note}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  )
}
