// src/frontend/components/pension/state/StatementsCard.tsx
"use client"

import { FormField, FormItem, FormLabel, FormControl, FormMessage } from "@/frontend/components/ui/form"
import { UseFormReturn, useFieldArray, Path } from "react-hook-form"
import { StatePensionFormData } from "@/frontend/types/pension-form"
import { Button } from "@/frontend/components/ui/button"
import { Plus, Trash2, ChevronDown, ChevronRight } from "lucide-react"
import { useState, useEffect } from "react"
import { safeNumberValue } from "@/frontend/lib/transforms"
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/frontend/components/ui/collapsible"
import { DateInput } from '@/frontend/components/ui/date-input'
import { useDateFormat } from "@/frontend/hooks/useDateFormat"
import { useDeleteStatePensionStatement } from '@/frontend/hooks/pension/useStatePensions'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/frontend/components/ui/alert-dialog"
import { Textarea } from "@/frontend/components/ui/textarea"
// Import standardized formatting components
import { FormattedDate } from "@/frontend/components/shared/formatting/FormattedDate"
// Import standardized input components
import { CurrencyInput } from "@/frontend/components/shared/inputs/CurrencyInput"

interface StatementsCardProps {
  form: UseFormReturn<StatePensionFormData>
  pensionId?: number
}

export function StatementsCard({ form, pensionId }: StatementsCardProps) {
  const { fields: statementFields, append: appendStatement, remove: removeStatement } = useFieldArray({
    control: form.control,
    name: "statements"
  })
  
  const { formatDate } = useDateFormat()
  const { mutate: deleteStatement } = useDeleteStatePensionStatement()
  
  const [expandedStatements, setExpandedStatements] = useState<{[key: number]: boolean}>({})
  const [formattedDates, setFormattedDates] = useState<{[key: number]: string}>({})
  const [statementToDelete, setStatementToDelete] = useState<{ index: number, date: string } | null>(null)

  // Get the index of the latest statement by date
  const getLatestStatementIndex = () => {
    if (statementFields.length === 0) return -1
    
    // Find the index of the statement with the most recent date
    let latestIndex = 0
    let latestDate = new Date(0) // Start with earliest possible date
    
    statementFields.forEach((field, index) => {
      const statementDate = form.getValues(`statements.${index}.statement_date`)
      if (statementDate && new Date(statementDate) > latestDate) {
        latestDate = new Date(statementDate)
        latestIndex = index
      }
    })
    
    return latestIndex
  }

  // Initialize dates when form data changes
  useEffect(() => {
    const statements = form.getValues("statements")
    if (statements) {
      // Initialize dates
      const newFormattedDates: {[key: number]: string} = {}
      
      statements.forEach((statement, index) => {
        if (statement.statement_date) {
          newFormattedDates[index] = formatDate(statement.statement_date)
        }
        
        // Ensure all form values are properly set with numbers
        form.setValue(`statements.${index}.current_monthly_amount` as Path<StatePensionFormData>, safeNumberValue(statement.current_monthly_amount) ?? 0)
        form.setValue(`statements.${index}.projected_monthly_amount` as Path<StatePensionFormData>, safeNumberValue(statement.projected_monthly_amount) ?? 0)
        form.setValue(`statements.${index}.current_value` as Path<StatePensionFormData>, safeNumberValue(statement.current_value) ?? 0)
      })
      
      setFormattedDates(newFormattedDates)
    }
  }, [form, formatDate])

  const handleAddStatement = () => {
    const statementDate = new Date()
    statementDate.setUTCHours(0, 0, 0, 0)
    
    appendStatement({
      statement_date: statementDate,
      current_monthly_amount: 0,
      projected_monthly_amount: 0,
      current_value: 0,
      note: ""
    })
    
    const newStatementIndex = statementFields.length
    setFormattedDates(prev => ({
      ...prev,
      [newStatementIndex]: formatDate(statementDate)
    }))
  }

  const toggleStatement = (index: number) => {
    setExpandedStatements(prev => ({
      ...prev,
      [index]: !prev[index]
    }))
  }

  const handleRemoveStatement = async (index: number) => {
    const statements = form.getValues("statements")
    const statement = statements?.[index]

    if (pensionId && statement?.id) {
      try {
        await deleteStatement({ pensionId, statementId: statement.id })
      } catch (error) {
        console.error('Error deleting statement:', error)
        return
      }
    }

    removeStatement(index)
    setStatementToDelete(null)
  }

  const confirmDeleteStatement = (index: number) => {
    const date = formattedDates[index] || 'unknown date'
    setStatementToDelete({ index, date })
  }

  const renderStatementForm = (index: number) => (
    <div className="space-y-4">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <FormField
          control={form.control}
          name={`statements.${index}.statement_date`}
          render={({ field }) => (
            <FormItem>
              <FormLabel>Statement Date</FormLabel>
              <FormControl>
                <DateInput field={field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name={`statements.${index}.current_value`}
          render={({ field }) => (
            <FormItem>
              <FormLabel>Current Value</FormLabel>
              <FormControl>
                <CurrencyInput
                  value={field.value ?? undefined}
                  onChange={field.onChange}
                  onBlur={field.onBlur}
                  placeholder="0.00"
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <FormField
          control={form.control}
          name={`statements.${index}.current_monthly_amount`}
          render={({ field }) => (
            <FormItem>
              <FormLabel>Current Monthly Amount</FormLabel>
              <FormControl>
                <CurrencyInput
                  value={field.value ?? undefined}
                  onChange={field.onChange}
                  onBlur={field.onBlur}
                  placeholder="0.00"
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name={`statements.${index}.projected_monthly_amount`}
          render={({ field }) => (
            <FormItem>
              <FormLabel>Projected Monthly Amount</FormLabel>
              <FormControl>
                <CurrencyInput
                  value={field.value ?? undefined}
                  onChange={field.onChange}
                  onBlur={field.onBlur}
                  placeholder="0.00"
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
      </div>

      <div className="grid grid-cols-1 gap-4">
        <FormField
          control={form.control}
          name={`statements.${index}.note`}
          render={({ field }) => (
            <FormItem>
              <FormLabel>Notes (Optional)</FormLabel>
              <FormControl>
                <Textarea 
                  {...field} 
                  placeholder="Add any notes about this statement"
                  className="resize-none h-24"
                />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
      </div>
    </div>
  )

  // Render previous statements as collapsible items
  const renderPreviousStatements = () => {
    if (statementFields.length <= 1) return null;
    
    const latestIndex = getLatestStatementIndex();
    
    // Get all statements except the latest one by date
    const previousStatements = statementFields.filter((_, index) => index !== latestIndex);
    
    // Sort previous statements by date (latest on top)
    const sortedPreviousStatements = [...previousStatements].sort((a, b) => {
      const indexA = statementFields.findIndex(field => field.id === a.id);
      const indexB = statementFields.findIndex(field => field.id === b.id);
      const dateA = new Date(form.getValues(`statements.${indexA}.statement_date`)).getTime();
      const dateB = new Date(form.getValues(`statements.${indexB}.statement_date`)).getTime();
      return dateB - dateA; // Sort in descending order (latest first)
    });
    
    return (
      <div className="space-y-4">
        <h3 className="text-lg font-medium">Previous Statements</h3>
        {sortedPreviousStatements.map((field) => {
          // Get the original index to access the correct data
          const originalIndex = statementFields.findIndex(f => f.id === field.id);
          
          return (
            <Collapsible
              key={field.id}
              open={expandedStatements[originalIndex]}
              onOpenChange={() => toggleStatement(originalIndex)}
              className="border rounded-md overflow-hidden"
            >
              <div className="p-4 flex justify-between items-center bg-muted/30">
                <CollapsibleTrigger asChild>
                  <Button 
                    type="button"
                    variant="ghost" 
                    className="p-0 h-auto flex items-center gap-2 hover:bg-transparent"
                  >
                    {expandedStatements[originalIndex] ? (
                      <ChevronDown className="h-4 w-4" />
                    ) : (
                      <ChevronRight className="h-4 w-4" />
                    )}
                    <h4 className="font-medium">
                      Statement from <FormattedDate value={form.getValues(`statements.${originalIndex}.statement_date`)} />
                    </h4>
                  </Button>
                </CollapsibleTrigger>
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  onClick={() => confirmDeleteStatement(originalIndex)}
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              </div>
              <CollapsibleContent className="p-4">
                {renderStatementForm(originalIndex)}
              </CollapsibleContent>
            </Collapsible>
          );
        })}
      </div>
    );
  }

  // Render the latest statement form (the one with the most recent date)
  const renderLatestStatementForm = () => {
    if (statementFields.length === 0) return null;
    
    const latestIndex = getLatestStatementIndex();
    
    // Get the date string for display
    const statementDate = form.getValues(`statements.${latestIndex}.statement_date`);
    const formattedDate = statementDate ? <FormattedDate value={statementDate} /> : "latest statement";
    
    return (
      <div className="space-y-6">
        <h3 className="text-lg font-medium">Latest Statement ({formattedDate})</h3>
        <div className="p-4 border rounded-md">
          {renderStatementForm(latestIndex)}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Add Statement Button - Shown at top when statements exist */}
      {statementFields.length > 0 && (
        <Button
          type="button"
          variant="outline"
          className="w-full border-dashed text-center py-6 text-sm text-muted-foreground border-2 rounded-lg"
          onClick={handleAddStatement}
        >
          <Plus className="h-4 w-4 mr-2" />
          Add a new statement
        </Button>
      )}

      {/* Latest Statement Form */}
      {renderLatestStatementForm()}

      {/* Previous Statements */}
      {renderPreviousStatements()}

      {/* Empty State */}
      {statementFields.length === 0 && (
        <Button
          type="button"
          variant="outline"
          className="w-full border-dashed text-center py-6 text-sm text-muted-foreground border-2 rounded-lg"
          onClick={handleAddStatement}
        >
          <Plus className="h-4 w-4 mr-2" />
          No statements added yet. Click to add your first statement.
        </Button>
      )}

      {/* Delete Confirmation Dialog */}
      <AlertDialog
        open={!!statementToDelete}
        onOpenChange={() => setStatementToDelete(null)}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Statement</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete the statement from {statementToDelete?.date}?
              This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => {
                if (statementToDelete) {
                  handleRemoveStatement(statementToDelete.index)
                }
              }}
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}

// src/svelte-frontend/src/lib/components/pension/state/StatementsCard.svelte
<script lang="ts">
	import { m } from '$lib/paraglide/messages.js';
	import { Plus, Trash2, ChevronDown, ChevronRight } from '@lucide/svelte';
	import { pensionApi } from '$lib/api/pension';
	import { toISODate } from '$lib/utils/format';
	import CurrencyInput from '$lib/components/ui/CurrencyInput.svelte';
	import FormattedDate from '$lib/components/ui/FormattedDate.svelte';
	import type { StatePensionStatement } from '$lib/types/pension';

	interface StatementFormData {
		id: number;
		pension_id: number;
		statement_date: string;
		current_monthly_amount: number;
		projected_monthly_amount: number;
		current_value: number;
		note?: string;
	}

	let {
		statements = $bindable([]),
		pensionId
	}: {
		statements: StatementFormData[];
		pensionId?: number;
	} = $props();

	let expandedStatements = $state<Record<number, boolean>>({});
	let deletingIndex = $state<number | null>(null);
	let deleteDialogEl: HTMLDialogElement;

	$effect(() => {
		if (!deleteDialogEl) return;
		if (deletingIndex !== null && !deleteDialogEl.open) deleteDialogEl.showModal();
		else if (deletingIndex === null && deleteDialogEl.open) deleteDialogEl.close();
	});

	// Find the index of the latest statement by date
	function getLatestStatementIndex(): number {
		if (statements.length === 0) return -1;
		let latestIndex = 0;
		let latestDate = new Date(0);
		statements.forEach((s, i) => {
			const d = new Date(s.statement_date);
			if (d > latestDate) {
				latestDate = d;
				latestIndex = i;
			}
		});
		return latestIndex;
	}

	// Get previous statements sorted by date (newest first), excluding the latest
	let latestIndex = $derived(getLatestStatementIndex());
	let previousStatements = $derived(
		statements
			.map((s, i) => ({ statement: s, originalIndex: i }))
			.filter((_, i) => i !== latestIndex)
			.sort((a, b) => new Date(b.statement.statement_date).getTime() - new Date(a.statement.statement_date).getTime())
	);

	function handleAddStatement() {
		const now = new Date();
		now.setUTCHours(0, 0, 0, 0);
		statements = [
			...statements,
			{
				id: 0,
				pension_id: pensionId ?? 0,
				statement_date: toISODate(now),
				current_monthly_amount: 0,
				projected_monthly_amount: 0,
				current_value: 0,
				note: ''
			}
		];
	}

	async function handleRemoveStatement(index: number) {
		const statement = statements[index];
		if (pensionId && statement?.id) {
			try {
				await pensionApi.deleteStatePensionStatement(pensionId, statement.id);
			} catch (error) {
				console.error('Error deleting statement:', error);
				return;
			}
		}
		statements = statements.filter((_, i) => i !== index);
		deletingIndex = null;
	}

	function toggleStatement(index: number) {
		expandedStatements = { ...expandedStatements, [index]: !expandedStatements[index] };
	}
</script>

<div class="space-y-6">
	<!-- Add Statement Button (shown when statements exist) -->
	{#if statements.length > 0}
		<button
			type="button"
			onclick={handleAddStatement}
			class="flex items-center justify-center w-full border-2 border-dashed border-border rounded-lg
				py-6 text-sm text-muted-foreground hover:border-primary/50 hover:bg-accent/30 transition-colors cursor-pointer"
		>
			<Plus class="h-4 w-4 mr-2" />
			{m.state_pension_add_statement()}
		</button>
	{/if}

	<!-- Latest Statement Form -->
	{#if statements.length > 0}
		{@const li = latestIndex}
		<div class="space-y-4">
			<h3 class="text-lg font-medium">
				{m.state_pension_latest_statement()} (<FormattedDate value={statements[li].statement_date} />)
			</h3>
			<div class="p-4 border border-border rounded-lg">
				{@render statementForm(li)}
			</div>
		</div>
	{/if}

	<!-- Previous Statements (collapsible) -->
	{#if previousStatements.length > 0}
		<div class="space-y-4">
			<h3 class="text-lg font-medium">{m.state_pension_previous_statements()}</h3>
			{#each previousStatements as { originalIndex } (originalIndex)}
				<div class="border border-border rounded-lg overflow-hidden">
					<div class="p-4 flex justify-between items-center bg-muted/30">
						<button
							type="button"
							onclick={() => toggleStatement(originalIndex)}
							class="flex items-center gap-2 text-sm font-medium hover:text-foreground/80"
						>
							{#if expandedStatements[originalIndex]}
								<ChevronDown class="h-4 w-4" />
							{:else}
								<ChevronRight class="h-4 w-4" />
							{/if}
							<span>
								Statement from <FormattedDate value={statements[originalIndex].statement_date} />
							</span>
						</button>
						<button
							type="button"
							onclick={() => { deletingIndex = originalIndex; }}
							class="p-1 text-muted-foreground hover:text-destructive transition-colors"
						>
							<Trash2 class="h-4 w-4" />
						</button>
					</div>
					{#if expandedStatements[originalIndex]}
						<div class="p-4">
							{@render statementForm(originalIndex)}
						</div>
					{/if}
				</div>
			{/each}
		</div>
	{/if}

	<!-- Empty State -->
	{#if statements.length === 0}
		<button
			type="button"
			onclick={handleAddStatement}
			class="flex items-center justify-center w-full border-2 border-dashed border-border rounded-lg
				py-6 text-sm text-muted-foreground hover:border-primary/50 hover:bg-accent/30 transition-colors cursor-pointer"
		>
			<Plus class="h-4 w-4 mr-2" />
			{m.state_pension_add_first_statement()}
		</button>
	{/if}
</div>

<!-- Delete Confirmation Dialog -->
<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
<dialog
	bind:this={deleteDialogEl}
	onclick={(e) => { if (e.target === deleteDialogEl) deletingIndex = null; }}
	onclose={() => deletingIndex = null}
	class="rounded-xl p-0 max-w-sm shadow-xl border border-border"
>
	<div class="p-6">
		<h2 class="text-lg font-semibold">{m.state_pension_delete_statement_title()}</h2>
		<p class="mt-2 text-sm text-muted-foreground">{m.state_pension_delete_statement_confirm()}</p>
		<div class="mt-4 flex justify-end gap-2">
			<button
				onclick={() => deletingIndex = null}
				class="px-4 py-2 bg-secondary hover:bg-secondary/80 text-secondary-foreground rounded-lg text-sm font-medium transition-colors"
			>
				{m.cancel()}
			</button>
			<button
				onclick={() => { if (deletingIndex !== null) handleRemoveStatement(deletingIndex); }}
				class="px-4 py-2 bg-destructive hover:bg-destructive/90 text-destructive-foreground rounded-lg text-sm font-medium transition-colors"
			>
				{m.delete_action()}
			</button>
		</div>
	</div>
</dialog>

{#snippet statementForm(index: number)}
	<div class="space-y-4">
		<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
			<div>
				<label class="block text-sm font-medium mb-1.5">
					{m.state_pension_statement_date()}
					<input
						type="date"
						bind:value={statements[index].statement_date}
						class="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm"
					/>
				</label>
			</div>
			<div>
				<label class="block text-sm font-medium mb-1.5">
					{m.state_pension_current_value()}
				</label>
				<CurrencyInput bind:value={statements[index].current_value} min={0} />
			</div>
		</div>

		<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
			<div>
				<label class="block text-sm font-medium mb-1.5">
					{m.state_pension_current_monthly()}
				</label>
				<CurrencyInput bind:value={statements[index].current_monthly_amount} min={0} />
			</div>
			<div>
				<label class="block text-sm font-medium mb-1.5">
					{m.state_pension_projected_monthly()}
				</label>
				<CurrencyInput bind:value={statements[index].projected_monthly_amount} min={0} />
			</div>
		</div>

		<div>
			<label class="block text-sm font-medium mb-1.5">
				{m.state_pension_statement_note()}
				<textarea
					bind:value={statements[index].note}
					placeholder={m.state_pension_statement_note_placeholder()}
					rows="3"
					class="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm resize-none"
				></textarea>
			</label>
		</div>
	</div>
{/snippet}
