// src/frontend/components/settings/ScenarioRatesGrid.tsx
"use client"

import { RateInput } from "@/frontend/components/ui/rate-input"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/frontend/components/ui/card"
import { Label } from "@/frontend/components/ui/label"
import { FrontendSettings } from "@/frontend/types/settings"
import { TrendingDown, ArrowRight, TrendingUp } from "lucide-react"
import { Separator } from "@/frontend/components/ui/separator"

interface ScenarioRatesGridProps {
  settings: FrontendSettings;
  onUpdate: (key: keyof FrontendSettings, value: number) => void;
  isLoading: boolean;
  rateErrors: { [key: string]: string };
}

export function ScenarioRatesGrid({ settings, onUpdate, isLoading, rateErrors }: ScenarioRatesGridProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Growth Rate Scenarios</CardTitle>
        <CardDescription>Configure annual growth rates for different pension types</CardDescription>
      </CardHeader>
      <CardContent className="space-y-8">
        {/* Inflation Rate (standalone) */}
        <div className="grid grid-cols-4 gap-6">
          <div className="flex items-center">
            <Label className="text-base font-semibold">Inflation Rate</Label>
          </div>
          <div>
            <RateInput
              label="Inflation Rate"
              value={settings.inflation_rate}
              onChange={(value) => onUpdate('inflation_rate', value)}
              min={0}
              max={15}
              step={0.1}
              disabled={isLoading}
              error={rateErrors.inflation_rate}
              hideLabel
            />
          </div>
        </div>

        <Separator className="my-6" />

        {/* Scenario Rates Grid */}
        <div className="space-y-6">
          {/* Header row */}
          <div className="grid grid-cols-4 gap-6">
            <div className="col-span-1"></div>
            <div className="col-span-3 grid grid-cols-3 gap-6">
              <div className="flex flex-col items-center">
                <TrendingDown className="h-5 w-5 mb-2 text-yellow-500" />
                <span className="text-sm font-medium">Pessimistic</span>
              </div>
              <div className="flex flex-col items-center">
                <ArrowRight className="h-5 w-5 mb-2 text-blue-500" />
                <span className="text-sm font-medium">Realistic</span>
              </div>
              <div className="flex flex-col items-center">
                <TrendingUp className="h-5 w-5 mb-2 text-green-500" />
                <span className="text-sm font-medium">Optimistic</span>
              </div>
            </div>
          </div>
          
          {/* ETF Pension row */}
          <div className="grid grid-cols-4 gap-6">
            <div className="flex items-center">
              <Label className="text-base">ETF Pension</Label>
            </div>
            <div className="col-span-3 grid grid-cols-3 gap-6">
              <RateInput
                label="ETF Pension Pessimistic Rate"
                value={settings.projection_pessimistic_rate}
                onChange={(value) => onUpdate('projection_pessimistic_rate', value)}
                min={0}
                max={15}
                step={0.1}
                disabled={isLoading}
                error={rateErrors.projection_pessimistic_rate}
                hideLabel
              />
              <RateInput
                label="ETF Pension Realistic Rate"
                value={settings.projection_realistic_rate}
                onChange={(value) => onUpdate('projection_realistic_rate', value)}
                min={0}
                max={15}
                step={0.1}
                disabled={isLoading}
                error={rateErrors.projection_realistic_rate}
                hideLabel
              />
              <RateInput
                label="ETF Pension Optimistic Rate"
                value={settings.projection_optimistic_rate}
                onChange={(value) => onUpdate('projection_optimistic_rate', value)}
                min={0}
                max={15}
                step={0.1}
                disabled={isLoading}
                error={rateErrors.projection_optimistic_rate}
                hideLabel
              />
            </div>
          </div>
          
          {/* State Pension row */}
          <div className="grid grid-cols-4 gap-6">
            <div className="flex items-center">
              <Label className="text-base">State Pension</Label>
            </div>
            <div className="col-span-3 grid grid-cols-3 gap-6">
              <RateInput
                label="State Pension Pessimistic Rate"
                value={settings.state_pension_pessimistic_rate}
                onChange={(value) => onUpdate('state_pension_pessimistic_rate', value)}
                min={0}
                max={15}
                step={0.1}
                disabled={isLoading}
                error={rateErrors.state_pension_pessimistic_rate}
                hideLabel
              />
              <RateInput
                label="State Pension Realistic Rate"
                value={settings.state_pension_realistic_rate}
                onChange={(value) => onUpdate('state_pension_realistic_rate', value)}
                min={0}
                max={15}
                step={0.1}
                disabled={isLoading}
                error={rateErrors.state_pension_realistic_rate}
                hideLabel
              />
              <RateInput
                label="State Pension Optimistic Rate"
                value={settings.state_pension_optimistic_rate}
                onChange={(value) => onUpdate('state_pension_optimistic_rate', value)}
                min={0}
                max={15}
                step={0.1}
                disabled={isLoading}
                error={rateErrors.state_pension_optimistic_rate}
                hideLabel
              />
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

// src/svelte-frontend/src/lib/components/settings/ScenarioRatesGrid.svelte
<script lang="ts">
	import Card from '$lib/components/ui/Card.svelte';
	import RateInput from './RateInput.svelte';
	import type { FrontendSettings } from '$lib/types/settings';

	let {
		settings,
		onUpdate,
		disabled = false,
		rateErrors = {}
	}: {
		settings: FrontendSettings;
		onUpdate: (key: keyof FrontendSettings, value: number) => void;
		disabled?: boolean;
		rateErrors?: Record<string, string>;
	} = $props();

	const etfKeys = [
		'projection_pessimistic_rate',
		'projection_realistic_rate',
		'projection_optimistic_rate'
	] as const;
	const stateKeys = [
		'state_pension_pessimistic_rate',
		'state_pension_realistic_rate',
		'state_pension_optimistic_rate'
	] as const;
</script>

<Card
	title="Growth Rate Scenarios"
	description="Configure annual growth rates for different pension types"
>
	<div class="space-y-8">
		<!-- Inflation Rate -->
		<div class="grid grid-cols-4 gap-6">
			<div class="flex items-center">
				<span class="text-base font-semibold">Inflation Rate</span>
			</div>
			<div>
				<RateInput
					value={settings.inflation_rate}
					onChange={(v) => onUpdate('inflation_rate', v)}
					{disabled}
				/>
				{#if rateErrors.inflation_rate}
					<p class="text-xs text-destructive mt-1">{rateErrors.inflation_rate}</p>
				{/if}
			</div>
		</div>

		<hr class="border-border" />

		<!-- Scenario Rates Grid -->
		<div class="space-y-6">
			<!-- Header row -->
			<div class="grid grid-cols-4 gap-6">
				<div></div>
				<div class="grid grid-cols-3 gap-6 col-span-3">
					<div class="flex flex-col items-center w-24">
						<svg
							class="w-5 h-5 mb-2 text-yellow-500"
							fill="none"
							stroke="currentColor"
							viewBox="0 0 24 24"
							stroke-width="1.5"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								d="M2.25 6L9 12.75l4.286-4.286a11.948 11.948 0 014.306 6.43l.776 2.898M2.25 6l3 3m0-3h3"
							/>
						</svg>
						<span class="text-sm font-medium">Pessimistic</span>
					</div>
					<div class="flex flex-col items-center w-24">
						<svg
							class="w-5 h-5 mb-2 text-blue-500"
							fill="none"
							stroke="currentColor"
							viewBox="0 0 24 24"
							stroke-width="1.5"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3"
							/>
						</svg>
						<span class="text-sm font-medium">Realistic</span>
					</div>
					<div class="flex flex-col items-center w-24">
						<svg
							class="w-5 h-5 mb-2 text-green-500"
							fill="none"
							stroke="currentColor"
							viewBox="0 0 24 24"
							stroke-width="1.5"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								d="M2.25 18L9 11.25l4.306 4.307a11.95 11.95 0 015.814-5.519l2.74-1.22M21.75 18V12m0 0h-6"
							/>
						</svg>
						<span class="text-sm font-medium">Optimistic</span>
					</div>
				</div>
			</div>

			<!-- ETF Pension row -->
			<div class="grid grid-cols-4 gap-6">
				<div class="flex items-center">
					<span class="text-base">ETF Pension</span>
				</div>
				<div class="grid grid-cols-3 gap-6 col-span-3">
					{#each etfKeys as key}
						<div>
							<RateInput
								value={settings[key]}
								onChange={(v) => onUpdate(key, v)}
								{disabled}
							/>
							{#if rateErrors[key]}
								<p class="text-xs text-destructive mt-1">{rateErrors[key]}</p>
							{/if}
						</div>
					{/each}
				</div>
			</div>

			<!-- State Pension row -->
			<div class="grid grid-cols-4 gap-6">
				<div class="flex items-center">
					<span class="text-base">State Pension</span>
				</div>
				<div class="grid grid-cols-3 gap-6 col-span-3">
					{#each stateKeys as key}
						<div>
							<RateInput
								value={settings[key]}
								onChange={(v) => onUpdate(key, v)}
								{disabled}
							/>
							{#if rateErrors[key]}
								<p class="text-xs text-destructive mt-1">{rateErrors[key]}</p>
							{/if}
						</div>
					{/each}
				</div>
			</div>
		</div>
	</div>
</Card>
