// app/pension/insurance/[id]/edit/page.tsx
"use client"

import { useForm } from "react-hook-form"
import { useRouter } from "next/navigation"
import { Form } from "@/frontend/components/ui/form"
import { Button } from "@/frontend/components/ui/button"
import { InsurancePensionFormData } from "@/frontend/types/pension-form"
import { PensionType, InsurancePension } from "@/frontend/types/pension"
import { usePension } from "@/frontend/context/pension"
import { toast } from "sonner"
import { use } from "react"
import { getPensionListRoute } from "@/frontend/lib/routes"
import { ErrorBoundary } from "@/frontend/components/shared/ErrorBoundary"
import { BasicInformationCard } from "@/frontend/components/pension/insurance/BasicInformationCard"
import { ContributionDetailsCard } from "@/frontend/components/pension/insurance/ContributionDetailsCard"
import { StatementsCard } from "@/frontend/components/pension/insurance/StatementsCard"
import { BasicInformationExplanation } from "@/frontend/components/pension/insurance/explanations/BasicInformationExplanation"
import { ContributionDetailsExplanation } from "@/frontend/components/pension/insurance/explanations/ContributionDetailsExplanation"
import { StatementsExplanation } from "@/frontend/components/pension/insurance/explanations/StatementsExplanation"
import { zodResolver } from "@hookform/resolvers/zod"
import { insurancePensionSchema } from "@/frontend/lib/validations/pension"
import { usePensionData } from "@/frontend/lib/hooks/usePensionData"
import { LoadingState } from "@/frontend/components/shared/LoadingState"
import { Alert, AlertDescription, AlertTitle } from "@/frontend/components/ui/alert"
import { useFormReset } from "@/frontend/lib/hooks/useFormReset"
import { insurancePensionToForm } from "@/frontend/lib/transformers/insurancePensionTransformers"
import { toISODateString } from "@/frontend/lib/dateUtils"
import { FormLayout } from "@/frontend/components/shared/FormLayout"
import { FormSection } from "@/frontend/components/shared/FormSection"
import { PauseConfirmationDialog } from "@/frontend/components/pension/shared/dialogs/PauseConfirmationDialog"
import { ResumeDateDialog } from "@/frontend/components/pension/shared/dialogs/ResumeDateDialog"
import { useState } from "react"
import { PensionStatusActions } from "@/frontend/components/pension/shared/PensionStatusActions"

interface EditInsurancePensionPageProps {
  params: Promise<{
    id: string
  }>
}

const defaultValues: InsurancePensionFormData = {
  type: PensionType.INSURANCE,
  name: "",
  member_id: "",
  notes: "",
  provider: "",
  contract_number: "",
  start_date: new Date(),
  guaranteed_interest: undefined,
  expected_return: undefined,
  contribution_plan_steps: [],
  statements: []
}

export default function EditInsurancePensionPage({ params }: EditInsurancePensionPageProps) {
  const router = useRouter()
  const { updateInsurancePensionWithStatement, createInsurancePensionStatement, updatePensionStatus } = usePension()
  const resolvedParams = use(params)
  const pensionId = parseInt(resolvedParams.id)
  const { data: pension, isLoading, error } = usePensionData<InsurancePension>(pensionId, PensionType.INSURANCE)
  const [showPauseDialog, setShowPauseDialog] = useState(false)
  const [showResumeDialog, setShowResumeDialog] = useState(false)

  const form = useForm<InsurancePensionFormData>({
    resolver: zodResolver(insurancePensionSchema),
    defaultValues,
    mode: "onChange"
  })

  // Use the form reset hook
  useFormReset({
    data: pension,
    form,
    apiToForm: insurancePensionToForm,
    defaultValues
  })

  const handleSubmit = async (data: InsurancePensionFormData) => {
    try {
      // Format pension data
      const pensionData = {
        ...data,
        type: PensionType.INSURANCE,
        member_id: typeof data.member_id === 'string' ? parseInt(data.member_id) : data.member_id,
        start_date: toISODateString(data.start_date),
        notes: data.notes || ""
      }

      // Extract and format statements
      const statements = data.statements?.map(statement => ({
        id: statement.id,
        statement_date: toISODateString(statement.statement_date),
        value: typeof statement.value === 'string' ? parseFloat(statement.value) : statement.value,
        total_contributions: typeof statement.total_contributions === 'string' ? 
          parseFloat(statement.total_contributions) : statement.total_contributions,
        total_benefits: typeof statement.total_benefits === 'string' ? 
          parseFloat(statement.total_benefits) : statement.total_benefits,
        costs_amount: typeof statement.costs_amount === 'string' ? 
          parseFloat(statement.costs_amount) : statement.costs_amount,
        costs_percentage: typeof statement.costs_percentage === 'string' ? 
          parseFloat(statement.costs_percentage) : statement.costs_percentage,
        note: statement.note || "",
        projections: statement.projections?.map(proj => ({
          id: proj.id,
          scenario_type: proj.scenario_type,
          return_rate: typeof proj.return_rate === 'string' ? 
            parseFloat(proj.return_rate) : proj.return_rate,
          value_at_retirement: typeof proj.value_at_retirement === 'string' ? 
            parseFloat(proj.value_at_retirement) : proj.value_at_retirement,
          monthly_payout: typeof proj.monthly_payout === 'string' ? 
            parseFloat(proj.monthly_payout) : proj.monthly_payout
        }))
      })) || []

      // Separate existing and new statements
      const existingStatements = statements.filter(statement => typeof statement.id === 'number')
      const newStatements = statements.filter(statement => !statement.id)

      // First update the pension and existing statements
      if (existingStatements.length > 0) {
        await updateInsurancePensionWithStatement(
          pensionId,
          pensionData as unknown as Omit<InsurancePension, 'id' | 'current_value'>,
          existingStatements as Array<{
            id: number;
            statement_date: string;
            value: number;
            total_contributions: number;
            total_benefits: number;
            costs_amount: number;
            costs_percentage: number;
            note?: string;
            projections?: Array<{
              id?: number;
              scenario_type: 'with_contributions' | 'without_contributions';
              return_rate: number;
              value_at_retirement: number;
              monthly_payout: number;
            }>;
          }>
        )
      } else {
        // If no existing statements, just update the pension data
        await updateInsurancePensionWithStatement(
          pensionId,
          pensionData as unknown as Omit<InsurancePension, 'id' | 'current_value'>,
          []
        )
      }

      // Then create any new statements
      for (const statement of newStatements) {
        await createInsurancePensionStatement(
          pensionId,
          {
            statement_date: statement.statement_date,
            value: statement.value,
            total_contributions: statement.total_contributions,
            total_benefits: statement.total_benefits,
            costs_amount: statement.costs_amount,
            costs_percentage: statement.costs_percentage,
            note: statement.note,
            projections: statement.projections
          }
        )
      }

      toast.success("Success", { description: "Insurance pension updated successfully" })
      router.push(getPensionListRoute())
      router.refresh()
    } catch (error) {
      console.error('Failed to update pension:', error)
      if (error instanceof Error) {
        toast.error('Error', {
          description: error.message || 'Failed to update insurance pension'
        })
      } else {
        toast.error('Error', {
          description: 'Failed to update insurance pension'
        })
      }
    }
  }

  const handlePauseConfirm = async (pauseDate: Date) => {
    if (!pension) return

    try {
      await updatePensionStatus(pensionId, {
        status: 'PAUSED',
        paused_at: pauseDate.toISOString(),
      })
      setShowPauseDialog(false)
    } catch (error) {
      console.error('Error updating pension status:', error)
      toast.error('Error', {
        description: 'Failed to update pension status'
      })
    }
  }

  const handleResumeConfirm = async (resumeDate: Date) => {
    if (!pension) return

    try {
      await updatePensionStatus(pensionId, {
        status: 'ACTIVE',
        resume_at: resumeDate.toISOString(),
      })
      setShowResumeDialog(false)
    } catch (error) {
      console.error('Error updating pension status:', error)
      toast.error('Error', {
        description: 'Failed to update pension status'
      })
    }
  }

  return (
    <ErrorBoundary>
      <div className="container py-10">
        {/* Page Header */}
        <div className="flex flex-col space-y-4 sm:flex-row sm:justify-between sm:items-center mb-6">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Edit Insurance Pension Plan</h1>
            <p className="text-muted-foreground mt-2">
              Update your insurance pension plan details.
            </p>
          </div>
          <div className="flex space-x-4">
            <Button
              type="button"
              variant="outline"
              onClick={() => router.back()}
            >
              Cancel
            </Button>
            <Button type="submit" form="insurance-pension-form">
              Save Changes
            </Button>
          </div>
        </div>

        {isLoading ? (
          <LoadingState message="Loading pension details..." />
        ) : error ? (
          <Alert variant="destructive">
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>{error.message}</AlertDescription>
          </Alert>
        ) : !pension ? (
          <Alert variant="destructive">
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>Pension not found</AlertDescription>
          </Alert>
        ) : pension.type !== PensionType.INSURANCE ? (
          <Alert variant="destructive">
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>Invalid pension type</AlertDescription>
          </Alert>
        ) : (
          <Form {...form}>
            <form id="insurance-pension-form" onSubmit={form.handleSubmit(handleSubmit, (errors) => {
              console.error('Form validation errors:', errors)
              toast.error('Error', {
                description: 'Please fix the validation errors before submitting'
              })
            })}>
              <FormLayout>
                {/* Basic Information Section */}
                <FormSection
                  title="Basic Information"
                  description="Enter the basic details of your insurance pension plan"
                  explanation={<BasicInformationExplanation />}
                  headerActions={
                    <PensionStatusActions
                      status={pension.status}
                      onPause={() => setShowPauseDialog(true)}
                      onResume={() => setShowResumeDialog(true)}
                    />
                  }
                >
                  <BasicInformationCard form={form} />
                </FormSection>

                {/* Contribution Details Section */}
                <FormSection
                  title="Contribution Details"
                  description="Set up your contribution plan"
                  explanation={<ContributionDetailsExplanation />}
                >
                  <ContributionDetailsCard form={form} />
                </FormSection>

                {/* Statements Section */}
                <FormSection
                  title="Statements"
                  description="Track the performance of your pension plan"
                  explanation={<StatementsExplanation />}
                >
                  <StatementsCard form={form} pensionId={pensionId} />
                </FormSection>
              </FormLayout>
            </form>
          </Form>
        )}
      </div>
      
      {/* Dialogs */}
      {showPauseDialog && (
        <PauseConfirmationDialog
          open={showPauseDialog}
          onOpenChange={setShowPauseDialog}
          onConfirm={handlePauseConfirm}
        />
      )}
      {showResumeDialog && (
        <ResumeDateDialog
          open={showResumeDialog}
          onOpenChange={setShowResumeDialog}
          onConfirm={handleResumeConfirm}
        />
      )}
    </ErrorBoundary>
  )
}

// src/svelte-frontend/src/routes/pension/insurance/[id]/edit/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { m } from '$lib/paraglide/messages.js';
	import { pensionApi } from '$lib/api/pension';
	import { pensionStore } from '$lib/stores/pension.svelte';
	import { toastStore } from '$lib/stores/toast.svelte';
	import { PensionType } from '$lib/types/pension';
	import type { InsurancePension, ContributionStep } from '$lib/types/pension';
	import PageHeader from '$lib/components/ui/PageHeader.svelte';
	import Card from '$lib/components/ui/Card.svelte';
	import ContentSection from '$lib/components/ui/ContentSection.svelte';
	import Explanation from '$lib/components/ui/Explanation.svelte';
	import ExplanationAlert from '$lib/components/ui/ExplanationAlert.svelte';
	import ExplanationList from '$lib/components/ui/ExplanationList.svelte';
	import ExplanationListItem from '$lib/components/ui/ExplanationListItem.svelte';
	import BasicInformationCard from '$lib/components/pension/insurance/BasicInformationCard.svelte';
	import StatementsCard from '$lib/components/pension/insurance/StatementsCard.svelte';
	import ContributionPlanCard from '$lib/components/pension/ContributionPlanCard.svelte';
	import PensionStatusActions from '$lib/components/pension/PensionStatusActions.svelte';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	let pensionId = $derived(data.pensionId);

	// Loading/error state
	let loadError = $state('');
	let submitting = $state(false);

	// Pension data
	let pension = $state<InsurancePension | null>(null);

	// Form state
	let name = $state('');
	let provider = $state('');
	let contractNumber = $state('');
	let startDate = $state('');
	let guaranteedInterest = $state(0); // form decimal
	let expectedReturn = $state(0); // form decimal
	let notes = $state('');

	interface ProjectionFormData {
		id: number;
		scenario_type: 'with_contributions' | 'without_contributions';
		return_rate: number;
		value_at_retirement: number;
		monthly_payout: number;
	}

	interface StatementFormData {
		id: number;
		pension_id: number;
		statement_date: string;
		value: number;
		total_contributions: number;
		total_benefits: number;
		costs_amount: number;
		costs_percentage: number;
		note?: string;
		projections: ProjectionFormData[];
	}

	let statements = $state<StatementFormData[]>([]);
	let contributionPlanSteps = $state<ContributionStep[]>([]);
	let errors = $state<Record<string, string>>({});

	function hydrateForm(p: InsurancePension) {
		name = p.name;
		provider = p.provider;
		contractNumber = p.contract_number ?? '';
		startDate = p.start_date;
		// API rates are percentages (2.0 = 2%), convert to decimals for form
		guaranteedInterest = p.guaranteed_interest != null ? p.guaranteed_interest / 100 : 0;
		expectedReturn = p.expected_return != null ? p.expected_return / 100 : 0;
		notes = p.notes ?? '';
		statements = (p.statements ?? []).map((s) => ({
			...s,
			id: s.id ?? 0,
			pension_id: s.pension_id ?? p.id,
			costs_percentage: s.costs_percentage / 100, // API % → form decimal
			projections: (s.projections ?? []).map((proj) => ({
				...proj,
				id: proj.id ?? 0,
				return_rate: proj.return_rate / 100 // API % → form decimal
			}))
		}));
		contributionPlanSteps = (p.contribution_plan_steps ?? []).map((step) => ({ ...step }));
	}

	$effect(() => {
		loadError = data.initialError;
		pension = data.initialPension;
		if (data.initialPension) {
			hydrateForm(data.initialPension);
		}
	});

	function validate(): boolean {
		const newErrors: Record<string, string> = {};
		if (!name.trim()) newErrors.name = m.insurance_pension_name_required();
		if (!startDate) newErrors.start_date = m.insurance_pension_start_date_required();
		if (!provider.trim()) newErrors.provider = m.insurance_pension_provider_required();
		errors = newErrors;
		return Object.keys(newErrors).length === 0;
	}

	async function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		if (!validate() || !pension) return;

		submitting = true;
		try {
			const pensionData = {
				name: name.trim(),
				start_date: startDate,
				provider: provider.trim(),
				contract_number: contractNumber.trim() || undefined,
				// Convert decimals back to percentages for API
				guaranteed_interest: guaranteedInterest ? guaranteedInterest * 100 : undefined,
				expected_return: expectedReturn ? expectedReturn * 100 : undefined,
				notes: notes.trim() || '',
				contribution_plan_steps: contributionPlanSteps.map((step) => ({
					id: step.id,
					amount: step.amount,
					frequency: step.frequency,
					start_date: step.start_date,
					end_date: step.end_date || undefined,
					note: step.note || ''
				}))
			};

			await pensionApi.update(PensionType.INSURANCE, pensionId, pensionData);

			// Manage statements separately:
			// - id === 0 → new statement, POST
			// - id > 0 → existing statement, PUT to update
			await Promise.all(
				statements
					.filter((s) => s.statement_date)
					.map((s) => {
						const payload = {
							statement_date: s.statement_date,
							value: s.value || 0,
							total_contributions: s.total_contributions || 0,
							total_benefits: s.total_benefits || 0,
							costs_amount: s.costs_amount || 0,
							costs_percentage: s.costs_percentage * 100, // decimal → API %
							note: s.note || '',
							projections: s.projections.map((p) => ({
								scenario_type: p.scenario_type,
								return_rate: p.return_rate * 100, // decimal → API %
								value_at_retirement: p.value_at_retirement || 0,
								monthly_payout: p.monthly_payout || 0
							}))
						};
						return s.id
							? pensionApi.updateInsurancePensionStatement(pensionId, s.id, payload)
							: pensionApi.addInsurancePensionStatement(pensionId, payload);
					})
			);

			toastStore.success(m.insurance_pension_updated());
			goto('/pension');
		} catch (error) {
			console.error('Error updating insurance pension:', error);
			toastStore.error(
				error instanceof Error ? error.message : m.insurance_pension_update_failed()
			);
		} finally {
			submitting = false;
		}
	}

	async function handlePause(pauseDate: string) {
		try {
			await pensionStore.updateStatus(PensionType.INSURANCE, pensionId, {
				status: 'PAUSED',
				paused_at: pauseDate
			});
			pension = await pensionApi.get<InsurancePension>(PensionType.INSURANCE, pensionId);
		} catch (error) {
			console.error('Error pausing pension:', error);
			toastStore.error(
				error instanceof Error ? error.message : m.insurance_pension_update_failed()
			);
		}
	}

	async function handleResume(resumeDate: string) {
		try {
			await pensionStore.updateStatus(PensionType.INSURANCE, pensionId, {
				status: 'ACTIVE',
				resume_at: resumeDate
			});
			pension = await pensionApi.get<InsurancePension>(PensionType.INSURANCE, pensionId);
		} catch (error) {
			console.error('Error resuming pension:', error);
			toastStore.error(
				error instanceof Error ? error.message : m.insurance_pension_update_failed()
			);
		}
	}
</script>

<div class="space-y-6">
	<!-- Header -->
	<div class="flex flex-col space-y-4 sm:flex-row sm:justify-between sm:space-y-0 sm:items-center">
		<PageHeader
			title={m.insurance_pension_edit_title()}
			description={m.insurance_pension_edit_description()}
		/>
		<div class="flex space-x-4 shrink-0">
			<button
				type="button"
				onclick={() => history.back()}
				class="px-4 py-2 bg-secondary hover:bg-secondary/80 text-secondary-foreground rounded-lg text-sm font-medium transition-colors"
			>
				{m.cancel()}
			</button>
			<button
				type="submit"
				form="insurance-pension-form"
				disabled={submitting}
				class="px-4 py-2 bg-primary hover:bg-primary/90 text-primary-foreground rounded-lg text-sm font-medium transition-colors disabled:opacity-50"
			>
				{m.insurance_pension_save()}
			</button>
		</div>
	</div>

	{#if loadError}
		<div class="bg-destructive/10 border border-destructive/30 rounded-xl p-4 text-destructive">
			<p>{loadError}</p>
		</div>
	{:else if !pension}
		<div class="bg-destructive/10 border border-destructive/30 rounded-xl p-4 text-destructive">
			<p>{m.insurance_pension_not_found()}</p>
		</div>
	{:else}
		<form id="insurance-pension-form" onsubmit={handleSubmit} class="space-y-8">
			<!-- Basic Information Section -->
			<ContentSection>
				{#snippet aside()}
					<Explanation>
						<p>{m.insurance_pension_explanation_intro()}</p>
						<ExplanationList>
							<ExplanationListItem><strong>{m.insurance_pension_name()}:</strong> {m.insurance_pension_explanation_name()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.insurance_pension_provider()}:</strong> {m.insurance_pension_explanation_provider()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.insurance_pension_contract_number()}:</strong> {m.insurance_pension_explanation_contract_number()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.insurance_pension_start_date()}:</strong> {m.insurance_pension_explanation_start_date()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.insurance_pension_guaranteed_interest()}:</strong> {m.insurance_pension_explanation_guaranteed()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.insurance_pension_expected_return()}:</strong> {m.insurance_pension_explanation_expected()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.insurance_pension_notes()}:</strong> {m.insurance_pension_explanation_notes()}</ExplanationListItem>
						</ExplanationList>
						<ExplanationAlert>
							{m.insurance_pension_explanation_alert()}
						</ExplanationAlert>
					</Explanation>
				{/snippet}
				<Card
					title={m.insurance_pension_basic_info()}
					description={m.insurance_pension_basic_info_edit_description()}
				>
					{#snippet headerActions()}
						<PensionStatusActions
							status={pension!.status}
							onPause={handlePause}
							onResume={handleResume}
						/>
					{/snippet}
					<BasicInformationCard
						bind:name
						bind:provider
						bind:contractNumber
						bind:startDate
						bind:guaranteedInterest
						bind:expectedReturn
						bind:notes
						{errors}
					/>
				</Card>
			</ContentSection>

			<!-- Statements Section -->
			<ContentSection>
				{#snippet aside()}
					<Explanation>
						<p>{m.insurance_pension_statements_explanation_intro()}</p>
						<ExplanationList>
							<ExplanationListItem><strong>{m.insurance_pension_value()}:</strong> {m.insurance_pension_statements_explanation_value()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.insurance_pension_total_contributions()}:</strong> {m.insurance_pension_statements_explanation_contributions()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.insurance_pension_total_benefits()}:</strong> {m.insurance_pension_statements_explanation_benefits()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.insurance_pension_costs_amount()} / {m.insurance_pension_costs_percentage()}:</strong> {m.insurance_pension_statements_explanation_costs()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.insurance_pension_projections()}:</strong> {m.insurance_pension_statements_explanation_projections()}</ExplanationListItem>
						</ExplanationList>
						<ExplanationAlert>
							{m.insurance_pension_statements_explanation_alert()}
						</ExplanationAlert>
					</Explanation>
				{/snippet}
				<Card
					title={m.insurance_pension_statements()}
					description={m.insurance_pension_statements_description()}
				>
					<StatementsCard bind:statements {pensionId} />
				</Card>
			</ContentSection>

			<!-- Contribution Plan Section -->
			<ContentSection>
				{#snippet aside()}
					<Explanation>
						<ExplanationList>
							<ExplanationListItem><strong>{m.contribution_amount()}:</strong> {m.contribution_amount()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.contribution_frequency()}:</strong> {m.contribution_frequency()}</ExplanationListItem>
							<ExplanationListItem><strong>{m.contribution_start_date()} / {m.contribution_end_date()}:</strong> {m.contribution_start_date()}</ExplanationListItem>
						</ExplanationList>
					</Explanation>
				{/snippet}
				<ContributionPlanCard bind:steps={contributionPlanSteps} />
			</ContentSection>
		</form>
	{/if}
</div>
